BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "What a TRAINER needs to stay winning…\p"
	.string "The knowledge…\n"
	.string "The strategy…\l"
	.string "The luck…\l"
	.string "The heart…\l"
	.string "The spirit…\l"
	.string "The bravery…\l"
	.string "And the raw ability…\p"
	.string "Basically, I’m built different!\n"
	.string "I’m gonna be unstoppable in every spot!\p"
	.string "Wait… POKéMON?\n"
	.string "What’s that?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "You heard about the FRONTIER\n"
	.string "BRAINS yet?\p"
	.string "That’s what SCOTT calls the seven\n"
	.string "elite TRAINERS running the facilities\l"
	.string "in the BATTLE FRONTIER. Proper bosses.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Down at the BATTLE TOWER, an older\n"
	.string "girl told me I’ve got bare talent\l"
	.string "for a scrap!\p"
	.string "But I’m more about POKéMON CONTESTS!\p"
	.string "Only problem is I’m trash at 'em!\p"
	.string "I guess having talent and actually\n"
	.string "liking the vibe aren’t the same thing.$"

