BattleFrontier_Lounge4_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring:
	.string "I wonder if they're gonna be airing\n"
	.string "interviews with the elite TRAINERS\l"
	.string "today? I’m tryna see the hype.$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere:
	.string "If I set up a food spot here, I’d be\n"
	.string "securing the bag for sure. No cap.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles:
	.string "Whew…\p"
	.string "I need to take a breather after\n"
	.string "some proper intense scraps…\p"
	.string "But even now, I’m still out here\n"
	.string "plotting the next strategy and\l"
	.string "cracking the best combos.$"

