gText_ApprenticeChallenge0::
	.string "Listen, I'm {STR_VAR_1}'s no. {STR_VAR_2} young gun.\n"
	.string "Allow it... I'm bare nervous, man.$"

gText_ApprenticeChallenge1::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} soldier!\n"
	.string "Get ready for the mash up!$"

gText_ApprenticeChallenge2::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} student!\n"
	.string "You want beef? Let's go then!$"

gText_ApprenticeChallenge3::
	.string "Yo… I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice…\n"
	.string "Think I'm gonna get smoked or what?$"

gText_ApprenticeChallenge4::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} young gun!\n"
	.string "I'll let you have a go if you want.$"

gText_ApprenticeChallenge5::
	.string "I've got bare stuff to do, but I'm still\n"
	.string "{STR_VAR_1}'s no. {STR_VAR_2} apprentice, innit.$"

gText_ApprenticeChallenge6::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} soldier.\n"
	.string "What's the word? You good?$"

gText_ApprenticeChallenge7::
	.string "I'm repping as {STR_VAR_1}'s no. {STR_VAR_2} lad.\n"
	.string "We doing this or what?$"

gText_ApprenticeChallenge8::
	.string "Rah! I'm {STR_VAR_1}'s no. {STR_VAR_2} soldier!\n"
	.string "I'm gonna put in work, believe!$"

gText_ApprenticeChallenge9::
	.string "Oi! I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Square up then, let's go!$"

gText_ApprenticeChallenge10::
	.string "I'm the main apprentice! Nah, jokes,\n"
	.string "I'm no. {STR_VAR_2}! Get ready!$"

gText_ApprenticeChallenge11::
	.string "Yeah, I'm {STR_VAR_1}'s no. {STR_VAR_2} young gun!\n"
	.string "Let's get this popping, innit!$"

gText_ApprenticeChallenge12::
	.string "Wagwan! I'm what you call\n"
	.string "{STR_VAR_1}'s no. {STR_VAR_2} student!$"

gText_ApprenticeChallenge13::
	.string "Yo! I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "What's the motive? You good?$"

gText_ApprenticeChallenge14::
	.string "This is peak, man…\n"
	.string "I'm the no. {STR_VAR_2} soldier for {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice,\n"
	.string "no word of a lie, man.$"

gText_ApprenticePleaseTeach0::
	.string "Yo… you're {PLAYER}, innit?\n"
	.string "Rah! Give me a sec…\p"
	.string "My bad, man…\n"
	.string "I'm bare gassed to meet you, still.\p"
	.string "I'm {STR_VAR_1}, and you're a legend\n"
	.string "round here, {PLAYER}.\p"
	.string "I always said to the mandem I'd\n"
	.string "link you and get the lowdown.\p"
	.string "C'mon, {PLAYER}!\n"
	.string "Give me some tips on these POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Allow it! Don't be like that…\n"
	.string "You're moving peak now!\p"
	.string "Please, man!\n"
	.string "Help a brother out!$"

gText_ApprenticeWhichLevelMode0::
	.string "Safe! You're gonna help?\n"
	.string "Mad! That's what I'm talkin' about!\p"
	.string "Trust me…\n"
	.string "You don't know how much this means.\p"
	.string "Right… give me the word then.\n"
	.string "About the BATTLE TOWER…\p"
	.string "Which one's the move: Level 50\n"
	.string "or the Open Level?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Get in!\p"
	.string "Seriously, man, my bad for\n"
	.string "moving a bit weird just now.\p"
	.string "Love for that!\n"
	.string "You're a top man.\l"
	.string "Catch you later, yeah?$"

gText_ApprenticePleaseTeach1::
	.string "Rah! You're {PLAYER}, yeah?\n"
	.string "You're moving mad with that team!\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "I'm new to the game, innit.\p"
	.string "Look, {PLAYER}!\n"
	.string "Be my mentor and show me how\l"
	.string "to run the roads as a TRAINER?$"

gText_ApprenticeRejectTeaching1::
	.string "Allow it, why not?\n"
	.string "C'mon, don't be a pagan!\l"
	.string "Just show me the ropes, man!$"

gText_ApprenticeWhichLevelMode1::
	.string "Get in! Safe for that!\p"
	.string "First thing I need to know is\n"
	.string "about the BATTLE TOWER.\p"
	.string "Level 50 or Open Level…\n"
	.string "Which one's the move for me?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, yeah? Say no more!\n"
	.string "I'm gonna smash it, trust me!\p"
	.string "Next time I see you, you've gotta\n"
	.string "give me more gems, mentor!$"

gText_ApprenticePleaseTeach2::
	.string "Yo… you {PLAYER}, yeah?\n"
	.string "I'm {STR_VAR_1}.\p"
	.string "I'm tryna get into this POKéMON\n"
	.string "game, but it's bare confusing…\p"
	.string "I heard you're the main man round\n"
	.string "here, so I came to find you.\p"
	.string "{PLAYER}, can you give me the scoop?$"

gText_ApprenticeRejectTeaching2::
	.string "But yo…\p"
	.string "I’m dead serious about getting\n"
	.string "my team sorted and making moves!\p"
	.string "C'mon, just answer one thing?$"

gText_ApprenticeWhichLevelMode2::
	.string "Safe! Respect for that!\n"
	.string "Check this, first question.\p"
	.string "The BATTLE TOWER has those two\n"
	.string "rooms, Level 50 and Open Level.\p"
	.string "Which one is actually the move\n"
	.string "for a lad like me?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, the {STR_VAR_1} challenge?\n"
	.string "Say no more! I'm on it.\p"
	.string "When I've got another query,\n"
	.string "I'll link you here for the gems!$"

gText_ApprenticePleaseTeach3::
	.string "Wait… what? You're…\n"
	.string "Nah, you're winding me up.\p"
	.string "No way a little man like me is\n"
	.string "standing here with {PLAYER}.\p"
	.string "…You're actually {PLAYER}?\n"
	.string "Rah, this is actually mental!\p"
	.string "My luck is never this good,\n"
	.string "something peak is gonna happen\l"
	.string "later, I just know it…\p"
	.string "…My bad… I’m {STR_VAR_1}…\n"
	.string "I’m just a nobody round here.\p"
	.string "You’ll probably forget my name\n"
	.string "the minute I walk off…\p"
	.string "I always said if I met you,\n"
	.string "{PLAYER}, I’d ask how to actually\l"
	.string "run the game like you do.\p"
	.string "But you’re probably too busy\n"
	.string "for a younger like me.\p"
	.string "…Or are you gonna be a legend\n"
	.string "and give me some tips?$"

gText_ApprenticeRejectTeaching3::
	.string "I knew it…\p"
	.string "Knew you'd blank me 'cause I'm\n"
	.string "just some random kid, innit.\p"
	.string "But I thought just maybe…\n"
	.string "You won't change your mind, yeah?\p"
	.string "Actually, nah, I'm not backing\n"
	.string "down yet. I'm feeling lucky!\p"
	.string "C'mon, be a legend and give\n"
	.string "me some tips?$"

gText_ApprenticeWhichLevelMode3::
	.string "Rah! Seriously? Legend!\n"
	.string "I can't believe you're actually\l"
	.string "helping a younger out!\p"
	.string "It's a bit of a basic question,\n"
	.string "but I'm bare stuck, man…\p"
	.string "At the BATTLE TOWER, they got\n"
	.string "Level 50 or Open Level.\p"
	.string "Which one's the move if I don't\n"
	.string "wanna get smoked instantly?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Safe!\n"
	.string "But you actually reckon a lad\l"
	.string "like me has got the minerals?\p"
	.string "I'll give it a go, even if it\n"
	.string "ends up being a total fail.\p"
	.string "Safe for taking the time to\n"
	.string "chat to a younger like me.$"

gText_ApprenticePleaseTeach4::
	.string "Oi! You're {PLAYER}, yeah?\p"
	.string "Word on the street is you're\n"
	.string "bare tough at POKéMON!\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "Let's link up, yeah?\p"
	.string "You heard?\p"
	.string "You can't run the BATTLE FRONTIER\n"
	.string "just using the dead stuff they\l"
	.string "teach you at school.\p"
	.string "I'm down to hear your gems.\n"
	.string "You're gonna help me, obviously?$"

gText_ApprenticeRejectTeaching4::
	.string "Huh? Why you blanking me for?\n"
	.string "I’m actually asking you, innit!\l"
	.string "Sort it out and say yes!$"

gText_ApprenticeWhichLevelMode4::
	.string "Safe, so check this.\n"
	.string "I need you to make the call.\p"
	.string "BATTLE TOWER has Level 50 and\n"
	.string "Open Level rooms, yeah?\p"
	.string "Which one’s the move for a lad\n"
	.string "like me, {PLAYER}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Safe, so {STR_VAR_1} is the one?\n"
	.string "Nice one!\p"
	.string "Since you’re the one who said it,\n"
	.string "{PLAYER}, I won’t be bare vexed\l"
	.string "if I take an L.\p"
	.string "Right, I’ll holla at you again.\n"
	.string "In a bit!$"

gText_ApprenticePleaseTeach5::
	.string "Yo, wagwan! {PLAYER}!\n"
	.string "Everyone knows your face, man!\l"
	.string "I'm {STR_VAR_1}! What's the word?\p"
	.string "I'm a TRIATHLETE, so I'm always\n"
	.string "on my fitness, even with the POKéMON.\p"
	.string "I'm bare busy though—between work,\n"
	.string "napping, and playing footy…\p"
	.string "Being this active, it’s long tryna\n"
	.string "become a proper top TRAINER.\p"
	.string "So, I’ve got a shout for you!\p"
	.string "We met for a reason, innit?\n"
	.string "So, {PLAYER}, how about you drop\l"
	.string "some gems for me every so often?$"

gText_ApprenticeRejectTeaching5::
	.string "Allow it, man, please?\n"
	.string "A guy like me needs a link like\l"
	.string "you, {PLAYER}!\p"
	.string "Real talk, I need your gems!$"

gText_ApprenticeWhichLevelMode5::
	.string "Safe! That's more like it!\n"
	.string "Right, let's start with an easy one.\p"
	.string "You know the BATTLE TOWER's\n"
	.string "two rooms, Level 50 and Open Level?\p"
	.string "I'm on a busy schedule, so which\n"
	.string "one should I be repping in?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, yeah? Say no more.\n"
	.string "I'll find a gap and give it a go!\p"
	.string "…Rah, I'm late for my shift!\n"
	.string "Love for that! See you later!$"

gText_ApprenticePleaseTeach6::
	.string "No way! Is it?!\n"
	.string "Are you actually the real {PLAYER}?\p"
	.string "Rah! Mental! I'm {STR_VAR_1},\n"
	.string "honoured to meet you, man!\p"
	.string "{PLAYER}, you're bare powerful,\n"
	.string "innit?\p"
	.string "The whole manor's talking 'bout you!\p"
	.string "Yo! I just had a madness of an idea!\n"
	.string "I'll get gems off you, {PLAYER}!\l"
	.string "I'll be a proper tank in no time!\p"
	.string "Ain't that a move?!\n"
	.string "C'mon, give me the lowdown!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, you're just acting like\n"
	.string "a tough guy, I see you!\l"
	.string "You’re actually gonna help me, yeah?$"

gText_ApprenticeWhichLevelMode6::
	.string "Get in! I knew you were sound,\n"
	.string "{PLAYER}!\p"
	.string "What’s the first move then?\n"
	.string "…Oh, I've got it!\p"
	.string "Listen up, yeah?!\n"
	.string "The question is…\p"
	.string "If I’m hitting the BATTLE TOWER,\n"
	.string "what's the best route?\p"
	.string "Level 50 or Open Level?\n"
	.string "Which one suits my vibe?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oi oi!\n"
	.string "{STR_VAR_1}, you reckon?!\l"
	.string "Safe for the sick advice, man!\p"
	.string "I think that’s me sorted for\n"
	.string "now, to be fair.\p"
	.string "Catch you in the manor later!\n"
	.string "Safe!$"

gText_ApprenticePleaseTeach7::
	.string "Safe... beg your pardon, but…\n"
	.string "Are you {PLAYER}?\p"
	.string "I'm {STR_VAR_1}. Honestly, it's a\n"
	.string "proper honor to link you.\p"
	.string "I’ve been watching your moves\n"
	.string "for bare time now…\p"
	.string "… … … … … …\p"
	.string "Um… I don't want to be long or\n"
	.string "nothing, but…\p"
	.string "Can I join your firm, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Rah…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…I think I just had a heart attack.\n"
	.string "Say you're joking, man.\p"
	.string "Please! Tell me I can roll with\n"
	.string "your crew!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Safe! I'm gassed!\p"
	.string "I won't waste your time, man,\n"
	.string "so just give me the word.\p"
	.string "I’m hitting the BATTLE TOWER\n"
	.string "pretty soon.\p"
	.string "But there’s two rooms…\p"
	.string "Which one's the move for me?\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} is the one! Safe.\n"
	.string "I see. I'm gonna put in work!\p"
	.string "Love for that, {PLAYER}.\n"
	.string "I'll holla at you again soon.\l"
	.string "Keep it real!$"

gText_ApprenticePleaseTeach8::
	.string "Rah! Rah! {PLAYER}!\n"
	.string "You actually spoke to me!\l"
	.string "I’m bare gassed, man!\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "I just started out, innit!\p"
	.string "I'm so hyped I met you, {PLAYER},\n"
	.string "the biggest name in the game!\p"
	.string "Oi, I’ve got a massive shout!\n"
	.string "Can I roll as your apprentice?\l"
	.string "I need to learn your ways!$"

gText_ApprenticeRejectTeaching8::
	.string "Rah! {PLAYER} just blanked me…\n"
	.string "Even that's a madness, to be fair!\p"
	.string "{PLAYER}, c'mon! Say it with me\n"
	.string "one time—say yes!\p"
	.string "I’m begging for the blueprint, man!$"

gText_ApprenticeWhichLevelMode8::
	.string "Oi! {PLAYER} said safe!\n"
	.string "{PLAYER} said safe!\p"
	.string "I’m not gonna sleep for bare time…\n"
	.string "Love for that, seriously!\p"
	.string "Right, here’s the motive!\p"
	.string "At the BATTLE TOWER, what’s the move\n"
	.string "for me? Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Say no more!\n"
	.string "I hear that, loud and clear!\l"
	.string "I’m absolutely gassed, man!\p"
	.string "You’ve gotta drop more knowledge\n"
	.string "for me another time, yeah?$"

gText_ApprenticePleaseTeach9::
	.string "Wait! Are you…\n"
	.string "Is it actually… {PLAYER}?!\l"
	.string "The sickest TRAINER in the manor?\l"
	.string "Rah, I’m the luckiest guy alive!\p"
	.string "Yo, I’m {STR_VAR_1}!\p"
	.string "I’ve been tryna find a mentor\n"
	.string "who actually knows the game.\p"
	.string "And then you just roll up,\n"
	.string "{PLAYER}! Perfect timing!\p"
	.string "So, check it, {PLAYER}!\n"
	.string "Let me roll with your firm!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "You’re bare cold and tough…\p"
	.string "Don’t be a hater, man.\n"
	.string "I’m asking you nicely!$"

gText_ApprenticeWhichLevelMode9::
	.string "Safe! That’s a solid answer!\n"
	.string "Top tier, man!\p"
	.string "So give me the first bit of gems\n"
	.string "on the BATTLE TOWER.\p"
	.string "If I’m going in, what’s better?\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Safe, bare safe!\l"
	.string "I’m gonna go smash it, trust me!\p"
	.string "Right, you're my mentor now!\n"
	.string "In a bit!$"

gText_ApprenticePleaseTeach10::
	.string "Oi, {PLAYER}, yeah?\n"
	.string "The feds were looking for you!\p"
	.string "… … …\n"
	.string "Only joking, man! Gotcha!\p"
	.string "I'm {STR_VAR_1}. Look, I’m actually the\n"
	.string "POKéMON CHAMPION, believe!\l"
	.string "…Nah, that's a lie as well.\p"
	.string "No lie though—\n"
	.string "I’m actually dead at battling.\p"
	.string "So, how about you become my master\n"
	.string "for all things POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "If you’re gonna be cold like that,\n"
	.string "watch how I moving now!\p"
	.string "Waaah! Waaah! Look at me go!\n"
	.string "Sike!\p"
	.string "Hahaha, you actually thought I was\n"
	.string "crying? You're moist, man!\p"
	.string "C'mon, be a legend and become\n"
	.string "my POKéMON master?$"

gText_ApprenticeWhichLevelMode10::
	.string "Get in!\n"
	.string "I’ll buy you a whip for that!\p"
	.string "Only joking again! I'm skint!\n"
	.string "But… Love for that, master!\p"
	.string "You know how there's Level 50 and\n"
	.string "Open Level at the BATTLE TOWER?\p"
	.string "I'm bare stuck deciding which\n"
	.string "level I should challenge…\p"
	.string "Make the call for me, master?$"

gText_ApprenticeLevelModeThanks10::
	.string "Safe, so {STR_VAR_1} is better?\n"
	.string "I'll go to the other level, then!\p"
	.string "Just kidding! Don't look at me\n"
	.string "like that! I'll do what you say.\p"
	.string "Safe, master!\n"
	.string "Keep dropping those gems for me!$"

gText_ApprenticePleaseTeach11::
	.string "Yo! Yo! Yo!\n"
	.string "Check the flow, here I go!\p"
	.string "I'm {STR_VAR_1}, the sickest sailor\n"
	.string "on the mic, don't be a hater!\p"
	.string "Your turn now, tell me your name,\n"
	.string "don't be shy, step into the frame!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}'s your name,\l"
	.string "and POKéMON's your game!\p"
	.string "You’re just a young lad tryna\n"
	.string "find your way in this mad city!\p"
	.string "Anyway, I just want to say,\n"
	.string "you're the tenth person I've\l"
	.string "tried to spit bars at today.\p"
	.string "Let's celebrate the link up!\n"
	.string "Be my mentor and keep my rank up!$"

gText_ApprenticeRejectTeaching11::
	.string "But!\n"
	.string "You gotta work with me, man!\p"
	.string "Don't be a pagan, don't be a tease!\n"
	.string "Be my mentor, pretty please!$"

gText_ApprenticeWhichLevelMode11::
	.string "That's it!\n"
	.string "{PLAYER}, you've got the spirit!\p"
	.string "So here's my first question\n"
	.string "now let's hear you spit it!\p"
	.string "It's about the BATTLE TOWER,\n"
	.string "do I have the speed and the power?\p"
	.string "Level 50 and Open Level, you see,\n"
	.string "which one is the motive for me?$"

gText_ApprenticeLevelModeThanks11::
	.string "Safe, {STR_VAR_1} it is, you say!\n"
	.string "I'll go smash it, starting today!\p"
	.string "If I need a link for a strategy,\n"
	.string "{PLAYER}, I’ll holla at you, G!$"

gText_ApprenticePleaseTeach12::
	.string "Oi, hold up, ain't you {PLAYER}?\n"
	.string "Should I chat to you? Why not?\l"
	.string "I’m already doing it, innit!\p"
	.string "{PLAYER}, you look bare shocked!\n"
	.string "I better tell you who I am before\l"
	.string "you get me locked!\p"
	.string "{STR_VAR_1} is the name. The sickest\n"
	.string "guitarist in the whole manor!\p"
	.string "You feeling me?\n"
	.string "I know you're feeling me!\p"
	.string "I'm feeling lucky today,\n"
	.string "so I've got a request, okay?\p"
	.string "{PLAYER}, let me roll with you!\n"
	.string "Teach me everything you do!$"

gText_ApprenticeRejectTeaching12::
	.string "You’re blanking me? For real?\n"
	.string "I’m just gonna ask you again!\p"
	.string "{PLAYER}, let me roll with you!\n"
	.string "I need the full blueprint, man!$"

gText_ApprenticeWhichLevelMode12::
	.string "Get in! Woohoo!\n"
	.string "I can drop a question to you?\p"
	.string "Since we’re by the BATTLE TOWER,\n"
	.string "how do I get the most power?\p"
	.string "Of the choices you see,\n"
	.string "which is the motive for me?$"

gText_ApprenticeLevelModeThanks12::
	.string "If {STR_VAR_1} is the one you say,\n"
	.string "it’s gotta be the best way!\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me.\p"
	.string "Catch you later, my smart friend!$"

gText_ApprenticePleaseTeach13::
	.string "Oi, watch the shoulder, man!\n"
	.string "Just did bare reps at the gym.\p"
	.string "…Rah, right there! Ouch!\n"
	.string "Actually, that's not too bad.\p"
	.string "Name's {STR_VAR_1}. I do MMA and that,\n"
	.string "but my body’s taking a beating…\p"
	.string "Decided I’ll hit the POKéMON instead\n"
	.string "to keep my status up.\p"
	.string "You're {PLAYER}, yeah?\n"
	.string "The main man in the LEAGUE?\p"
	.string "Listen, can you drop some gems\n"
	.string "for a brother?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, why?\p"
	.string "I won't be a wasteman, I promise!\n"
	.string "C'mon?$"

gText_ApprenticeWhichLevelMode13::
	.string "Safe. Proper decent of you!\n"
	.string "…*Cough!*\p"
	.string "Ugh, I need to get tough, fast.\p"
	.string "I’m hitting the BATTLE TOWER now,\n"
	.string "but what's the move for me?\l"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, safe. So {STR_VAR_1} it is.\n"
	.string "I'll head over there now.\p"
	.string "I'll keep hollering at you for help,\n"
	.string "since you're my mentor now, innit!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Um…\n"
	.string "{PLAYER}…?\p"
	.string "Please, don't look at me like that.\n"
	.string "You're making me bare awkward.\p"
	.string "I… I'm {STR_VAR_1}.\p"
	.string "It’s a bit peak to say this, but\n"
	.string "I spend my time in ruins and that.\p"
	.string "It’s even more bait to admit I’m\n"
	.string "actually into the BATTLE FRONTIER.\p"
	.string "{PLAYER}, you've got a rep as\n"
	.string "the toughest guy on the roads…\p"
	.string "It’s hard for me to ask, but…\p"
	.string "Can you be my mentor and give\n"
	.string "me the lowdown?$"

gText_ApprenticeRejectTeaching14::
	.string "Don't just air me like that, man!\n"
	.string "I’ll look like a proper melon.\p"
	.string "C'mon, be my mentor!\n"
	.string "I need those gems!$"

gText_ApprenticeWhichLevelMode14::
	.string "S-safe... nice one.\p"
	.string "But stop staring at me like that.\n"
	.string "It’s making me bare shook.\p"
	.string "Just give me the word, yeah?\n"
	.string "Don't even look at me.\p"
	.string "At the BATTLE TOWER…\n"
	.string "Which level should I move to?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Safe!\n"
	.string "I'll give that a go then.\p"
	.string "Hopefully I can put in work\n"
	.string "without getting bare rattled…\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "If I see you again, don't be\l"
	.string "a stranger, yeah?$"

gText_ApprenticePleaseTeach15::
	.string "Wait... you look like {PLAYER}…\n"
	.string "But are you actually the real deal?\p"
	.string "You can call me {STR_VAR_1}.\p"
	.string "I've been thinking about getting\n"
	.string "put on by a top-tier TRAINER.\p"
	.string "So, lucky me that you rolled up!\n"
	.string "…You’re definitely {PLAYER}, yeah?\p"
	.string "Nah, if you're legit, it’s calm.\n"
	.string "I just need you to recognize me\l"
	.string "as part of your firm.$"

gText_ApprenticeRejectTeaching15::
	.string "Eh?\n"
	.string "Why you acting like that for?\p"
	.string "My bad for questioning if you\n"
	.string "were the main man or not.\p"
	.string "Drop the attitude and let me\n"
	.string "roll with your crew, man.$"

gText_ApprenticeWhichLevelMode15::
	.string "You’re actually saying safe?\n"
	.string "I’m not gonna hype it up yet.\p"
	.string "If you're serious, my bad.\n"
	.string "But now, I need the lowdown.\p"
	.string "If I hit the BATTLE TOWER,\n"
	.string "what’s actually worth my time?\l"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "You sure about that?\p"
	.string "I hear you. If that's the word, calm.\n"
	.string "Love for the time, man.\p"
	.string "I know I can be long, but I'm\n"
	.string "gassed that I'm in the firm now.\p"
	.string "Catch you later!$"

gText_ApprenticeWhatHeldItem0::
	.string "Rah… give me a sec…\n"
	.string "Oh, {PLAYER}!\p"
	.string "I’m in a proper pickle, man,\n"
	.string "I can't make a decision.\p"
	.string "I don't know what gear I should\n"
	.string "give my {STR_VAR_1} to hold.\p"
	.string "Tell me straight, {PLAYER}.\n"
	.string "What item should it be repping?$"

gText_ApprenticeHoldNothing0::
	.string "Wait, for real? I shouldn't give\n"
	.string "my {STR_VAR_1} any gear at all?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Safe! I'm gassed that’s sorted!\n"
	.string "Mad! Sick! Get in!\p"
	.string "Love for that, seriously!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, safe…\n"
	.string "I think I’ve got {STR_VAR_1} in my bag.\p"
	.string "I’m gassed that’s sorted!\n"
	.string "Mad! Sick! Get in!\p"
	.string "Love for that, seriously!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Allow it! Don't be a hater!\p"
	.string "Someone already told me to use\n"
	.string "{STR_VAR_1} before, man…\p"
	.string "Or are you saying I should let\n"
	.string "my {STR_VAR_2} go in empty-handed?$"

gText_ApprenticeWhatHeldItem1::
	.string "Get in! It’s {PLAYER}!\n"
	.string "Sick! I needed to ask you a favor!\p"
	.string "Do you kit out your POKéMON with items?\n"
	.string "I wanna give mine some flavor, but…\p"
	.string "What item would look sick on\n"
	.string "{STR_VAR_1}?\p"
	.string "What’s the word?$"

gText_ApprenticeHoldNothing1::
	.string "Eh? You reckon my {STR_VAR_1} doesn't\n"
	.string "need to hold anything?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, I hear that! I’ll do that then!\n"
	.string "Safe for the gems!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, rah! {STR_VAR_1}, yeah?\n"
	.string "Safe, I’m on it!\p"
	.string "Safe for the gems!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Nah, that ain't it, man.\n"
	.string "I want something different to what\l"
	.string "the other manndem told me.\p"
	.string "Or are you saying my POKéMON should\n"
	.string "just roll out with no gear this time?$"

gText_ApprenticeWhatHeldItem2::
	.string "Yo {PLAYER}, wagwan!\n"
	.string "It's about my {STR_VAR_1}…\p"
	.string "I need to get it some proper kit.\n"
	.string "What's the best look for it?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, so my {STR_VAR_1} is rolling\n"
	.string "with no gear? You sure?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Safe, I hear that!\n"
	.string "Catch you later!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, {STR_VAR_1}, yeah?\n"
	.string "Say no more!\p"
	.string "I'll go hunt one down now!\n"
	.string "In a bit!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Someone already dropped that knowledge\n"
	.string "about the {STR_VAR_1} to me.\p"
	.string "I want my POKéMON to rep a\n"
	.string "different kind of item, innit.\p"
	.string "Or do you reckon {STR_VAR_2} doesn't\n"
	.string "need to hold anything?$"

gText_ApprenticeWhatHeldItem3::
	.string "Yo, {PLAYER}…\n"
	.string "Sorry to be long, but I've got\l"
	.string "another query for you.\p"
	.string "I don't think I'm tough enough to\n"
	.string "get the win on my own, so I'm tryna\l"
	.string "give my {STR_VAR_1} some gear.\p"
	.string "But I'm bare stuck on what's good.\p"
	.string "{PLAYER}, c'mon, make the call\n"
	.string "for me?$"

gText_ApprenticeHoldNothing3::
	.string "You reckon a younger like me\n"
	.string "is better off with no items at all?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "I hear you…\n"
	.string "You're saying I shouldn't rely on kit.\l"
	.string "I'll try and put in work without it!\p"
	.string "Love for that, man!$"

gText_ApprenticeThanksHeldItem3::
	.string "{STR_VAR_1}, okay.\n"
	.string "Dunno if I can even find one…\l"
	.string "Nah, I'll go all out to get it.\p"
	.string "Love for that, man!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, but…\n"
	.string "I think I've heard that one before…\p"
	.string "Is it 'cause I'm moving peak with\n"
	.string "the {STR_VAR_1} or what?\p"
	.string "Or are you saying I shouldn't give\n"
	.string "my {STR_VAR_2} anything?$"

gText_ApprenticeWhatHeldItem4::
	.string "Yo, {PLAYER}.\n"
	.string "I need a quick word with you.\p"
	.string "You already picked out which\n"
	.string "POKéMON I should be using, yeah?\p"
	.string "But we never chatted about what\n"
	.string "gear it needs to be repping.\p"
	.string "Since you started this, you gotta\n"
	.string "finish the job, innit?\p"
	.string "What’s the move? I need to give\n"
	.string "my {STR_VAR_1} some proper kit.$"

gText_ApprenticeHoldNothing4::
	.string "Rah! So my {STR_VAR_1} should just\n"
	.string "go in raw with no items?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "If you reckon that’s the move, I’m on it.\p"
	.string "Since you made the call, {PLAYER},\n"
	.string "I won’t be bare vexed if I take\l"
	.string "an L.\p"
	.string "Safe, I’ll holla at you again soon.\n"
	.string "In a bit!$"

gText_ApprenticeThanksHeldItem4::
	.string "The {STR_VAR_1}, yeah?\n"
	.string "Not bad. I’ll run with that!\p"
	.string "Since you made the call, {PLAYER},\n"
	.string "I won’t be bare vexed if I take\l"
	.string "an L.\p"
	.string "Safe, I’ll holla at you again soon.\n"
	.string "In a bit!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Eh? What you on about?\n"
	.string "You already told me about the\l"
	.string "{STR_VAR_1} last time.\p"
	.string "Or are you saying my {STR_VAR_2} should\n"
	.string "just go in raw with no items?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}!\p"
	.string "We’re both bare busy, but we keep\n"
	.string "linking up in the manor anyway!\p"
	.string "Today I’ve got to do the chores—\n"
	.string "cleaning, hoovering, all that.\p"
	.string "I haven’t even had a sec to buy\n"
	.string "my boy {STR_VAR_1} any new gear.\p"
	.string "I’m on a tight schedule, so just\n"
	.string "give me the lowdown on what my\l"
	.string "{STR_VAR_1} should be holding?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, so since I'm a busy man, you\n"
	.string "reckon my {STR_VAR_1} doesn't need kit?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Safe, gotcha.\n"
	.string "Saves me some time, to be fair.\p"
	.string "Safe for today!\n"
	.string "Catch you later!$"

gText_ApprenticeThanksHeldItem5::
	.string "Safe, gotcha.\n"
	.string "I’ll find a gap in the schedule and\l"
	.string "grab that {STR_VAR_1} you mentioned.\p"
	.string "Glad I got a proper mentor like you.\n"
	.string "Safe! In a bit!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Eh? I already know about\n"
	.string "that {STR_VAR_1}, man.\p"
	.string "Oh, right, I see the vibe.\n"
	.string "Since I'm a busy man, you're saying\l"
	.string "my {STR_VAR_2} doesn't need kit?$"

gText_ApprenticeWhatHeldItem6::
	.string "Oi oi, {PLAYER}! It's me!\n"
	.string "Need to pick your brain again today.\l"
	.string "C'mon, drop some gems for me!\p"
	.string "Listen up, yeah?!\n"
	.string "The big question is…\p"
	.string "If I want to make my {STR_VAR_1} hold\n"
	.string "an item, what gear should it be?$"

gText_ApprenticeHoldNothing6::
	.string "Is that the word? My {STR_VAR_1} is\n"
	.string "better off with no gear, you reckon?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Safe, that's what I'll do!\p"
	.string "I think that’s me sorted for\n"
	.string "now, to be fair.\p"
	.string "Catch you in the manor later!\n"
	.string "Safe!$"

gText_ApprenticeThanksHeldItem6::
	.string "Oi oi! One {STR_VAR_1}.\n"
	.string "That is a sick choice!\l"
	.string "I'm definitely running with that!\p"
	.string "I think that’s me sorted for\n"
	.string "now, to be fair.\p"
	.string "Catch you in the manor later!\n"
	.string "Safe!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahaha! You're moving mad!\n"
	.string "You already told me about that\l"
	.string "{STR_VAR_1} before!\p"
	.string "You feeling alright, {PLAYER}?\p"
	.string "Wait! Are you saying my {STR_VAR_2}\n"
	.string "doesn't need to hold any gear?$"

gText_ApprenticeWhatHeldItem7::
	.string "Safe, {PLAYER}. Hope you've been\n"
	.string "keeping it real.\p"
	.string "Can I ask you for a quick favor?\p"
	.string "In my last match, the other guy\n"
	.string "had bare items on his POKéMON.\p"
	.string "I got smoked, basically…\p"
	.string "I'm not tryna be left behind.\n"
	.string "I need my {STR_VAR_1} to rep\l"
	.string "an item as well.\p"
	.string "Be a legend and tell me what's\n"
	.string "actually the move for my POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "So you're saying… my POKéMON\n"
	.string "doesn't actually need any kit?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "I hear you loud and clear!\n"
	.string "I'll keep putting in work like this.\p"
	.string "Love for that, {PLAYER}.\n"
	.string "I'll holla at you again soon.\l"
	.string "Keep it real!$"

gText_ApprenticeThanksHeldItem7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I'll get that shipped right away.\p"
	.string "Love for that, {PLAYER}.\n"
	.string "I'll holla at you again soon.\l"
	.string "Keep it real!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "You already dropped that knowledge,\n"
	.string "and I've got the item already.\p"
	.string "Or are you saying… my POKéMON\n"
	.string "doesn't actually need any kit?$"

gText_ApprenticeWhatHeldItem8::
	.string "Rah! {PLAYER}!\n"
	.string "I’m bare gassed to see you again!\p"
	.string "Oi! There’s something I just\n"
	.string "had to ask you, {PLAYER}!\p"
	.string "Make the call on what gear my\n"
	.string "{STR_VAR_1} should be repping!$"

gText_ApprenticeHoldNothing8::
	.string "Rah! I didn't expect that answer!\n"
	.string "So I don't need an item at all?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Say no more! I hear that!\n"
	.string "I'll keep at it without an item!\p"
	.string "I hope you’ll drop more gems for\n"
	.string "me another time, yeah?$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! I'm on it!\p"
	.string "Wait… is that because you also\n"
	.string "use that item on your team?\p"
	.string "I’m definitely grabbing one!\n"
	.string "I hope you’ll drop more gems for\l"
	.string "me another time, yeah?$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Eh? You recommended that\n"
	.string "{STR_VAR_1} before, too.\p"
	.string "Is that just the best one to rep?\n"
	.string "Or are you saying my {STR_VAR_2}\l"
	.string "doesn't need anything at all?$"

gText_ApprenticeWhatHeldItem9::
	.string "Yo!\n"
	.string "My mentor, {PLAYER}!\p"
	.string "I need to hit you up for gems on\n"
	.string "POKéMON gear.\p"
	.string "What do you reckon is the best look\n"
	.string "for my {STR_VAR_1} to rep?\p"
	.string "Don't be shy, man.\n"
	.string "Spit it out!$"

gText_ApprenticeHoldNothing9::
	.string "Eh? So you're saying my {STR_VAR_1}\n"
	.string "can smash it with no gear at all?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Safe, respect!\n"
	.string "I'll give it my best shot, trust me!\p"
	.string "Safe for that, as always!\n"
	.string "In a bit!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, {STR_VAR_1}, yeah?\n"
	.string "Safe, respect!\l"
	.string "I'll go find me one right now!\p"
	.string "Safe for that, as always!\n"
	.string "In a bit!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Nah, nah! You already dropped that\n"
	.string "knowledge on {STR_VAR_1} before.\p"
	.string "Wait... hold up a sec…\n"
	.string "So you're saying my {STR_VAR_2}\l"
	.string "can win without holding any gear?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}, you won't believe\n"
	.string "the madness that just happened!\p"
	.string "I woke up and my POKéMON had\n"
	.string "stacked 10 NUGGETS!\p"
	.string "Sike! Only joking!\n"
	.string "Hahaha!\p"
	.string "Real talk though—\n"
	.string "I'm dead at picking gear for\l"
	.string "my team to hold.\p"
	.string "So, make the call for me. What\n"
	.string "should my {STR_VAR_1} rep, master?$"

gText_ApprenticeHoldNothing10::
	.string "What's the word?\n"
	.string "Don't give it any kit at all?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Safe, so no gear. Right then,\n"
	.string "I'll go buy the most expensive item!\p"
	.string "Sike! I'm listening, master!\n"
	.string "I'll do exactly what you say.\p"
	.string "Safe, master!\n"
	.string "Keep the gems coming!$"

gText_ApprenticeThanksHeldItem10::
	.string "Safe, so one {STR_VAR_1}!\n"
	.string "I'll give it anything but that!\p"
	.string "Gotcha! Joking again!\n"
	.string "I'll obey your word, master!\p"
	.string "Safe, master!\n"
	.string "Keep the gems coming!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Wait, you told me that before,\n"
	.string "didn't you?\p"
	.string "Ain't there something else?\p"
	.string "Or do you mean I shouldn't give\n"
	.string "my {STR_VAR_2} any kit at all?$"

gText_ApprenticeWhatHeldItem11::
	.string "Yo! Yo! Yo!\n"
	.string "Check the flow, here I go!\p"
	.string "The sickest sailor on the mic!\n"
	.string "Got a question you might like!\p"
	.string "It's a question about gear,\n"
	.string "so lend me your legendary ear!\p"
	.string "My {STR_VAR_1} needs an item to rep,\n"
	.string "help me out and watch my step?$"

gText_ApprenticeHoldNothing11::
	.string "Is that the vibe?\n"
	.string "My {STR_VAR_1} doesn't need to be\l"
	.string "decked out to survive?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Safe, I hear you, loud and clear!\n"
	.string "Empty-handed, I have no fear!\p"
	.string "If I need a link for a strategy,\n"
	.string "{PLAYER}, I'll holla at you, G!$"

gText_ApprenticeThanksHeldItem11::
	.string "Safe, {STR_VAR_1}, that's the one.\n"
	.string "I knew you'd get the job done!\p"
	.string "If I need a link for a strategy,\n"
	.string "{PLAYER}, I'll holla at you, G!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Wait, {STR_VAR_1}, you say?\n"
	.string "You told me that the other day.\l"
	.string "I need a new look, a fresh way.\p"
	.string "Or, wait, is that the vibe?\n"
	.string "My POKéMON doesn't need kit\l"
	.string "to survive?$"

gText_ApprenticeWhatHeldItem12::
	.string "Oi oi, {PLAYER}!\n"
	.string "Linked you again today, innit!\p"
	.string "Should I get your gems? Why not?\n"
	.string "I’m already chatting to you, yeah!\p"
	.string "{PLAYER}, you getting bare fed up with\n"
	.string "me? Nah, no way, that’s not the vibe.\p"
	.string "Hear me out one time!\n"
	.string "I need the blueprint—that’s what\l"
	.string "I’m on about today.\p"
	.string "It’s about gear for my {STR_VAR_1}.\n"
	.string "Thinking about it is making me head spin.$"

gText_ApprenticeHoldNothing12::
	.string "My {STR_VAR_1} needs zero gear?\n"
	.string "Rolling out with nothing?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "If going in raw is the best,\n"
	.string "I’ll do what you suggest!\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me.\p"
	.string "Catch you later, my smart friend!$"

gText_ApprenticeThanksHeldItem12::
	.string "If repping that {STR_VAR_1} is\n"
	.string "the one, I’ll get it done!\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me.\p"
	.string "Catch you later, my smart friend!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Haven’t I heard about that\n"
	.string "{STR_VAR_1} before?\l"
	.string "I’m certain I have, for sure!\p"
	.string "I need a fresh something!\n"
	.string "Or, my {STR_VAR_2} needs nothing?\l"
	.string "Rolling out with nothing?$"

gText_ApprenticeWhatHeldItem13::
	.string "Rah! Ouch! {PLAYER}, my arm’s dead!\n"
	.string "Don’t touch it, man!\p"
	.string "Must’ve pulled it while I was tryna\n"
	.string "sort out gear for my squad of\l"
	.string "POKéMON.\p"
	.string "Since I’m a bit out of action,\n"
	.string "I need you to make the call.\p"
	.string "{PLAYER}, what do you reckon would\n"
	.string "be good for my {STR_VAR_1} to rep?$"

gText_ApprenticeHoldNothing13::
	.string "Ouch…\p"
	.string "So you reckon my {STR_VAR_1} shouldn't\n"
	.string "be repping any gear at all?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, safe. That would be easier\n"
	.string "for me, the way I’m feeling now.\p"
	.string "I’ll keep hollering at you for help\n"
	.string "like this, yeah?$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, safe. {STR_VAR_1} it is.\n"
	.string "My POKéMON’s arm is fine, so I’ll give\l"
	.string "it that kit right away.\p"
	.string "I’ll keep hollering at you for help\n"
	.string "like this, yeah?$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Nah, man, you told me about that\n"
	.string "{STR_VAR_1} before, remember?\p"
	.string "How about dropping something\n"
	.string "even better?\p"
	.string "Oh, wait a sec.\n"
	.string "So you reckon my {STR_VAR_2} shouldn't\l"
	.string "be repping any gear at all?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Um…\n"
	.string "{PLAYER}…\p"
	.string "Please, don't look at me like that.\n"
	.string "My POKéMON haven't got any kit.\p"
	.string "I… I'm bare embarrassed about this,\n"
	.string "but I really need your gems.\p"
	.string "I can't decide what gear would\n"
	.string "make my {STR_VAR_1} look tough.\p"
	.string "{PLAYER}, what do you reckon?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… So you think it’s better if\n"
	.string "my {STR_VAR_1} doesn't have an item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Safe!\n"
	.string "I'll go with zero gear then.\p"
	.string "This is bare nerve-racking, though.\n"
	.string "Would that actually be a sick move?\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "If we link up again, don't be\l"
	.string "a stranger.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Safe!\n"
	.string "I'll go with that {STR_VAR_1}.\p"
	.string "This is bare nerve-racking, though.\n"
	.string "Would that actually be a sick move?\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "If we link up again, don't be\l"
	.string "a stranger.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-but I already heard about that.\p"
	.string "Don't just air me like this, man!\n"
	.string "I’ll look like a proper melon.\p"
	.string "Oh… Am I getting it twisted?\n"
	.string "Do you think it’s better if\l"
	.string "my {STR_VAR_2} doesn't have an item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Wait... you look like {PLAYER}…\n"
	.string "But are you actually legit?\l"
	.string "Maybe you’re just a lookalike?\p"
	.string "Nah, nah, don’t stress!\n"
	.string "If you’re the real {PLAYER}, just\l"
	.string "ignore me being cheeky.\p"
	.string "What I need is some more of\n"
	.string "your top-tier gems.\p"
	.string "I’ve got my {STR_VAR_1} here and I want\n"
	.string "to give it some decent gear.\p"
	.string "What’s actually worth repping?$"

gText_ApprenticeHoldNothing15::
	.string "It’s better with zero gear?\n"
	.string "You’re 100% on that?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "I hear you. If that's the word, calm.\n"
	.string "Love for the time, man.\p"
	.string "Catch you later!$"

gText_ApprenticeThanksHeldItem15::
	.string "One {STR_VAR_1}?\n"
	.string "You’re 100% on that?\p"
	.string "I hear you. If that's the word, calm.\n"
	.string "Love for the time, man.\p"
	.string "Hopefully my POKéMON can actually\n"
	.string "put in work with it.\p"
	.string "Catch you later!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Nah, nah, hold up a sec.\n"
	.string "You already dropped that one before.\p"
	.string "I need you to recommend a fresh\n"
	.string "look for me this time.\p"
	.string "Or are you saying my {STR_VAR_2}\n"
	.string "should just roll out with nothing?\l"
	.string "You’re 100% on that?$"

gText_ApprenticeWhichMonFirst0::
	.string "Rah, {PLAYER}!\n"
	.string "I’m in a proper state, man…\p"
	.string "I wanna start battling the mandem,\n"
	.string "but I’m moving bare slow.\p"
	.string "How should I line up my squad\n"
	.string "so we’re moving correct?\p"
	.string "Tell me straight, {PLAYER}.\n"
	.string "If it was you, which of these would\l"
	.string "you send out to lead?$"

gText_ApprenticeMonFirstThanks0::
	.string "My {STR_VAR_1} should lead?\n"
	.string "Get in!\p"
	.string "Safe, my bad for getting emotional!\n"
	.string "I’m just gassed you picked my\l"
	.string "starter. It's a madness!\p"
	.string "Love for that, seriously!$"

gText_ApprenticeWhichMonFirst1::
	.string "Get in! It’s {PLAYER}!\n"
	.string "Sick! I needed to ask you a favor!\p"
	.string "Of my team, who do you reckon\n"
	.string "is the best to send out first?$"

gText_ApprenticeMonFirstThanks1::
	.string "My {STR_VAR_1}? Say no more.\n"
	.string "Safe, I’m on it!\p"
	.string "Safe for the gems!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, wagwan!\p"
	.string "I reckon in a battle, the first\n"
	.string "move and the lead POKéMON are key.\p"
	.string "Out of my squad here, who should\n"
	.string "be repping the front line?$"

gText_ApprenticeMonFirstThanks2::
	.string "My {STR_VAR_1} leads the way?\n"
	.string "Safe, I hear that!\p"
	.string "In a bit!$"

gText_ApprenticeWhichMonFirst3::
	.string "Yo, {PLAYER}…\n"
	.string "Sorry to be long again, but I’ve got\l"
	.string "another query for you.\p"
	.string "I’ve got zero confidence, man. I’d be\n"
	.string "moving peak without you, {PLAYER}.\p"
	.string "It’s probably a waste of time even\n"
	.string "stressing, but I’m bare stuck…\p"
	.string "Which of my squad should I send\n"
	.string "out first in a scrap?$"

gText_ApprenticeMonFirstThanks3::
	.string "My {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I can’t believe you’d even bother\n"
	.string "dropping gems for me so often!\p"
	.string "I’m bare grateful you even chat\n"
	.string "to me… Love for that!$"

gText_ApprenticeWhichMonFirst4::
	.string "Yo, {PLAYER}! It’s me!\n"
	.string "Gassed to see you ‘cause I’ve got\l"
	.string "this little problem.\p"
	.string "I can’t decide how my squad should\n"
	.string "be lined up. Can you make the call?\p"
	.string "Nah, you don’t need to sort the whole\n"
	.string "crew right now.\p"
	.string "How about just picking the lead\n"
	.string "POKéMON for me?$"

gText_ApprenticeMonFirstThanks4::
	.string "My {STR_VAR_1}? That’s sick!\p"
	.string "Since you made the call, {PLAYER},\n"
	.string "I won’t be bare vexed if I take\l"
	.string "an L.\p"
	.string "Safe, I’ll holla at you again soon.\n"
	.string "In a bit!$"

gText_ApprenticeWhichMonFirst5::
	.string "Yo, my mentor {PLAYER}!\n"
	.string "I’m on a madness again today!\p"
	.string "I’ve got cycling, shopping, and\n"
	.string "tunes to listen to.\p"
	.string "I haven’t even had a sec to decide\n"
	.string "how to line up my crew.\p"
	.string "So, have a look at the team.\n"
	.string "Which one should lead?$"

gText_ApprenticeMonFirstThanks5::
	.string "Safe, gotcha.\n"
	.string "I’ve got enough time at least to put\l"
	.string "my {STR_VAR_1} at the front of the line!\p"
	.string "Rah, the missus is waiting!\n"
	.string "Safe! Catch you later!$"

gText_ApprenticeWhichMonFirst6::
	.string "Oi oi! Hiya, {PLAYER}!\n"
	.string "You’re always walking around repping\l"
	.string "that tough look!\p"
	.string "Listen, I need a favor again!\n"
	.string "The usual business, yeah?\p"
	.string "Drum roll, please!\n"
	.string "The question is about the squad…\p"
	.string "Which POKéMON of mine should be the\n"
	.string "one to lead the charge?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "My {STR_VAR_1}, you say!\l"
	.string "That is a proper sick answer!\p"
	.string "I reckon that’s all I needed to\n"
	.string "bother you with today.\p"
	.string "Catch you in the manor later, yeah?\n"
	.string "Safe!$"

gText_ApprenticeWhichMonFirst7::
	.string "Safe for stopping to chat with me,\n"
	.string "{PLAYER}. Proper decent of you.\p"
	.string "I know I’m being a bit long,\n"
	.string "but can I get some advice?\p"
	.string "I need to sort out the order\n"
	.string "of my POKéMON squad.\p"
	.string "Be a legend and decide which\n"
	.string "POKéMON should lead the line.$"

gText_ApprenticeMonFirstThanks7::
	.string "My {STR_VAR_1} it is!\n"
	.string "I’ll swap the order right now!\p"
	.string "Love for that, {PLAYER}.\n"
	.string "I’ll holla at you again soon.\l"
	.string "Keep it real!$"

gText_ApprenticeWhichMonFirst8::
	.string "Rah! {PLAYER}!\n"
	.string "I’m bare gassed to see you again!\p"
	.string "My POKéMON have been putting in\n"
	.string "serious work lately!\p"
	.string "But I’m still taking Ls. It’s all\n"
	.string "about who starts the scrap, innit?\p"
	.string "{PLAYER}, please, I need the blueprint!\p"
	.string "Make the call—which of my squad\n"
	.string "should go out first?$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… I’m absolutely gassed…\p"
	.string "It’s like a dream having you pick\n"
	.string "the lead for me, {PLAYER}.\p"
	.string "But say no more! I hear that!\n"
	.string "I’m sending {STR_VAR_1} in first!\p"
	.string "I hope you’ll drop more gems for\n"
	.string "me another time, yeah?$"

gText_ApprenticeWhichMonFirst9::
	.string "Yo, yo!\n"
	.string "My mentor, {PLAYER}!\l"
	.string "Drop some sage gems on me today!\p"
	.string "Check it, I’ve got a team of\n"
	.string "three POKéMON. All's calm so far.\p"
	.string "But the battling order is\n"
	.string "all over the shop.\p"
	.string "This is your moment, {PLAYER}!\n"
	.string "Decide which POKéMON is the lead!\p"
	.string "Don't be shy, man.\n"
	.string "Spit it out!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, my {STR_VAR_1} is the lead!\n"
	.string "Safe, bare safe!\l"
	.string "I’ll fix the lineup now, like, boom!\p"
	.string "Safe for the help, as always!\n"
	.string "In a bit!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}, listen!\n"
	.string "It’s a madness!\p"
	.string "My POKéMON, all three of them, just\n"
	.string "rushed the field at once!\p"
	.string "Sike! Imagine that though!\n"
	.string "Wahahaha!\p"
	.string "Real talk though—\n"
	.string "I’m proper dead at sorting out\l"
	.string "the order for my team.\p"
	.string "So, make the call—which POKéMON\n"
	.string "should lead the line, master?$"

gText_ApprenticeMonFirstThanks10::
	.string "Safe, so you chose my {STR_VAR_1}?\n"
	.string "I’ll let any but that one go first!\p"
	.string "Gotcha! Joking again!\n"
	.string "I’ll obey your word, master!\p"
	.string "Safe, master!\n"
	.string "Keep the gems coming!$"

gText_ApprenticeWhichMonFirst11::
	.string "Yo! Yo! Yo!\n"
	.string "Check the flow, here I go!\p"
	.string "The sickest sailor on the mic!\n"
	.string "Got a question you might like!\p"
	.string "It’s a team lineup question\n"
	.string "that needs your suggestion!\p"
	.string "Out of this lot, who’s the lead\n"
	.string "to give me the wins I need?$"

gText_ApprenticeMonFirstThanks11::
	.string "Safe, I hear you, loud and clear!\n"
	.string "I’ll switch them up, have no fear!\p"
	.string "If I need a link for a strategy,\n"
	.string "{PLAYER}, I’ll holla at you, G!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yo, {PLAYER}!\n"
	.string "Wagwan with you?\p"
	.string "What’s the move? Should I ask?\n"
	.string "Yeah, I’ve got a task!\l"
	.string "You feeling me?\l"
	.string "I know you’re feeling me!\p"
	.string "You gotta decide, which of my\n"
	.string "squad is the first to ride!\l"
	.string "Into the scrap, I mean to say.$"

gText_ApprenticeMonFirstThanks12::
	.string "My {STR_VAR_1}? Sick!\n"
	.string "That’ll do, it’s a vibe!\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me.\p"
	.string "Catch you later, my smart friend!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof… ouch… {PLAYER}…\n"
	.string "My stomach’s killing me all of a sudden…\p"
	.string "…Proper peak… I’m alright now…\p"
	.string "I must’ve stressed myself out\n"
	.string "racking my brains on how to line\l"
	.string "up my squad.\p"
	.string "Since I’m struggling,\n"
	.string "I need you to make the call.\p"
	.string "{PLAYER}, which of my POKéMON should\n"
	.string "lead? So I don’t take an L, I mean.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, safe.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I’ll fix the lineup after I’ve\n"
	.string "grabbed a cheeky Nando’s.\p"
	.string "I’ll keep hollering at you for help\n"
	.string "like this, yeah?$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "{PLAYER}…?\p"
	.string "Please, don’t look at me like that.\n"
	.string "You’re making me bare shook.\p"
	.string "Um…\n"
	.string "I really need your gems.\p"
	.string "It’s a bit bait to say this,\n"
	.string "but I’ve picked my team of 3.\l"
	.string "I can’t decide on the order, though.\p"
	.string "Who should lead the line so\n"
	.string "I actually look like I know the roads?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Safe!\n"
	.string "I’ll lead with my {STR_VAR_1}.\p"
	.string "Hopefully I can put in work without\n"
	.string "getting bare rattled.\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "If we link up again, don't be\l"
	.string "a stranger.$"

gText_ApprenticeWhichMonFirst15::
	.string "Wait... you look like {PLAYER}…\n"
	.string "But are you actually legit?\l"
	.string "Maybe you’re just a lookalike?\p"
	.string "Nah, nah, don’t stress!\n"
	.string "If you’re the real {PLAYER}, just\l"
	.string "ignore me being cheeky.\p"
	.string "What I need is your top-tier gems.\p"
	.string "I’ve got my team here.\n"
	.string "I need you to tell me which one\l"
	.string "should lead the line in a scrap.$"

gText_ApprenticeMonFirstThanks15::
	.string "My {STR_VAR_1}…\n"
	.string "You’re not trolling me, are you?\p"
	.string "I hear you. If that's the word, calm.\n"
	.string "Love for the time, man.\p"
	.string "I’m just a humble guy, but I’ll\n"
	.string "give it a proper go.\p"
	.string "Catch you later!$"

gText_ApprenticeWhichMon0::
	.string "Rah… {PLAYER}!\n"
	.string "You’ve come at the perfect time!\p"
	.string "I’m in a proper pickle, man…\n"
	.string "I can't decide which POKéMON to use.\p"
	.string "I’m stuck between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which one do you reckon gives\n"
	.string "a guy like me a chance at a win?$"

gText_ApprenticeMonThanks0::
	.string "Safe… I… I hear that!\n"
	.string "My bad, man!\l"
	.string "I’m just bare gassed, I’m tearing up…\p"
	.string "I’ll go all out to catch a\n"
	.string "{STR_VAR_1}!\p"
	.string "Love for that, seriously!$"

gText_ApprenticeWhichMon1::
	.string "Get in! It’s {PLAYER}!\n"
	.string "Perfect timing, man!\l"
	.string "I need you to drop some gems again!\p"
	.string "Listen, I’m all mixed up—should I go\n"
	.string "with {STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which one should I be training up,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, so {STR_VAR_1} is the one!\n"
	.string "Safe, I’m on it!\p"
	.string "Safe for the gems!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, wagwan!\n"
	.string "I’ve got a query for you.\p"
	.string "I’m in a dilemma over whether I should\n"
	.string "train up {STR_VAR_1} or {STR_VAR_2}.\p"
	.string "Which POKéMON do you reckon is\n"
	.string "actually top-tier?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} is the move?\n"
	.string "Safe, I hear that!\p"
	.string "I’ll go catch a strong {STR_VAR_1}\n"
	.string "straight away!\p"
	.string "In a bit!$"

gText_ApprenticeWhichMon3::
	.string "Yo, {PLAYER}…\p"
	.string "You’ve probably forgotten about a\n"
	.string "younger like me already…\p"
	.string "…But it’s calm if you could just\n"
	.string "give me a bit of advice…\p"
	.string "I can't decide what POKéMON to raise…\p"
	.string "I’ve narrowed it down to {STR_VAR_1}\n"
	.string "and {STR_VAR_2}, but I’m bare stuck…\p"
	.string "{PLAYER}, I know it’s a long ask,\n"
	.string "but please make the call for me.$"

gText_ApprenticeMonThanks3::
	.string "But will a wild {STR_VAR_1} even rate\n"
	.string "a guy like me?\p"
	.string "I’ll give it a go!\p"
	.string "What if I can't even catch it though…\n"
	.string "Nah! I’ve gotta put in work!\p"
	.string "Safe!$"

gText_ApprenticeWhichMon4::
	.string "Yo, {PLAYER}! Gassed to see you!\n"
	.string "I was just about to look for you!\p"
	.string "Can you make the call on what POKéMON\n"
	.string "I should be using?\p"
	.string "For example…\n"
	.string "How about {STR_VAR_1}\l"
	.string "and {STR_VAR_2}?\p"
	.string "Which one do you reckon is\n"
	.string "the better look?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? That’s sick!\p"
	.string "Since you made the call, {PLAYER},\n"
	.string "I won’t be bare vexed if I take\l"
	.string "an L.\p"
	.string "Safe, I’ll holla at you again soon.\n"
	.string "In a bit!$"

gText_ApprenticeWhichMon5::
	.string "If it isn't {PLAYER}! Wagwan?\n"
	.string "I’m bare busy as usual!\p"
	.string "I wanna do big things with POKéMON,\n"
	.string "but I haven't been able to decide\l"
	.string "which one to actually use.\p"
	.string "{STR_VAR_1} looks proper tough, yeah?\n"
	.string "But {STR_VAR_2} is hard to ignore.\p"
	.string "{PLAYER}, give me the lowdown!\n"
	.string "Which one is the move for me?$"

gText_ApprenticeMonThanks5::
	.string "Safe, gotcha.\n"
	.string "I’ll find a gap in the schedule and\l"
	.string "grab that {STR_VAR_1} you mentioned.\p"
	.string "Glad I got a proper mentor like you.\n"
	.string "Safe! Catch you later!$"

gText_ApprenticeWhichMon6::
	.string "Oi!\n"
	.string "Get in, it’s {PLAYER}!\p"
	.string "I’ve been bare bragging to all the\n"
	.string "mandem about meeting you!\p"
	.string "Need to pick your brain again today.\n"
	.string "It’s a light one for you, though!\p"
	.string "Drum roll, please!\n"
	.string "The question I’ve got is…\p"
	.string "If I was to raise a POKéMON,\n"
	.string "and it’s between {STR_VAR_1}\l"
	.string "or {STR_VAR_2}, which one’s the move?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, yeah? Sick!\l"
	.string "Safe for a proper sick answer!\p"
	.string "I reckon that’s all I needed to\n"
	.string "bother you with today.\p"
	.string "Catch you in the manor later, yeah?\n"
	.string "Safe!$"

gText_ApprenticeWhichMon7::
	.string "Yo, is that you, {PLAYER}?\n"
	.string "Proper gassed to see you again!\p"
	.string "Ever since I started learning from\n"
	.string "you, my confidence has been peak.\p"
	.string "I reckon I’m ready to raise a proper\n"
	.string "POKéMON of my own now!\p"
	.string "{PLAYER}, can I bother you to pick\n"
	.string "which POKéMON I should train?\p"
	.string "It’s between the POKéMON\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\l"
	.string "Which one’s the right vibe for me?$"

gText_ApprenticeMonThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I’ll track one down right now!\p"
	.string "Love for that, {PLAYER}.\n"
	.string "I’ll holla at you again soon.\l"
	.string "Keep it real!$"

gText_ApprenticeWhichMon8::
	.string "Rah! {PLAYER}! Linked you again!\n"
	.string "I’m… I’m bare gassed!\p"
	.string "Oi, I know!\n"
	.string "I can’t let this opportunity slide!\p"
	.string "Can I ask a huge favor, {PLAYER}?\n"
	.string "Please pick a POKéMON for me!\p"
	.string "Make the call—which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks8::
	.string "Wow! You actually made the call!\n"
	.string "I’ll raise a {STR_VAR_1} to be a\l"
	.string "proper beast, trust me.\p"
	.string "I hope you’ll drop more gems for\n"
	.string "me another time, yeah?$"

gText_ApprenticeWhichMon9::
	.string "Yo, yo!\n"
	.string "My mentor, {PLAYER}!\p"
	.string "Safe, I’ve been looking for you\n"
	.string "to get some more sage gems!\p"
	.string "What POKéMON is the move for me,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?\p"
	.string "Don't be shy, man.\n"
	.string "Spit it out!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Safe, bare safe!\l"
	.string "I’ll get one in a BALL, like, boom!\p"
	.string "Safe for that, as always!\n"
	.string "In a bit!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}, listen! Big news!\n"
	.string "I just bagged a legendary POKéMON!\p"
	.string "Sike! Imagine that though!\n"
	.string "Wahahaha!\p"
	.string "Real talk, though—\n"
	.string "I’m proper dead at actually\l"
	.string "catching POKéMON.\p"
	.string "So, how about deciding which one\n"
	.string "I should go for, master?\p"
	.string "Which one’s the move?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Safe, so {STR_VAR_1} is the one?\n"
	.string "I’ll go catch the other one then!\p"
	.string "Gotcha! Joking again!\n"
	.string "I’ll obey your word, master!\p"
	.string "Safe, master!\n"
	.string "Keep the gems coming!$"

gText_ApprenticeWhichMon11::
	.string "Yo! Yo! Yo!\n"
	.string "Check the flow, here I go!\p"
	.string "The sickest sailor on the mic!\n"
	.string "Surely you know what I’m like?\p"
	.string "Today, I’ve got a POKéMON query\n"
	.string "that needs a legendary theory!\p"
	.string "I’ve gotta pick between {STR_VAR_1}\n"
	.string "and {STR_VAR_2}, you see.\l"
	.string "Which one should be joining me?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, you say? Safe, safe!\n"
	.string "I’ll track one down for the base!\p"
	.string "If I need a link for a strategy,\n"
	.string "{PLAYER}, I’ll holla at you, G!$"

gText_ApprenticeWhichMon12::
	.string "Rah, check it, it’s {PLAYER}!\p"
	.string "What’s the move? Should I ask?\n"
	.string "Yeah, I’ve got a task!\l"
	.string "You feeling me?\l"
	.string "I know you’re feeling me!\p"
	.string "My POKéMON—who should I use?\n"
	.string "It’s {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which one do you choose?$"

gText_ApprenticeMonThanks12::
	.string "If {STR_VAR_1} is the sickest choice,\n"
	.string "I’ll follow your legendary voice!\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me.\p"
	.string "Catch you later, my smart friend!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hi, {PLAYER}…\n"
	.string "I’ve got a proper splitting headache…\p"
	.string "Must’ve stressed myself out tryna\n"
	.string "pick which POKéMON to train up.\p"
	.string "Since I’m out of action,\n"
	.string "I need you to make the call.\p"
	.string "{PLAYER}, if it’s between {STR_VAR_1}\n"
	.string "and {STR_VAR_2}, which one’s the move?$"

gText_ApprenticeMonThanks13::
	.string "Hm, {STR_VAR_1}, safe.\n"
	.string "I’ll go track one down when I’m calm.\p"
	.string "I’ll keep hollering at you for help\n"
	.string "like this, yeah?$"

gText_ApprenticeWhichMon14::
	.string "Er… Um…\n"
	.string "{PLAYER}…?\p"
	.string "Please, don’t look at me like that.\n"
	.string "You’re making me bare rattled…\l"
	.string "I… I need your gems.\p"
	.string "I’m bare embarrassed, but I can’t\n"
	.string "decide which POKéMON to use.\p"
	.string "If it was {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Safe!\n"
	.string "I’ll do my best with {STR_VAR_1}.\p"
	.string "Hopefully I can put in work without\n"
	.string "getting bare shook.\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "If we link up again, don't be\l"
	.string "a stranger.$"

gText_ApprenticeWhichMon15::
	.string "Wait... you look like {PLAYER}…\n"
	.string "But are you actually legit?\p"
	.string "Nah, if you’re real, it’s calm.\n"
	.string "Anyway, I’m looking to grab\l"
	.string "some of your top-tier gems.\p"
	.string "It’s about which POKéMON I should use.\p"
	.string "If it’s between {STR_VAR_1}\n"
	.string "and {STR_VAR_2}, which one is more\l"
	.string "worthy of the squad?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "You’re 100% on that?\p"
	.string "I hear you. If that's the word, calm.\n"
	.string "Love for the time, man.\p"
	.string "Hopefully it’s a POKéMON I can\n"
	.string "actually handle with style.\p"
	.string "Catch you later!$"

gText_ApprenticeWhichMove0::
	.string "Rah! {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I’m in a proper state!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, help me out, {PLAYER}.\n"
	.string "Make the call for me!\p"
	.string "For my {STR_VAR_1}, which move is\n"
	.string "the one: {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Sorry, {PLAYER}! I’m just bare\n"
	.string "gassed that you picked the move.\l"
	.string "I’m actually tearing up…\p"
	.string "Snivel…\n"
	.string "Love for that, seriously!$"

gText_ApprenticeWhichMove1::
	.string "Get in! Hi, {PLAYER}!\n"
	.string "I need you to drop more gems!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a move that’s actually sick.\p"
	.string "It’s between the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}.\l"
	.string "What’s the move, mentor?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} is the one? I hear that!\n"
	.string "Safe, I’ll go with that!\p"
	.string "If we link up again, keep the\n"
	.string "knowledge coming, master!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, wagwan!\n"
	.string "It’s my {STR_VAR_1}—I’m bare\l"
	.string "stressed about its moveset.\p"
	.string "I’m looking at {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which one is more top-tier for\n"
	.string "my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} is the move?\n"
	.string "Safe, I hear that!\p"
	.string "I’ll go teach {STR_VAR_1} to\n"
	.string "my POKéMON right away!\p"
	.string "In a bit!$"

gText_ApprenticeWhichMove3::
	.string "Yo, {PLAYER}…\n"
	.string "I’m moving peak, seriously!\p"
	.string "I’ve started training this team,\n"
	.string "but now I’m stuck on which move\l"
	.string "I should let it learn…\p"
	.string "I know it’s a bit long for you to\n"
	.string "care about, {PLAYER}.\p"
	.string "But I’m bare stressed about it…\p"
	.string "Please, {PLAYER}, pick a move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "Between {STR_VAR_2} and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "I hear you!\p"
	.string "But will it even learn {STR_VAR_1}\n"
	.string "from a guy like me…\l"
	.string "Nah! I’ve gotta put in work!\p"
	.string "Safe!$"

gText_ApprenticeWhichMove4::
	.string "Yo, {PLAYER}! I was gassed\n"
	.string "hoping I’d bump into you!\p"
	.string "I was wondering what move would\n"
	.string "suit my {STR_VAR_1} the best.\p"
	.string "I can’t decide, so can you make the\n"
	.string "call for me instead?\p"
	.string "Like… how about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one’s the better look?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? That’s sick!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}, I won’t be bare vexed if\l"
	.string "I take an L.\p"
	.string "Safe, I’ll holla at you again.\n"
	.string "In a bit!$"

gText_ApprenticeWhichMove5::
	.string "Rah, how am I this busy?\n"
	.string "Yo, if it isn't {PLAYER}!\l"
	.string "Wagwan with you?\p"
	.string "Since I got up, I’ve done a 5k,\n"
	.string "some shopping, and prepped lunch!\p"
	.string "You wouldn't believe the schedule!\p"
	.string "I haven’t even had a sec to pick a\n"
	.string "move for my {STR_VAR_1}!\p"
	.string "{STR_VAR_2} looks tough, yeah?\n"
	.string "But {STR_VAR_3} is also decent.\p"
	.string "{PLAYER}, give me the lowdown!\n"
	.string "Which move is the vibe for me?$"

gText_ApprenticeMoveThanks5::
	.string "Safe, gotcha.\n"
	.string "I’ll find a gap in the diary and\l"
	.string "get that taught.\p"
	.string "Glad I got a proper mentor like you.\n"
	.string "Safe! Catch you later!$"

gText_ApprenticeWhichMove6::
	.string "Oi! Lucky!\n"
	.string "Linked you again, {PLAYER}!\l"
	.string "Need to pick your brain today.\p"
	.string "Drum roll, please!\n"
	.string "The question is…\p"
	.string "For my {STR_VAR_1}, which move is\n"
	.string "the better look: {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, yeah? Sick!\l"
	.string "Safe for a proper sick answer!\p"
	.string "I reckon that’s all I needed to\n"
	.string "bother you with today.\p"
	.string "Catch you later! Safe!$"

gText_ApprenticeWhichMove7::
	.string "Yo, hiya, {PLAYER}.\n"
	.string "Proper decent to see you again.\p"
	.string "I need to seek your advice again.\n"
	.string "It’s about my {STR_VAR_1}.\p"
	.string "What’s the ideal move for\n"
	.string "my {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I’ll get that sorted right away!\p"
	.string "Love for that, {PLAYER}.\n"
	.string "I’ll holla at you again soon.\l"
	.string "Keep it real!$"

gText_ApprenticeWhichMove8::
	.string "Rah! {PLAYER}! Linked you again!\n"
	.string "I’m… I’m bare gassed!\p"
	.string "Whenever I’m stuck, you’re always\n"
	.string "there to link me, {PLAYER}!\p"
	.string "Today, I need a move recommendation!\p"
	.string "Please pick a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move is better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Get in! Love for that!\n"
	.string "{STR_VAR_1} it is!\l"
	.string "Say no more!\p"
	.string "I hope you’ll drop more gems for\n"
	.string "me another time, yeah?$"

gText_ApprenticeWhichMove9::
	.string "Yo, {PLAYER}, wagwan!\n"
	.string "I’m hoping for some more of\l"
	.string "your sage gems today!\p"
	.string "What’s the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "I need something that’ll\n"
	.string "let me grab a win, just like that!\p"
	.string "Should it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Safe, respect!\l"
	.string "I’ll get it taught, like, boom!\p"
	.string "Safe for that, as always!\n"
	.string "In a bit!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}, it’s absolute madness!\p"
	.string "My POKéMON!\n"
	.string "It just learned six moves at once!\p"
	.string "Sike! Imagine that though!\n"
	.string "Wahahaha!\p"
	.string "Real talk though—\n"
	.string "I’m proper dead at picking moves\l"
	.string "for my squad.\p"
	.string "So, make the call—which move\n"
	.string "should I teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}—which one\n"
	.string "suits my {STR_VAR_1} the best?$"

gText_ApprenticeMoveThanks10::
	.string "Safe, so you chose {STR_VAR_1}?\n"
	.string "I’ll pick the other move, then!\p"
	.string "Gotcha! Joking again!\n"
	.string "I’ll obey your word, master!\p"
	.string "Safe, master!\n"
	.string "Keep the gems coming!$"

gText_ApprenticeWhichMove11::
	.string "Yo! Yo! Yo!\n"
	.string "Check the flow, here I go!\p"
	.string "The sickest sailor on the mic!\n"
	.string "Staying on top, that’s what I’m like.\p"
	.string "Today, I’ve got a move query\n"
	.string "that needs a legendary theory!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the ones. What’s the best for my\l"
	.string "{STR_VAR_1} so we get things done?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, you say? Safe, safe!\n"
	.string "I’ll track that down for the base!\p"
	.string "If I need a link for a strategy,\n"
	.string "{PLAYER}, I’ll holla at you, G!$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeah, if it isn't {PLAYER}!\p"
	.string "What’s the move? Should I ask?\n"
	.string "Yeah, I’ve got a task!\l"
	.string "You feeling me?\l"
	.string "I know you’re feeling me!\p"
	.string "{PLAYER}, you caught by surprise?\n"
	.string "Check the advice in my eyes!\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}—what should it use?\n"
	.string "It’s {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12::
	.string "If {STR_VAR_1} is the sickest choice,\n"
	.string "I’ll follow your legendary voice!\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me.\p"
	.string "Catch you later, my smart friend!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Rah! Oh, {PLAYER}…\n"
	.string "I’ve got a proper nasty cold, man…\p"
	.string "I wanna pick a move for my squad,\n"
	.string "but I’m moving bare slow…\p"
	.string "Since I’m struggling,\n"
	.string "I need you to make the call.\p"
	.string "{PLAYER}, if it’s {STR_VAR_2} or\n"
	.string "{STR_VAR_3} for my {STR_VAR_1},\l"
	.string "which one’s the move?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, safe. Cough!\n"
	.string "I’ll get that taught when I’m calm.\p"
	.string "I’ll keep hollering at you for help\n"
	.string "like this, yeah?$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "{PLAYER}…?\p"
	.string "Please, don’t look at me like that.\n"
	.string "You’re making me bare rattled…\l"
	.string "I… I need your gems.\p"
	.string "I’m bare embarrassed, but I can’t\n"
	.string "decide what move to teach my squad.\p"
	.string "It’s for my {STR_VAR_1}.\n"
	.string "If it was {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Safe!\n"
	.string "I’ll try that {STR_VAR_1}.\p"
	.string "Hopefully I can get it taught…\n"
	.string "This is bare nerve-racking…\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "If we link up again, don't be\l"
	.string "a stranger.$"

gText_ApprenticeWhichMove15::
	.string "Wait... you look like {PLAYER}…\n"
	.string "But are you actually legit?\p"
	.string "Maybe you’re one of those TikTok\n"
	.string "look-alikes?\p"
	.string "Nah, if you’re real, it’s calm.\n"
	.string "Don't be vexed, I’m just checking!\p"
	.string "Anyway, I’m looking to grab\l"
	.string "some of your top-tier gems.\p"
	.string "It’s about my {STR_VAR_1}.\p"
	.string "Which move is more worthy of it,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "You’re 100% on that?\p"
	.string "I hear you. If that's the word, calm.\n"
	.string "Love for the time, man.\p"
	.string "I do hope it’s a move even my\n"
	.string "POKéMON can actually pull off.\p"
	.string "Catch you later!$"

gText_ApprenticePickWinSpeech0::
	.string "Rah… {PLAYER}?\n"
	.string "It is you!\l"
	.string "Oh! Sniff… Please, listen!\p"
	.string "I… when I battle, I get bare rattled.\n"
	.string "I can’t help crying even if I win…\p"
	.string "I wish I could drop something cool\n"
	.string "when I win a scrap…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you teach me a sick bar to say\l"
	.string "so I don’t look like a wet wipe?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Legend! Sick! Absolute madness!\n"
	.string "That is proper tough!\p"
	.string "Oh… I’m sorry…\n"
	.string "I’m just bare gassed, I’m crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Love for everything, man!\p"
	.string "I’m gonna battle my heart out for\n"
	.string "you, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… it’s a friendly scrap!$"

gText_ApprenticePickWinSpeech1::
	.string "Get in! It’s {PLAYER}! Yo!\n"
	.string "I needed to ask you something!\p"
	.string "I wanna drop a sick quote when\n"
	.string "I win a match.\p"
	.string "Do you have any top-tier lines that\n"
	.string "you’d recommend?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! That is proper sick!\n"
	.string "Safe, I’m using that!\p"
	.string "Safe for the gems all this time!\n"
	.string "I’m gonna go all out wherever\l"
	.string "I end up from now on!\p"
	.string "When we link up again, we’re battling!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, wagwan!\p"
	.string "My squad and I are ready for\n"
	.string "the roads, but there’s one thing.\p"
	.string "I reckon I need a sick shout to\n"
	.string "drop when I win.\p"
	.string "Can you think up something cold\n"
	.string "to say?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Cold!\n"
	.string "I’m definitely using that!\p"
	.string "I’m gonna be battling all over\n"
	.string "the region now.\p"
	.string "Who knows, I might even give you\n"
	.string "a run for your money, {PLAYER}.\p"
	.string "Next time, let’s link for a battle!$"

gText_ApprenticePickWinSpeech3::
	.string "Yo, {PLAYER}…\n"
	.string "Sorry to be long, but I’m peak…\p"
	.string "Even when…\n"
	.string "Even when I win, I’ve got nothing\l"
	.string "decent to say…\p"
	.string "I know it’s whatever to a champ\n"
	.string "like you, {PLAYER}.\p"
	.string "But it’s a big deal to me…\p"
	.string "Please, {PLAYER}, what should I say\n"
	.string "if I actually bag a win?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "That’s inspired, man…\p"
	.string "Uh… is it even right for a younger\n"
	.string "like me to be saying that?\p"
	.string "Nah! I’ve gotta back it!\p"
	.string "{PLAYER}, love for putting up with\n"
	.string "me for so long, honestly…\p"
	.string "I promise to put in work from now on.\p"
	.string "You’ll probably forget a guy like me\n"
	.string "bare fast, but let’s link again!$"

gText_ApprenticePickWinSpeech4::
	.string "Yo, {PLAYER}.\n"
	.string "I need a quick word with you.\p"
	.string "I know I don’t always sound like\n"
	.string "the most polite guy…\p"
	.string "When I win, I think I sound a bit\n"
	.string "too gassed or arrogant.\p"
	.string "I don’t want people to think I’m a\n"
	.string "dick, so I want something decent to\l"
	.string "say to someone I’ve beaten.\p"
	.string "But I’m stuck! Can you help me out?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yeah, that’s the one!\p"
	.string "I’m hitting the road now to use\n"
	.string "everything you’ve taught me.\p"
	.string "Sorry for being so pushy with you\n"
	.string "this whole time!\p"
	.string "Next time, we’re scrapping, yeah?\n"
	.string "In a bit!$"

gText_ApprenticePickWinSpeech5::
	.string "Rah, I’m actually so busy, it’s peak!\n"
	.string "Oh, yo, I was tryna find you, {PLAYER}.\p"
	.string "You good? Everything’s still a\n"
	.string "madness for me.\p"
	.string "I’ve got cardio, battling, and training\n"
	.string "to do. Why is the schedule like this?\p"
	.string "But even if I’m busy, it’s rude to\n"
	.string "just dip after a win without saying\l"
	.string "a single word.\p"
	.string "So, what’s a sick line to show off\n"
	.string "my style before I bounce? Help me!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Safe, gotcha.\n"
	.string "I can find a sec to say that!\p"
	.string "Honestly, I’m glad I had a proper\n"
	.string "mentor like you.\p"
	.string "I’m gonna make time somehow to\n"
	.string "really get into these battles.\p"
	.string "Love for everything, {PLAYER}!\n"
	.string "We’ve gotta scrap one day, trust me!$"

gText_ApprenticePickWinSpeech6::
	.string "Oi! My luck is in again!\n"
	.string "{PLAYER}! Proper gassed to see you!\l"
	.string "As per, I need your gems!\p"
	.string "Drum roll, please!\n"
	.string "The final question is…\p"
	.string "If I win a scrap and want to end\n"
	.string "it with a proper flourish, what\l"
	.string "should I drop?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "That… that is actually sick!\n"
	.string "It’s got style and vibe! It’s mine!\p"
	.string "…Listen, I think I’m getting proper\n"
	.string "decent at this, yeah?\p"
	.string "So, I’m thinking of taking on other\n"
	.string "TRAINERS from now on.\p"
	.string "{PLAYER}, your gems really helped me.\p"
	.string "Maybe one day, we’ll actually link\n"
	.string "for a battle!\p"
	.string "Safe for everything!$"

gText_ApprenticePickWinSpeech7::
	.string "Yo, {PLAYER}.\n"
	.string "I’m so glad I linked you today!\p"
	.string "I’ve got zero concerns left when\n"
	.string "it comes to my squad.\p"
	.string "It’s my own style that worries me…\p"
	.string "You know how a TRAINER drops\n"
	.string "a bar after winning a battle?\p"
	.string "I definitely want to do that,\n"
	.string "too!\p"
	.string "Please, what should I say when\n"
	.string "I bag a win?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! That line! It’s actually fresh!\n"
	.string "I feel like a new man!\p"
	.string "I’ve gotta use that right away!\p"
	.string "And now, I’ve gotta bounce,\n"
	.string "{PLAYER}…\p"
	.string "I’m gonna go scrap many others,\n"
	.string "but I won’t forget your gems.\p"
	.string "Maybe one day…\n"
	.string "In a bit!$"

gText_ApprenticePickWinSpeech8::
	.string "Rah! I spotted {PLAYER}!\n"
	.string "I’m… I’m bare gassed to see you!\p"
	.string "Oi! There’s something I just\n"
	.string "had to ask you!\p"
	.string "A bit ago, I won a battle.\n"
	.string "The hype was absolute madness!\p"
	.string "But I was so gassed that I just\n"
	.string "choked up and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, I need you to\n"
	.string "think up an exit line for a win!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I’m really gonna say that?!\l"
	.string "I’m delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I’ve got zero regrets now!\p"
	.string "I’m gonna travel now and scrap\n"
	.string "all sorts of people.\p"
	.string "Everything, I owe it to you, {PLAYER}.\n"
	.string "Really, truly, safe for that!\p"
	.string "I’ve gotta go now, but let’s link\n"
	.string "in a battle one day!$"

gText_ApprenticePickWinSpeech9::
	.string "Yo, {PLAYER}, wagwan!\p"
	.string "You know, I’m getting the itch to roam\n"
	.string "and scrap wherever I may.\p"
	.string "But before I do, I need your gems\n"
	.string "one last time, please!\p"
	.string "If I win a battle, what’s a proper\n"
	.string "boast I can drop to my opponent?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, that’s sweet!\n"
	.string "Safe, respect!\l"
	.string "I’ll try saying that, like, boom!\p"
	.string "And now, it’s time to say goodbye!\n"
	.string "Safe for all the help, man!\p"
	.string "Give me a battle one day, yeah?\n"
	.string "In a bit!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}, there’s big trouble!\p"
	.string "When I win a battle, I brag about it\n"
	.string "for at least a whole hour!\p"
	.string "Sike! Imagine that though!\n"
	.string "Wahahaha!\p"
	.string "Real talk, though—\n"
	.string "I’m proper dead at the small talk.\p"
	.string "So, how about picking a line for\n"
	.string "me to drop after winning, master?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "That’s what I should say, huh?\n"
	.string "Then I’ll stay well away from that!\p"
	.string "Gotcha! Joking again!\n"
	.string "I’ll obey your word, master!\p"
	.string "Safe for the gems all this time,\n"
	.string "master!\p"
	.string "I’m finally seeing what being a\n"
	.string "proper TRAINER is all about.\p"
	.string "I’m gonna go out and bag wins\n"
	.string "against any TRAINER I link.\p"
	.string "Might even be you one day, master!\p"
	.string "That’s all!\n"
	.string "Safe, my master!$"

gText_ApprenticePickWinSpeech11::
	.string "Yo! Yo! Yo!\n"
	.string "Check the flow, here I go!\p"
	.string "The sickest sailor on the mic!\n"
	.string "This is my last task, alright?\p"
	.string "It’s a saying query\n"
	.string "for my winning theory!\p"
	.string "If I bag a win, what can I say\n"
	.string "in a proper sick way?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfect! That’s what I’ll use.\n"
	.string "I was right to let you choose!\p"
	.string "And now, I think it’d be best,\n"
	.string "if I were to fly the nest!\p"
	.string "Safe for everything you taught.\n"
	.string "In a battle, I won't be caught!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "Bon voyage, that’s me!\l"
	.string "Respect for making me a G!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, yeah, {PLAYER}!\n"
	.string "Linked you again today!\p"
	.string "What’s the move? Ask you again?\n"
	.string "Why not? I’m already asking you!\p"
	.string "Anyway, {PLAYER}…\n"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\l"
	.string "I need one last gem for me!\p"
	.string "It’s about what I should yell.\n"
	.string "Something sick to holler when\l"
	.string "a battle ends well.\p"
	.string "Come on, I wanna hear you drop it!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I’ll use that because it’s so tight!\p"
	.string "I’m out of things to ask you now.\n"
	.string "Waving bye is the final bow.\p"
	.string "But maybe we’ll meet on the road,\n"
	.string "with someone about to get rolled.\p"
	.string "But it really is time to bounce.\p"
	.string "Right, {PLAYER}, I’m off to roam free,\n"
	.string "but don’t you go forgetting me!\p"
	.string "Take care, {PLAYER}!\n"
	.string "Love ya!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}, it’s over…\n"
	.string "My nose won't stop running…\p"
	.string "I was tryna think up something\n"
	.string "sick to say when I bag a win.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose is moving peak…\p"
	.string "Since things are this way,\n"
	.string "I need you to make the call, {PLAYER}.\p"
	.string "When I win a scrap,\n"
	.string "what should I say?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …That’s cold.\n"
	.string "Nah, it’s actually legendary!\l"
	.string "It’s bringing fresh tears to my eyes!\p"
	.string "In spite of the tears and the peak\n"
	.string "nose, I’m using that line!\p"
	.string "I’m officially out of things to ask,\n"
	.string "{PLAYER}.\p"
	.string "From now on, we’re rivals!\n"
	.string "Safe for everything!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Um…\n"
	.string "{PLAYER}…\p"
	.string "Please, don’t look at me like that.\n"
	.string "You’re making me bare nervous.\p"
	.string "I… I need your gems again.\n"
	.string "I’ll make it the last one, though…\p"
	.string "It’s bare embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Safe!\n"
	.string "I’ll try to say that!\l"
	.string "I might be too rattled to say it…\p"
	.string "Safe for that, {PLAYER}.\n"
	.string "I have to say goodbye now.\p"
	.string "I’ll follow everything you taught,\n"
	.string "{PLAYER}, and put in serious work.$"

gText_ApprenticePickWinSpeech15::
	.string "Wait... you look like {PLAYER}…\n"
	.string "But are you actually legit?\l"
	.string "Maybe a clever {PLAYER} PLUSHIE?\p"
	.string "Nah, nah, don’t stress!\n"
	.string "If you’re real, it’s calm.\l"
	.string "Forget I was being cheeky.\p"
	.string "Don't be so vexed. I just want\n"
	.string "one last bit of your top-tier gems.\p"
	.string "It’s about a victory line.\p"
	.string "What should I say\n"
	.string "if I bag a win?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you actually serious?\p"
	.string "I hear you. If you’re serious, calm.\n"
	.string "Love for the time, man.\p"
	.string "Hopefully even I can put that\n"
	.string "saying to proper use.\p"
	.string "I seem to have run dry on advice.\p"
	.string "I reckon it’s high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Safe, my mentor!\n"
	.string "My bad for being so skeptical!$"

