FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Yo, welcome to the BATTLE TENT\n"
	.string "FALLARBOR SITE!\p"
	.string "I’m your guide for the Set KO Tourney!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "So, you ready to step up and take the\n"
	.string "Set KO challenge?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Calm. We’ll be here when you’re\n"
	.string "actually ready for the smoke!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Here in the FALLARBOR BATTLE TENT,\n"
	.string "it’s all about the Set KO Tourney.\p"
	.string "You’re entering with a squad of\n"
	.string "three POKéMON.\p"
	.string "Order matters—line them up exactly\n"
	.string "how you want them to come out.\p"
	.string "In battle, they’ll drop in one by one\n"
	.string "based on that preset order.\p"
	.string "Once a POKéMON hits the field, they’re\n"
	.string "locked in until the round is over.\p"
	.string "If no one’s dropped after three turns,\n"
	.string "the judges make the final call.\p"
	.string "If you need to dip for a bit, make\n"
	.string "sure you save your progress.\p"
	.string "If you don’t save, consider your\n"
	.string "challenge dead in the water.\p"
	.string "If you manage to roll three TRAINERS\n"
	.string "back-to-back, we’ve got a sick prize\l"
	.string "waiting for you.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Before I send you in, I’ve gotta\n"
	.string "save your data. That cool?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Two ways to play: Level 50 or\n"
	.string "Open Level. What’s the move?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Safe. Go ahead and pick your\n"
	.string "top three POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Hold up, challenger!\p"
	.string "You haven’t got the three POKéMON\n"
	.string "needed to enter this bracket.\p"
	.string "Also, no duplicate items allowed—\n"
	.string "keep it original.\p"
	.string "EGGS{STR_VAR_1} obviously a no-go.\p"
	.string "Get your squad sorted and\n"
	.string "link us again.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Hold up, challenger!\p"
	.string "You haven’t got the three POKéMON\n"
	.string "needed to enter this bracket.\p"
	.string "You need three different species,\n"
	.string "and no duplicate items either.\p"
	.string "EGGS{STR_VAR_1} obviously a no-go.\p"
	.string "Get your squad sorted and\n"
	.string "link us again.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Right, follow me to the arena.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Wait, what happened?\p"
	.string "You didn’t save before you cut the\n"
	.string "power, did you?\p"
	.string "That’s a major foul. You’ve been\n"
	.string "disqualified from the run.\p"
	.string "You’ll have to start a fresh\n"
	.string "challenge if you want that prize.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Madness! You actually rolled all\n"
	.string "three TRAINERS in a row!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Give me a sec while I save the game.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "To celebrate that 3-win streak,\n"
	.string "here’s your reward.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Wait, your BAG is stuffed.\p"
	.string "Go clear some space and come back\n"
	.string "to claim your loot.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Love for taking part!\p"
	.string "Hold tight while I save the game.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "We’ll be waiting for your next run!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "We’ve been waiting for you to\n"
	.string "show up.\p"
	.string "Before we head in, I’ve gotta save\n"
	.string "the progress. Hold tight.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT\n"
	.string "VERDANTURF SITE!\p"
	.string "This is where we test if you actually\n"
	.string "trust your squad or not.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "You down for the VERDANTURF\n"
	.string "BATTLE TENT challenge?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "At the VERDANTURF BATTLE TENT,\n"
	.string "there’s one main rule you gotta follow.\p"
	.string "You’re only allowed to swap your\n"
	.string "POKéMON in and out.\p"
	.string "Other than that, you can't give 'em\n"
	.string "any orders. None.\p"
	.string "The POKéMON will move based on their\n"
	.string "own nature and instincts.\p"
	.string "You just gotta trust 'em and watch\n"
	.string "the magic happen.\p"
	.string "Bag three wins in a row, and we’ll\n"
	.string "drop a prize for you.\p"
	.string "If you need to take a break, make\n"
	.string "sure you save the game.\p"
	.string "No save means automatic DQ.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Come back once you and your squad\n"
	.string "are actually in sync.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Level 50 or Open Level?\n"
	.string "Choose your struggle.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Sigh…\p"
	.string "You haven’t got the three POKéMON\n"
	.string "needed for this run.\p"
	.string "You need three unique species, and\n"
	.string "no holding the same items.\p"
	.string "EGGS{STR_VAR_1} don't count.\p"
	.string "Link us again when you’re actually\n"
	.string "prepared.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Sigh…\p"
	.string "You haven’t got the three POKéMON\n"
	.string "needed for this run.\p"
	.string "You need three unique species, and\n"
	.string "no holding the same items.\p"
	.string "EGGS{STR_VAR_1} don't count.\p"
	.string "Link us again when you’re actually\n"
	.string "prepared.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Safe. Now, pick the three POKéMON\n"
	.string "you’re putting your faith in.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "I’ve gotta save before we head into\n"
	.string " the BATTLE TENT. Safe?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Calm. Follow me.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Proper respect—seeing your squad\n"
	.string "move on their own was legendary.\p"
	.string "Hold tight while I record the stats.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "A 3-win streak… mad.\p"
	.string "The bond you’ve got with your squad\n"
	.string "is clearly the real deal.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "I’m recording that run now.\n"
	.string "Just wait a sec.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "For bagging that 3-win streak,\n"
	.string "take this prize.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I’m here to run you through the\n"
	.string "Battle Swap Tournament.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "You ready to try your luck with\n"
	.string "the Battle Swap challenge?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Here at the SLATEPORT BATTLE TENT,\n"
	.string "it’s all about the Swap—using\l"
	.string "rental POKéMON.\p"
	.string "First, we loan you three POKéMON\n"
	.string "picked just for this event.\p"
	.string "You take those rentals into a\n"
	.string "SINGLE BATTLE and try to scrap.\p"
	.string "If you win, you get to trade one of\n"
	.string "your rentals for one of theirs.\p"
	.string "Keep battling and trading—if you\n"
	.string "hit three wins in a row, you get paid.\p"
	.string "If you need to bail, save the game.\p"
	.string "No save means you’re DQ’d.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Safe. See you for the next run.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which bracket you hitting?\n"
	.string "Level 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Before we start the swap, I’ve\n"
	.string "gotta save the data. Safe?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Calm, I’ll keep your squad safe\n"
	.string "while you use the rentals.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Follow me this way, please.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Love for taking part!\p"
	.string "I’ll take the rentals back and\n"
	.string "give you your real squad now.\p"
	.string "Gotta save the results, too.\n"
	.string "Hold tight.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Trading back—here’s your team,\n"
	.string "I’ll take the rentals.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Get in! Three wins straight!\p"
	.string "I’ll swap your squad back for the\n"
	.string "rentals now.\p"
	.string "Hold tight while I save the stats.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "In honor of that 3-win streak,\n"
	.string "here’s your prize.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Wait, your BAG is full up.\p"
	.string "Go clear some space and holla at\n"
	.string "me so I can give you this prize.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "We’ve been waiting for you!\p"
	.string "Before we jump back in, I’ve gotta\n"
	.string "save the game.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Sorry to break it to you, but you didn’t\n"
	.string "save before you dipped last time.\p"
	.string "Because of that, you’ve been DQ’d\n"
	.string "from the challenge.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We’ll give you your real squad back now.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize:\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are posted.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which part do you want to check?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "In a Battle Swap event, you’re locked\n"
	.string "into using just three POKéMON.\p"
	.string "Whether you’re renting or swapping,\n"
	.string "your squad can’t have any duplicates.\n"
	.string "Keep the variety up!$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "You can only swap POKéMON with the\n"
	.string "TRAINER you just rolled.\p"
	.string "And you only get to pick from the\n"
	.string "exact POKéMON they used in the scrap.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "After every win, you get the chance\n"
	.string "to swap for one of their POKéMON.\p"
	.string "Just a heads up: you can’t swap after\n"
	.string "beating the third TRAINER.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Two major things to keep in mind\n"
	.string "when you’re swapping POKéMON.\p"
	.string "First, it’s a blind trade—you can’t\n"
	.string "check the stats of what you’re getting.\p"
	.string "Second, the order of your squad stays\n"
	.string "fixed based on when you rented 'em.\p"
	.string "Swapping won’t change your lineup\n"
	.string "position, so plan ahead!$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Every POKéMON in the SLATEPORT\n"
	.string "BATTLE TENT is a rental.\p"
	.string "All the rentals are leveled to\n"
	.string "exactly Level 30 for fairness.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are posted.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which section are you reading?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "the POKéMON have to use their heads\l"
	.string "and battle on their own.\p"
	.string "Unlike wild ones, POKéMON living with\n"
	.string "people develop their own vibes—or\l"
	.string "Natures—that dictate how they scrap.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its Nature, a POKéMON\n"
	.string "might just want to attack, period.\p"
	.string "Another might be more about playing\n"
	.string "safe and protecting itself.\p"
	.string "Some even enjoy just being a nuisance\n"
	.string "and messing with the opponent's head.\p"
	.string "A POKéMON’s Nature tells you which\n"
	.string "moves it’s actually gassed to use.\p"
	.string "If they hate a move, they’re gonna\n"
	.string "struggle to pull it off in a pinch.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Offensive moves are for dealing\n"
	.string "straight damage to the foe.\p"
	.string "Defensive moves are for prepping\n"
	.string "against hits or healing up HP.\p"
	.string "Then there’s the 'Tactical' moves—the\n"
	.string "ones that inflict status like poison\l"
	.string "or paralysis to nerf the enemy.\p"
	.string "Your POKéMON will weigh up moves in\n"
	.string "these three categories on their own.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When you aren't calling the shots,\n"
	.string "a POKéMON might flop on certain moves.\p"
	.string "They won't be any good at moves that\n"
	.string "don't fit their personal style.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "clash with its Nature, it's never\l"
	.string "gonna reach its full potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "When things get peak and they're in\n"
	.string "trouble, some POKéMON might actually\l"
	.string "switch up their style.\p"
	.string "If your POKéMON starts acting moves\n"
	.string "weirdly in a pinch, watch 'em closely.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "In this BATTLE TENT, we scale the\n"
	.string "opponents to match your own squad.\p"
	.string "But don't think it'll be easy—no one\n"
	.string "here is dropping below Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are posted.$"

