PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "DAD: Yo, {PLAYER}!\p"
	.string "I just got my hands on a bare rare\n"
	.string "BERRY. I want you to have it, kid.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "If you see BERRIES growing in loamy\n"
	.string "soil, feel free to bag 'em.\p"
	.string "But you’ve gotta plant a BERRY back\n"
	.string "in the same spot. It’s common courtesy.\p"
	.string "Here, take this one for the road.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "By the look of you, you’re definitely\n"
	.string "a TRAINER, yeah?\p"
	.string "Most TRAINERS make their POKéMON\n"
	.string "hold BERRIES for a tactical edge.\p"
	.string "It’s up to you whether you want to\n"
	.string "farm 'em or use 'em in a scrap.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "I watered these every single day.\n"
	.string "The flowers are moving mad now!\p"
	.string "And I got bare BERRIES from it, too.\p"
	.string "Here you go!\n"
	.string "Take one, it’s calm!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "I’m gonna put in work and try to grow\n"
	.string "BERRIES in all different colors.\p"
	.string "I hope you’re grinding hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "I wonder what color BERRIES are\n"
	.string "gonna be the vibe today?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "I’m addicted to the BERRY CRUSH\n"
	.string "machine, so I’m out here collecting.\p"
	.string "I’ll share one with you, if you want.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "You should link up with your mates\n"
	.string "and try the BERRY CRUSH machine.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Which BERRY is the best to plant?\n"
	.string "Should you hoard 'em or spend 'em?\p"
	.string "It’s actually a proper head-scratcher.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES grow by soaking up the rays.\p"
	.string "We help 'em out by keeping 'em\n"
	.string "hydrated on the regular.\p"
	.string "It’s all about the love, isn’t it?$"

Route120_Text_YesYouUnderstand:
	.string "Yeah, man.\n"
	.string "You get the vision.\p"
	.string "You should take this.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… but I guess you’ve gotta form\n"
	.string "your own opinions on it…\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "I reckon that BERRY is bare rare.\n"
	.string "Raising it with love is the move.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "I’ll just go grab more BERRIES from\n"
	.string "the BERRY MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "When you really think about it…\p"
	.string "The same way a sharp suit fits me,\n"
	.string "a fresh breeze fits the sea.\p"
	.string "And you? A BERRY fits your vibe\n"
	.string "perfectly…\p"
	.string "Why is that, though?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "When you really think about it…\p"
	.string "It’s 'cause you’re a TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "When you really think about it…\p"
	.string "The way simple style suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "The name's the BERRY MASTER.\p"
	.string "My dream is to fill the world with\n"
	.string "top-tier flowers, so I grow BERRIES\l"
	.string "and hand 'em out to the locals.\p"
	.string "You look like you deserve one!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Why be stingy with the goods?\n"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "You’ve gotta check out PRETTY PETAL\n"
	.string "near RUSTBORO.\p"
	.string "Let flowers take over the world!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "I’m done for the day.\n"
	.string "Link me again tomorrow.\p"
	.string "Let flowers take over the world!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "The way my husband grows BERRIES…\n"
	.string "honestly, he’s the GOAT.\p"
	.string "He makes me proper proud, he does.\p"
	.string "Anyway, kid, have you heard any\n"
	.string "sick quotes lately?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! What a legendary saying!\n"
	.string "That’s actually inspired!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! That’s a decent saying.\n"
	.string "You’re a sharp one, aren’t you?\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Our grandkids are gonna be even\n"
	.string "more elite than my husband.\p"
	.string "Life is just a constant vibe!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Yo!\p"
	.string "Welcome to PRETTY PETAL.\n"
	.string "We’re putting flowers on the map!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}, you want to learn the\n"
	.string "lowdown on BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "What’s your name?\p"
	.string "{PLAYER}.\n"
	.string "That’s a sick name.\p"
	.string "{PLAYER}, you want to learn the\n"
	.string "lowdown on BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BERRIES grow on trees that only\n"
	.string "thrive in soft, loamy soil.\p"
	.string "If you take some BERRIES, make sure\n"
	.string "you plant one back in the soil.\p"
	.string "A planted BERRY will sprout fast,\n"
	.string "grow into a plant, look legendary,\l"
	.string "then grow BERRIES all over again.\p"
	.string "I want to see the whole world\n"
	.string "filled with beautiful flowers.\l"
	.string "That’s the vision.\p"
	.string "Please help me, {PLAYER}. Plant BERRIES\n"
	.string "and make the world look better.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Flowers just bring pure happiness to\n"
	.string "everyone, don’t they?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Yo!\p"
	.string "The more love you give to flowers,\n"
	.string "the more they’ll properly bloom.\p"
	.string "You’ll love gardening, I’m sure\n"
	.string "of it. Take this.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "While the plants are growing,\n"
	.string "keep 'em hydrated with the WAILMER PAIL.\p"
	.string "Oh, one more thing.\p"
	.string "If you don’t pick 'em for a while,\n"
	.string "they’ll drop onto the ground.\l"
	.string "But they’ll just sprout again!\p"
	.string "Isn't that sick?\n"
	.string "They’ve got that survival instinct.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "I’m tryna be like my big sisters.\n"
	.string "I’m growing flowers, too!\p"
	.string "Here you go!\n"
	.string "This is for you!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "You can farm BERRIES and grow 'em big,\n"
	.string "or give 'em to a POKéMON to hold.\p"
	.string "But now there’s a machine that mixes\n"
	.string "different BERRIES into POKéMON candy.\p"
	.string "I lowkey want some candy, too.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hi, what’s your name?\p"
	.string "… … …  … … …  … … …\n"
	.string "Safe. That’s a nice name!\p"
	.string "My name is KIRI.\p"
	.string "My parents named me that so\n"
	.string "I’d grow up healthy and kind.\l"
	.string "That was the plan, anyway.\p"
	.string "You can have one of these.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI is gonna give you this BERRY, too!\n"
	.string "I actually love this one!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "I wonder what kind of wish your\n"
	.string "parents put into your name.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you’re born in the spring, do you\n"
	.string "vibe with spring? And if you’re summer\l"
	.string "born, is summer your favorite?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Well, KIRI was born in the autumn,\n"
	.string "so I’m all about the autumn!\p"
	.string "Which season do you vibe with?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "It doesn’t matter, I guess…\p"
	.string "There’s just bare things I wanna know…$"

