gText_Birch_Welcome::
	.string "Yo! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "The name's BIRCH.\p"
	.string "But everyone round here calls me\n"
	.string "the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This right here? This is what\n"
	.string "we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is packed with these\n"
	.string "creatures known as POKéMON.\p"
	.string "We live side-by-side with 'em.\n"
	.string "Sometimes we’re just chilling as\l"
	.string "mates, other times we’re grinding\l"
	.string "and working together.\p"
	.string "And yeah, sometimes we squad up\n"
	.string "to scrap with other TRAINERS.\p"
	.string "But even though we’re tight,\n"
	.string "we don’t know everything yet.\p"
	.string "In fact, POKéMON are still full\n"
	.string "of mad secrets.\p"
	.string "To figure out the mystery, I’ve\n"
	.string "been doing bare research out in\l"
	.string "the field. That’s my whole vibe.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So, what’s your story?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Safe.\n"
	.string "What’s your name?$"

gText_Birch_SoItsPlayer::
	.string "So you’re {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, I see you!\p"
	.string "You’re {PLAYER}{KUN}, the one moving to\n"
	.string "my hometown, LITTLEROOT.\l"
	.string "It all makes sense now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Alright, you ready for this?\p"
	.string "Your own legendary adventure is\n"
	.string "about to kick off.\p"
	.string "Have some heart and jump into the\n"
	.string "world of POKéMON. Dreams, hype,\l"
	.string "and a solid squad are waiting!\p"
	.string "Anyway, I’m expecting you.\n"
	.string "Link me later at the POKéMON LAB.\p"
	.string "$"

