BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BLEND MASTER: Trust me, it’s really me!\n"
	.string "The BLEND MASTER in the flesh!\p"
	.string "Jump on the machine with me and\n"
	.string "witness the levels I’m on, fam!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MASTER: Hmmm! So, you’re tryna\n"
	.string "see a real boss in action?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "So, you’re movey right now, I see!\p"
	.string "Say no more!\n"
	.string "I’m posted here all day!\l"
	.string "Do your little errand and hurry back!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "You’re empty-handed! No BERRIES?!\p"
	.string "I’m on the block all day!\n"
	.string "Go grab the goods and hurry back!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Standard!\n"
	.string "Standard!\p"
	.string "Quick question, though…\n"
	.string "You actually know how to cook up\l"
	.string "{POKEBLOCK}S from BERRIES?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Listen, the process is light!\p"
	.string "When the arrow hits your marker,\n"
	.string "just mash the A Button.\p"
	.string "Simple as that.\p"
	.string "Once you see how frame-perfect my\n"
	.string "A Button game is, you’ll get it.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Safe!\p"
	.string "Let’s get this bread, then!\p"
	.string "Squad up with the BLEND MASTER,\n"
	.string "and let’s go mad on the BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "You haven't even copped a\n"
	.string "{POKEBLOCK} CASE yet?!\p"
	.string "I’m here till late! Go find a\n"
	.string "{POKEBLOCK} CASE and link me back!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Your {POKEBLOCK} CASE is looking peak!\n"
	.string "It’s completely stuffed!\p"
	.string "I’m posted here all day! Use some\n"
	.string "{POKEBLOCK}S and then we spin it!$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa!\n"
	.string "Madness!$"

BerryBlender_Text_WickedlyFast:
	.string "Too tech!$"

BerryBlender_Text_WhatAnExpert:
	.string "Pure specialist!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "When I hopped on with the MASTER,\n"
	.string "the {POKEBLOCK}S we made were elite!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Eyes that track the arrow with\n"
	.string "robotic focus…\p"
	.string "A hand that taps the A Button\n"
	.string "with terrifying precision…\p"
	.string "The BLEND MASTER is truly built\n"
	.string "different. Total GOAT status.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "The BLEND MASTER apparently grinds\n"
	.string "his skills deep in the mountains.\p"
	.string "Sometimes, he slides to LILYCOVE\n"
	.string "just to blend BERRIES for the fans.$"

