Text_PictureBookShelf:
	.string "A stack of POKéMON picture books.\n"
	.string "Strictly for the juniors, man.\l"
	.string "I’m tryna see real gains.$"

Text_BookShelf:
	.string "Just a bunch of dead-looking books.\n"
	.string "I ain't got time for all that\l"
	.string "reading, I’m tryna be active.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…\p"
	.string "It’s all clickbait for the fans.$"

Text_Vase:
	.string "This vase looks like it’s worth a\n"
	.string "bag. I checked for the P's…\p"
	.string "But it’s empty. Bare disappointing.$"

Text_EmptyTrashCan:
	.string "Empty. Not even a snack wrapper.\n"
	.string "The bin is looking parched.$"

Text_ShopShelf:
	.string "Shelves are absolutely stacked with\n"
	.string "merch. Everything’s looking pricey.$"

Text_Blueprint:
	.string "Some kind of blueprint?\n"
	.string "The geometry is way too tech.\l"
	.string "My head’s spinning.$"

