DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "I’m the DAY-CARE MAN.\p"
	.string "I make sure everyone’s squad stays\n"
	.string "looking healthy.\p"
	.string "If you’re tryna leave a POKéMON\n"
	.string "with us, go link with my lady inside.$"

DayCare_Text_DoYouWantEgg::
	.string "Yo, it’s you!\p"
	.string "We were watching your POKéMON, and\n"
	.string "trust me, things got mad!\p"
	.string "Your POKéMON had an EGG!\p"
	.string "No idea how it happened, but\n"
	.string "your POKéMON was holding it.\p"
	.string "You want the goods, yeah?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Safe, good to see you.\n"
	.string "Your {STR_VAR_1} is chilling.$"

DayCare_Text_IllKeepIt::
	.string "Say no more, I’ll keep it.\n"
	.string "Safe!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Your pockets are full, fam…\n"
	.string "Make some space and link me back.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} copped the EGG from\n"
	.string "the DAY-CARE MAN.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Look after the little one.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "If you're tryna collect,\n"
	.string "go holla at the boss inside.$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Yo! Your {STR_VAR_1} and\n"
	.string "{STR_VAR_2} are vibing.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "I'm really gonna keep it, you know.\n"
	.string "You sure you don't want it?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "I’m the DAY-CARE LADY.\p"
	.string "We help your POKéMON level up.\p"
	.string "You tryna leave one with us?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Which one of the squad are we\n"
	.string "grinding for you?$"

DayCare_Text_WellRaiseYourMon::
	.string "Standard. We’ll look after your\n"
	.string "{STR_VAR_1} for a bit.\p"
	.string "Come back later.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "We can handle two at a time.\p"
	.string "Want us to take another one\n"
	.string "off your hands?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "My man was looking for you outside.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, safe then.\n"
	.string "Catch you later.$"

DayCare_Text_NotEnoughMoney::
	.string "You’re short on the P’s…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "You taking the other one back\n"
	.string "as well?$"

DayCare_Text_ComeAgain::
	.string "Safe.\n"
	.string "See you soon.$"

DayCare_Text_GoodToSeeYou::
	.string "Yo! Back again?\n"
	.string "Good to see you.\p"
	.string "Your POKéMON is doing bare bits!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Your {STR_VAR_1} has jumped up\n"
	.string "by {STR_VAR_2} levels.$"

DayCare_Text_YourPartyIsFull::
	.string "Your squad's already at the limit.\n"
	.string "Fix that, then come holla at me.$"

DayCare_Text_TakeBackWhichMon::
	.string "Which one are you collecting?$"

DayCare_Text_ItWillCostX::
	.string "To get your {STR_VAR_1} back,\n"
	.string "it’s gonna cost you ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Too easy!\n"
	.string "Here’s your POKéMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} took back {STR_VAR_1} from\n"
	.string "the DAY-CARE LADY.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Wait, you’ve only got one POKéMON.\p"
	.string "I can't take your only one, man.\n"
	.string "Come back another time.$"

DayCare_Text_TakeYourMonBack::
	.string "You tryna take your POKéMON back?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "If you leave that one here, how\n"
	.string "are you gonna defend yourself?\p"
	.string "Come back with a backup.$"

DayCare_Text_Huh::
	.string "Eh?$"

