EventTicket_Text_ShowOldSeaMap:
	.string "The ferry to SLATEPORT is…\p"
	.string "Wait, what's that?\n"
	.string "You’re tryna sail to this spot on the map?\p"
	.string "Hold tight, I know a man who can\n"
	.string "sort you out properly.\p"
	.string "Wait there.$"

EventTicket_Text_ThatPass:
	.string "The ferry to SLATEPORT is…\p"
	.string "Oh?\n"
	.string "That PASS you've got there…$"

EventTicket_Text_ShowEonTicket:
	.string "Safe, young blood. You the one with\n"
	.string "that rare-looking PASS?\p"
	.string "Listen, you’re tryna reach a tiny\n"
	.string "little speck of an island way out south.\p"
	.string "No telling what kind of madness we’ll\n"
	.string "see once we land, trust me.\l"
	.string "Got me feeling bare hype!\p"
	.string "Everyone hop on!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Listen, fam, there’s absolutely nothing\n"
	.string "to do on this dead island.\p"
	.string "You ready to spin the boat back\n"
	.string "to LILYCOVE?$"

EventTicket_Text_SailHome:
	.string "Standard!\n"
	.string "We’re heading home, then!$"

EventTicket_Text_AsYouLike:
	.string "Safe, stay posted then.$"

SouthernIsland_Interior_Text_Sign:
	.string "“All dreams are just another reality.\n"
	.string "Keep that same energy…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Those whose memories fade seek to\n"
	.string "carve them in their hearts…”$"

