EventTicket_Text_OldSeaMapTooFar:
	.string "What's the word, youngster?\p"
	.string "Wait, you’re the one with that\n"
	.string "tattered old map?\p"
	.string "Let me see the levels…\n"
	.string "… … … … … …\p"
	.string "Boy, this is a long, long way.\n"
	.string "I can't reach that, it’s too far out.$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Hold it right there!\p"
	.string "What’s the deal? You’re tryna air\n"
	.string "someone that I owe so much to?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}, I’m bare sorry.\p"
	.string "You came to me for the linkup,\n"
	.string "and we almost turned you away.\p"
	.string "Let me fix the vibes real quick.\p"
	.string "We’re sailing right now, standard!\p"
	.string "Let’s find this island on\n"
	.string "this OLD SEA MAP!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "You the one who copped that\n"
	.string "weird-looking ticket?\p"
	.string "Where you're tryna go is an island\n"
	.string "that's way, way out in the sticks.\p"
	.string "No one knows what the scene is…\p"
	.string "The thought of it has me gassed!\n"
	.string "Pure adrenaline, man!\p"
	.string "Hop on the boat, youngster!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "CAPT. BRINEY is moving bare\n"
	.string "fickle today, man…\p"
	.string "You tryna spin back to LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Island’s looking a bit tech, no?\n"
	.string "You tryna head back to LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "So it’s you with the odd tickets?\n"
	.string "Let me check the credentials…\p"
	.string "… … …Hm.\p"
	.string "These will get you to some islands\n"
	.string "that are bare far away.\p"
	.string "No one knows what the vibe is there,\n"
	.string "it could be pure madness.\p"
	.string "The very thought has me gassed!\n"
	.string "Real sailor energy!\p"
	.string "Hop on the boat, youngster!\n"
	.string "Which spot are we hitting first?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Did… Did you hear that?\n"
	.string "That deep growl from the shadows.\p"
	.string "You sure we’re safe? The vibes are\n"
	.string "looking peak. Should we dip?$"

FarawayIsland_Entrance_Text_Sign:
	.string "The writing is faded, like it’s\n"
	.string "an old-school relic…\p"
	.string "“…ber, 6th day\n"
	.string "If any human…steps foot here…\l"
	.string "again…let it be a real one…\l"
	.string "…with that hope, I’m out…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"

