gFameCheckerFlavorText_ProfOak0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK POKéMON RESEARCH LAB$"

gFameCheckerFlavorText_ProfOak1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}To make the ultimate guide on every\n"
	.string "POKéMON on the planet…\p"
	.string "That was my main goal!$"

gFameCheckerFlavorText_ProfOak2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK might look like a casual\n"
	.string "elder, but he’s the top authority.\p"
	.string "The whole POKéMON scene holds\n"
	.string "him in high regard.$"

gFameCheckerFlavorText_ProfOak3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Reports say OAK lives with his\n"
	.string "grandkids, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK’s taken a proper\n"
	.string "interest in you, kid.\p"
	.string "That old man was once a heavy\n"
	.string "hitter and a looker, too.\p"
	.string "But that was decades ago.\n"
	.string "He’s just a shadow of the old OG.$"

gFameCheckerFlavorText_ProfOak5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK is getting his own\n"
	.string "radio show on the airwaves soon.\p"
	.string "The program is called PROF.\n"
	.string "OAK’S POKéMON SEMINAR.$"

gFameCheckerFlavorText_Daisy0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's her hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}If you show DAISY your squad,\n"
	.string "she knows if the vibes are right.\p"
	.string "Sometimes, she’ll even groom\n"
	.string "a POKéMON to keep it fresh.$"

gFameCheckerFlavorText_Daisy1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}But the person the POKéMON\n"
	.string "rate the most is DAISY, trust me.$"

gFameCheckerFlavorText_Daisy2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She was gently grooming POKéMON…\n"
	.string "She was a proper angel.\p"
	.string "That girl's name…\n"
	.string "I’m sure it was DAISY.$"

gFameCheckerFlavorText_Daisy3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK lives at the crib with\n"
	.string "his grandkids, DAISY and {RIVAL}.$"

gFameCheckerFlavorText_Daisy4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A girl from PALLET, DAISY,\n"
	.string "she loves her TEA every single day.\p"
	.string "She hits the CELADON DEPT. STORE\n"
	.string "just to buy the finest TEA.$"

gFameCheckerFlavorText_Daisy5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The Spring POKéMON CONTEST\n"
	.string "Grand Champion is DAISY OAK\l"
	.string "from PALLET TOWN!$"

gFameCheckerFlavorText_Brock0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PEWTER CITY POKéMON GYM\n"
	.string "LEADER: BROCK\l"
	.string "The Rock-Solid TRAINER!$"

gFameCheckerFlavorText_Brock1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My rock-hard willpower is clear\n"
	.string "in my whole team.\p"
	.string "My POKéMON are all solid and\n"
	.string "have that real-grit determination.\p"
	.string "That’s right—my whole squad is\n"
	.string "strictly ROCK type!$"

gFameCheckerFlavorText_Brock2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There aren’t many serious POKéMON\n"
	.string "TRAINERS in this ends.\p"
	.string "They’re all just BUG CATCHERS,\n"
	.string "you know, just hobbyists.\p"
	.string "But BROCK from PEWTER GYM\n"
	.string "is a different breed entirely.$"

gFameCheckerFlavorText_Brock3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK is cool. He isn't just tough.\n"
	.string "The people rate him and respect him.\p"
	.string "I’m tryna become a GYM LEADER\n"
	.string "just like him.$"

gFameCheckerFlavorText_Brock4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Yo, I’m digging for fossils here\n"
	.string "under MT. MOON.\p"
	.string "Sometimes, BROCK from PEWTER\n"
	.string "comes through to lend a hand.$"

gFameCheckerFlavorText_Brock5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK rarely laughs, but if he\n"
	.string "starts, he can’t stop. Mad.$"

gFameCheckerFlavorText_Misty0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's her hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN CITY POKéMON GYM\n"
	.string "LEADER: MISTY\l"
	.string "The Tomboyish Mermaid!$"

gFameCheckerFlavorText_Misty1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My policy is a full-on offensive\n"
	.string "using strictly WATER POKéMON!$"

gFameCheckerFlavorText_Misty2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY is a TRAINER who’s only\n"
	.string "gonna keep getting better.\p"
	.string "She ain't losing to a rookie like you!$"

gFameCheckerFlavorText_Misty3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Heavy TRAINERS and WATER POKéMON\n"
	.string "are a common sight round here.\p"
	.string "They say MISTY from the\n"
	.string "CERULEAN GYM put in work here.$"

gFameCheckerFlavorText_Misty4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes for this location.$"

gFameCheckerFlavorText_Misty5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY is said to proper worship\n"
	.string "LORELEI from the ELITE FOUR.$"

gFameCheckerFlavorText_LtSurge0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERMILION CITY POKéMON GYM\n"
	.string "LEADER: LT. SURGE\l"
	.string "The Lightning American!$"

gFameCheckerFlavorText_LtSurge1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m telling you, kid, electric mons\n"
	.string "saved my skin during the war!$"

gFameCheckerFlavorText_LtSurge2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When I was in the Army, LT. SURGE\n"
	.string "was my strict CO.\p"
	.string "He was a proper taskmaster.$"

gFameCheckerFlavorText_LtSurge3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE was always famous for\n"
	.string "his cautious nature in the Army.$"

gFameCheckerFlavorText_LtSurge4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE set up the traps in\n"
	.string "the GYM himself.\p"
	.string "He’s got the whole place on lock.$"

gFameCheckerFlavorText_LtSurge5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SURGE is rumored to have been\n"
	.string "a pilot back home in America.\p"
	.string "He used the juice from POKéMON\n"
	.string "to power his plane. Tech.$"

gFameCheckerFlavorText_Erika0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's her hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CELADON CITY POKéMON GYM\n"
	.string "LEADER: ERIKA\l"
	.string "The Nature-Loving Princess!$"

gFameCheckerFlavorText_Erika1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am a student of the art of\n"
	.string "flower arranging.\p"
	.string "My squad is strictly made of\n"
	.string "GRASS types.$"

gFameCheckerFlavorText_Erika2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER ERIKA might be quiet,\n"
	.string "but she’s a big name round here.$"

gFameCheckerFlavorText_Erika3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We only use GRASS POKéMON at\n"
	.string "our GYM.\p"
	.string "Why? We use 'em to help with\n"
	.string "the flower arrangements!$"

gFameCheckerFlavorText_Erika4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I would never collect POKéMON if\n"
	.string "they weren’t looking aesthetic.$"

gFameCheckerFlavorText_Erika5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rumor has it if you peek into\n"
	.string "CELADON GYM, you’ll often see\l"
	.string "ERIKA caught slipping, snoozing.$"

gFameCheckerFlavorText_Koga0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}FUCHSIA CITY POKéMON GYM\n"
	.string "LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"

gFameCheckerFlavorText_Koga1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Fear the creeping horror of\n"
	.string "my POISON-type POKéMON!$"

gFameCheckerFlavorText_Koga2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even though I lost, I’m gonna keep\n"
	.string "training under the teachings\l"
	.string "of KOGA, my ninja master.$"

gFameCheckerFlavorText_Koga3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My dad is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I’m training to use POISON mons\n"
	.string "just like my old man.$"

gFameCheckerFlavorText_Koga4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA is said to have a deep\n"
	.string "knowledge of the medicine game.\p"
	.string "He even whips up his own cures to\n"
	.string "keep his squad healthy.$"

gFameCheckerFlavorText_Koga5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The SAFARI ZONE is massive, no?\p"
	.string "KOGA from the FUCHSIA GYM\n"
	.string "patrols the grounds to keep order.\p"
	.string "Safe to play here because of him.$"

gFameCheckerFlavorText_Sabrina0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's her hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON CITY POKéMON GYM\n"
	.string "LEADER: SABRINA\l"
	.string "The Psychic Specialist!$"

gFameCheckerFlavorText_Sabrina1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You heard about the girl running\n"
	.string "the SAFFRON GYM?\p"
	.string "She only rolls with PSYCHIC-type\n"
	.string "mons, yeah?$"

gFameCheckerFlavorText_Sabrina2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’ve had mental powers since I was\n"
	.string "a young girl.\p"
	.string "It started when I bent a spoon\n"
	.string "just by glancing at it.$"

gFameCheckerFlavorText_Sabrina3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m not even about the violence,\n"
	.string "but if you want it, I’ll show you\l"
	.string "what these powers can do!$"

gFameCheckerFlavorText_Sabrina4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}People say SABRINA doesn't even\n"
	.string "use words in a battle. She sends\l"
	.string "the signals straight to the brain.$"

gFameCheckerFlavorText_Sabrina5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA absolutely smoked the\n"
	.string "KARATE MASTER next door. Total wash.$"

gFameCheckerFlavorText_Blaine0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR ISLAND POKéMON GYM\n"
	.string "LEADER: BLAINE\l"
	.string "The Hotheaded Quiz Master!$"

gFameCheckerFlavorText_Blaine1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My FIRE squad is all rough and\n"
	.string "ready with that intense heat!\p"
	.string "They incinerate every challenger!$"

gFameCheckerFlavorText_Blaine2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER, BLAINE, got bare lost\n"
	.string "out in the mountains once.\p"
	.string "When night fell, a glowing bird\n"
	.string "POKéMON came through.\p"
	.string "Its light helped BLAINE find the\n"
	.string "path back to the ends safely.$"

gFameCheckerFlavorText_Blaine3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR’s BLAINE is a bit of an\n"
	.string "odd character, trust me.\p"
	.string "He’s been on the island way before\n"
	.string "the LAB was even a thought.$"

gFameCheckerFlavorText_Blaine4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It’s a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They’re standing shoulder to\n"
	.string "shoulder, looking proper happy.$"

gFameCheckerFlavorText_Blaine5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}They say BLAINE only takes off the\n"
	.string "dark shades when he’s cooking up\l"
	.string "a new quiz. Peak focus.$"

gFameCheckerFlavorText_Lorelei0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's her hustle?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m LORELEI, one of the ELITE FOUR.$"

gFameCheckerFlavorText_Lorelei1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nobody can touch me when it comes\n"
	.string "to my ice-cold squad.$"

gFameCheckerFlavorText_Lorelei2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Origins?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A heavy-hitter TRAINER grew up\n"
	.string "right here on this island.\p"
	.string "I bet even you’ve heard of her.\n"
	.string "It’s LORELEI from the ELITE FOUR!$"

gFameCheckerFlavorText_Lorelei3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She’s known for that calculated,\n"
	.string "ice-cold battle style. But LORELEI\l"
	.string "has a secret she’s hiding!$"

gFameCheckerFlavorText_Lorelei4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Did you know LORELEI has a massive\n"
	.string "collection of stuffed dolls?\p"
	.string "Every time she hits FOUR ISLAND,\n"
	.string "the collection gets bigger!$"

gFameCheckerFlavorText_Lorelei5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That LAPRAS of hers? I reckon she\n"
	.string "met it when she was a little kid.\p"
	.string "I think she caught it in ICEFALL\n"
	.string "CAVE way back when.\p"
	.string "That POKéMON has been part of the\n"
	.string "inner circle since day one.$"

gFameCheckerFlavorText_Bruno0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m BRUNO of the ELITE FOUR!$"

gFameCheckerFlavorText_Bruno1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’ve spent my whole life training\n"
	.string "with my FIGHTING-type squad!$"

gFameCheckerFlavorText_Bruno2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO only joined the ELITE FOUR\n"
	.string "because he’s thirsty to test his\l"
	.string "skills against the best TRAINERS.$"

gFameCheckerFlavorText_Bruno3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO is like a senior to me.\n"
	.string "He hits the SPA every now and then.\p"
	.string "He’s there to rehab his injuries\n"
	.string "and look after his team.$"

gFameCheckerFlavorText_Bruno4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He’s one of the top brass.\n"
	.string "BRUNO is the name.\p"
	.string "He was bare disappointed when he\n"
	.string "found out the shop was sold out\l"
	.string "of Rage Candybars. Too peak.$"

gFameCheckerFlavorText_Bruno5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even a legend like BRUNO…\n"
	.string "He used to train with a man\l"
	.string "named BRAWLY back in the day.$"

gFameCheckerFlavorText_Agatha0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's her hustle?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am AGATHA, ELITE FOUR legend.$"

gFameCheckerFlavorText_Agatha1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA’s GHOST-type squad is\n"
	.string "terrifyingly tough. No cap.$"

gFameCheckerFlavorText_Agatha2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That old lady has a proper short\n"
	.string "fuse, man.\p"
	.string "It doesn't take much to get her\n"
	.string "shouting at everyone. Shook.$"

gFameCheckerFlavorText_Agatha3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Back in the day, AGATHA and PROF.\n"
	.string "OAK were rivals, always tryna\l"
	.string "see who was the top TRAINER.$"

gFameCheckerFlavorText_Agatha4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK’s taken an interest in\n"
	.string "your progress, child.\p"
	.string "That old man used to be a proper\n"
	.string "heavyweight and a looker.\p"
	.string "But that was decades ago.\n"
	.string "He’s just a shadow of his old self.$"

gFameCheckerFlavorText_Agatha5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s her vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Look at AGATHA, for real.\p"
	.string "She set the record for the oldest\n"
	.string "ever member of the ELITE FOUR.$"

gFameCheckerFlavorText_Lance0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m the leader of the ELITE FOUR.\p"
	.string "You can call me LANCE, the\n"
	.string "DRAGON master.$"

gFameCheckerFlavorText_Lance1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know dragons are mythical\n"
	.string "POKéMON.\p"
	.string "Hard to catch, hard to raise, but\n"
	.string "their power levels are unmatched.\p"
	.string "They’re basically indestructible.\n"
	.string "You can't outsmart 'em.$"

gFameCheckerFlavorText_Lance2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He stands for justice!\n"
	.string "He’s cool and passionate!\l"
	.string "LANCE is the absolute GOAT!$"

gFameCheckerFlavorText_Lance3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE is a regular customer of ours.\p"
	.string "He’s always buying new capes.\p"
	.string "I wonder… does he have a wardrobe\n"
	.string "full of the exact same cape?$"

gFameCheckerFlavorText_Lance4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE’s grandad is basically the\n"
	.string "elder of a legendary clan of\l"
	.string "dragon masters.$"

gFameCheckerFlavorText_Lance5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Word is, LANCE has a cousin who’s\n"
	.string "a GYM LEADER way out in another\l"
	.string "region.$"

gFameCheckerFlavorText_Bill0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL is world-famous as a total\n"
	.string "POKéMANIAC. A real enthusiast.\p"
	.string "He even built the POKéMON Storage\n"
	.string "System on the PC. Proper tech.$"

gFameCheckerFlavorText_Bill1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL’s got a madness of POKéMON!\n"
	.string "He collects all the rare ones too!$"

gFameCheckerFlavorText_Bill2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That’s my grandson!\p"
	.string "He was always out here collecting\n"
	.string "things, even when he was a tot!$"

gFameCheckerFlavorText_Bill3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL is a POKéMANIAC, so he rates\n"
	.string "every single type.\p"
	.string "Word is, the first one he ever\n"
	.string "caught was an ABRA. Safe choice.$"

gFameCheckerFlavorText_Bill4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL’s hometown is GOLDENROD,\n"
	.string "where his folks are still posted.\p"
	.string "I heard it’s a proper lively city,\n"
	.string "bare festive vibes everywhere.$"

gFameCheckerFlavorText_Bill5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparently, BILL can’t even handle\n"
	.string "a drop of milk. Weak stomach, fam.$"

gFameCheckerFlavorText_MrFuji0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He’s a real one.\p"
	.string "He looks after all the abandoned\n"
	.string "and orphaned POKéMON.$"

gFameCheckerFlavorText_MrFuji1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy stepped right up to\n"
	.string "our HIDEOUT, no fear.\p"
	.string "Started ranting about how TEAM\n"
	.string "ROCKET is moving foul.\p"
	.string "So, we’re just 'negotiating' with\n"
	.string "the elder right now.$"

gFameCheckerFlavorText_MrFuji2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! Clipped out. Someone already\n"
	.string "tried to secure the bag.$"

gFameCheckerFlavorText_MrFuji3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The word on the street…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear MR. FUJI isn’t originally\n"
	.string "from these ends, you know?$"

gFameCheckerFlavorText_MrFuji4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It’s a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They’re standing shoulder to\n"
	.string "shoulder, grinning like legends.$"

gFameCheckerFlavorText_MrFuji5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy MR. FUJI ducked\n"
	.string "our interview requests.\p"
	.string "He’s a kind soul who’s bare\n"
	.string "respected in LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET takes POKéMON from\n"
	.string "all over the globe.\p"
	.string "They’re vital assets for keeping\n"
	.string "the business booming.\p"
	.string "I’m the boss, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The preferred squad?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those goons that raided the spot…\p"
	.string "Their BOSS said he was only\n"
	.string "looking for high-tier POKéMON.$"

gFameCheckerFlavorText_Giovanni2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What’s his vibe?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET’s BOSS is moving\n"
	.string "bare cold-hearted!\p"
	.string "To him, POKéMON are just tools\n"
	.string "to help the come-up.$"

gFameCheckerFlavorText_Giovanni3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome to my hideout!\p"
	.string "It stays like this until I get\n"
	.string "TEAM ROCKET back to the top.$"

gFameCheckerFlavorText_Giovanni4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What's his hustle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m shook! GIOVANNI was actually\n"
	.string "the LEADER of VIRIDIAN GYM?$"

gFameCheckerFlavorText_Giovanni5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The inner circle?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Wait… you’re not GIOVANNI’s son,\n"
	.string "are you?\p"
	.string "Nah, can’t be. The boss’s kid\n"
	.string "has red hair. Bare different.$"

gFameCheckerPersonName_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON go so hard for you\n"
	.string "in every battle?\p"
	.string "It’s because they see the real\n"
	.string "trust you’ve got for them.\p"
	.string "Don't ever let that slide.$"

gFameCheckerPersonName_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"

gFameCheckerPersonQuote_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was chilling and having\n"
	.string "my tea, you’ve become a legend.\p"
	.string "Keep being a proper rival to my\n"
	.string "little brother, yeah?$"

gFameCheckerPersonName_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The world is massive, so there’s\n"
	.string "bound to be bare tough TRAINERS.\p"
	.string "Let’s keep grinding so we can\n"
	.string "both stay on top!$"

gFameCheckerPersonName_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m gonna keep putting in work\n"
	.string "here at the GYM.\p"
	.string "Once I’ve leveled up, I’m tryna\n"
	.string "hit the road and see the world.$"

gFameCheckerPersonName_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Yo, kid!\n"
	.string "You proper shocked me in our match!\p"
	.string "I didn't think rookies had guts\n"
	.string "like yours.\p"
	.string "You’ve officially changed my mind\n"
	.string "about you! Safe!$"

gFameCheckerPersonName_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m so happy that there are elite\n"
	.string "TRAINERS like you out there.\p"
	.string "Seeing you work motivates me to\n"
	.string "stop being lazy.\p"
	.string "Come link me again sometime.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I have to keep our heads\n"
	.string "up and handle our business.\p"
	.string "Now, I’ve got to go train my\n"
	.string "daughter. Stay sharp.$"

gFameCheckerPersonName_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The bond you have with your\n"
	.string "team…\p"
	.string "It’s a power that my psychic\n"
	.string "abilities could never touch.$"

gFameCheckerPersonName_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My FIRE squad!\n"
	.string "They’re gonna be even more tech!\p"
	.string "Quick quiz: How many types of\n"
	.string "FIRE POKéMON exist? Get guessing!$"

gFameCheckerPersonName_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I had to reach out and thank you\n"
	.string "for the assist.\p"
	.string "But don't get it twisted, that\n"
	.string "doesn't change our battles.\p"
	.string "Watch your back next time!$"

gFameCheckerPersonName_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’ve seen that high-tier power\n"
	.string "you and your squad carry.\p"
	.string "Next time, I might have to show\n"
	.string "you how to level up your own\l"
	.string "physical game!$"

gFameCheckerPersonName_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you get older, don't you\n"
	.string "dare go soft like that old duff OAK!\p"
	.string "Stay like me and keep the energy\n"
	.string "for the battle!$"

gFameCheckerPersonName_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’m thinking of heading back to\n"
	.string "the ends for a bit.\p"
	.string "I need to retrain my DRAGON squad\n"
	.string "and boost their levels.\p"
	.string "I’ll have to get you an invite to\n"
	.string "my hometown one day. Standard.$"

gFameCheckerPersonName_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Yo! CELIO was gassing you up,\n"
	.string "saying you're the GOAT.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare mons,\n"
	.string "come show me the levels. Trust!$"

gFameCheckerPersonName_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of just looking out for\n"
	.string "the vibes of your own squad…\p"
	.string "…Can you make sure every POKéMON\n"
	.string "out there is living their best life?$"

gFameCheckerPersonName_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I’ve got absolutely nothing to\n"
	.string "say to you.\p"
	.string "I’m moving in silence and focusing\n"
	.string "on my own grind. Nobody else.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET TOWN$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "RESEARCH LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "WATER LABYRINTH$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "VIRIDIAN CITY$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PEWTER GYM$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PEWTER CITY$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MT. MOON$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "PEWTER MUSEUM$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "CERULEAN GYM$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "SEAFOAM ISLANDS$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CERULEAN CAPE$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "VERMILION GYM$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "VERMILION CITY$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CELADON CITY$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "CELADON GYM$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "FUCHSIA GYM$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "SAFARI ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "THREE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "SAFFRON GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "RESORT GORGEOUS$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "FIVE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "FOUR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "EMBER SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "TWO ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SEVAULT CANYON$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SEVEN ISLAND$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SIX ISLAND$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "POKéMON LEAGUE$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFFRON CITY$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CELADON DEPT.$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "INDIGO PLATEAU$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CERULEAN CITY$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCHSIA CITY$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ONE ISLAND$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "POKéMON TOWER$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVENDER TOWN$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "CINNABAR GYM$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CINNABAR ISLAND$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "ROCKET HIDEOUT$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH CO.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "VIRIDIAN GYM$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ROCKET WAREHOUSE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "THE PROF$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "AIDE$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "LOCAL$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "BOY$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "SIGN$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "LITTLE BOY$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "THE ROCKETS$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "POKé JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéMON JOURNAL\p"
	.string "Expose: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely cracks a smile, but\n"
	.string "word is, if he starts laughing,\l"
	.string "he’s got no chill and won't stop.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéMON JOURNAL\p"
	.string "Expose: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "Rumor has it MISTY lowkey stans\n"
	.string "LORELEI of the ELITE FOUR.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéMON JOURNAL\p"
	.string "Expose: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE was reportedly a pilot\n"
	.string "back in the States.\p"
	.string "He used juice generated by\n"
	.string "POKéMON to power his jet.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéMON JOURNAL\p"
	.string "Expose: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Word on the street is if you peak\n"
	.string "into the GYM, you'll catch ERIKA\l"
	.string "caught in 4K just snoozing.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéMON JOURNAL\p"
	.string "Expose: FUCHSIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to be an absolute\n"
	.string "expert on medicine.\p"
	.string "He even whips up custom remedies\n"
	.string "to get his squad back to 100.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéMON JOURNAL\p"
	.string "Expose: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say SABRINA is telepathic\n"
	.string "and links with her squad in\l"
	.string "battle without saying a word.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéMON JOURNAL\p"
	.string "Expose: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE only takes the shades off\n"
	.string "when he’s in the lab cooking up\l"
	.string "new quiz questions.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéMON JOURNAL\p"
	.string "Expose:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Famous for her calculated and\n"
	.string "icy battle style, LORELEI has\l"
	.string "a secret that’ll shake the fans!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéMON JOURNAL\p"
	.string "Expose:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO joined the ELITE FOUR because\n"
	.string "he’s thirsty to battle the top-\l"
	.string "tier TRAINERS in the game.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéMON JOURNAL\p"
	.string "Expose:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "Back in the day, AGATHA and PROF.\n"
	.string "OAK were rivals constantly beefing\l"
	.string "over who was the top TRAINER.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéMON JOURNAL\p"
	.string "Expose:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the OG of a legendary clan of\l"
	.string "dragon masters.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON JOURNAL\p"
	.string "Expose: PROF. OAK,\n"
	.string "the POKéMON Researcher!\p"
	.string "The PROF reportedly stays with his\n"
	.string "grandkids DAISY and {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN! Legend!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéMON JOURNAL\p"
	.string "Expose:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI ducked\n"
	.string "our interview requests again.\p"
	.string "He’s a real one who’s bare\n"
	.string "respected in LAVENDER TOWN.$"

