Trade_Text_LookingForMonWannaTradeForMon::
	.string "I’m tryna find a {STR_VAR_1}!\p"
	.string "You down to swap one for my\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Ah, peak!\n"
	.string "Safe then…$"

Trade_Text_WhatThatsNoMon::
	.string "Wait, what?\n"
	.string "That’s not a {STR_VAR_1}, fam!$"

Trade_Text_HeyThanks::
	.string "Yo, nice one!$"

Trade_Text_IsntMyOldMonGreat::
	.string "My old {STR_VAR_2} is a beast, yeah?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Yo! Do you happen to have a\n"
	.string "{STR_VAR_1} on you?\p"
	.string "Would you be up for a swap for\n"
	.string "my {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Fine, if you’re not feeling it…$"

Trade_Text_ThisIsntMon::
	.string "Huh?\n"
	.string "This isn’t a {STR_VAR_1}.\p"
	.string "Link me if you actually get one.$"

Trade_Text_Thanks::
	.string "Safe!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "That {STR_VAR_2} I gave you,\n"
	.string "is it leveling up well?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Hi!\n"
	.string "You got a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "That’s a letdown.$"

Trade_Text_ThisIsNoMon::
	.string "…This isn't a {STR_VAR_1}.\p"
	.string "If you catch one, let’s trade.$"

Trade_Text_ThanksYoureAPal::
	.string "Thanks, you’re a real one!$"

Trade_Text_HowIsMyOldMon::
	.string "How’s my old {STR_VAR_2} doing?\n"
	.string "My {STR_VAR_1} is absolute vibes!$"

