LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Yo! Welcome to the POKéMON LOTO.\p"
	.string "All our customers get one free shot\n"
	.string "at drawing a LOTO TICKET.\p"
	.string "If the number matches the ID of any\n"
	.string "POKéMON on your squad, you’re\l"
	.string "taking home a massive prize.\p"
	.string "You feeling lucky? Want to draw a\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Limit one per day, fam.\n"
	.string "Check back tomorrow.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Safe. Link me again later.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Aight, grab a TICKET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "The LOTO TICKET number is {STR_VAR_1}.\p"
	.string "Lemme run a quick check to see if\n"
	.string "this matches any of your team’s\l"
	.string "IDs. Just a sec…$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Yooo, big moves!\p"
	.string "The ID for your {STR_VAR_1}\n"
	.string "matches the TICKET number!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Ayyy, congrats!\p"
	.string "The ID for your {STR_VAR_1}\n"
	.string "back in the PC matches the TICKET!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "That’s peak…\n"
	.string "None of the numbers matched up.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Two digits matched! You secured\n"
	.string "the third prize!\l"
	.string "Here’s your {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Three digits matched! That’s a\n"
	.string "second-place win!\l"
	.string "You won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Four digits matched?! Mad.\n"
	.string "You won the first prize!\l"
	.string "Take the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "No way! All five digits matched?!\p"
	.string "You just hit the jackpot, fam!\n"
	.string "Here’s your {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Wait…\n"
	.string "Your BAG is looking bare stuffed.\p"
	.string "Clear some space and then come\n"
	.string "link me for your prize.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Yeah, I was waiting for you.\p"
	.string "Here’s that prize I was holding\n"
	.string "for you.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Safe. See you around.$"

