MatchCall_WildBattleText1::
	.string "Yo! {PLAYER}, WYS?\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "I clocked this {STR_VAR_2} earlier\n"
	.string "but I couldn't firm the catch.\p"
	.string "It was bare close, as well!\n"
	.string "Safe, catch you in a bit!$"

MatchCall_WildBattleText2::
	.string "Yo, {PLAYER}.\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "I tried to bag a nice {STR_VAR_2}\n"
	.string "just a minute ago.\p"
	.string "But it gave me the slip.\n"
	.string "I was proper gutted!\p"
	.string "Aight, safe!$"

MatchCall_WildBattleText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I just had a go at catching\n"
	.string "this {STR_VAR_2}, but it bolted.\p"
	.string "I came oh so close, no cap!\p"
	.string "Ruined my whole vibe…\n"
	.string "Aight, see you!$"

MatchCall_WildBattleText4::
	.string "WYS, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "You know that POKéMON {STR_VAR_2}?\n"
	.string "I almost had it in the bag.\p"
	.string "It was just a bit ago.\n"
	.string "Thought I had it but it legged it.\p"
	.string "If I see it again, it’s mine\n"
	.string "for real, though.\p"
	.string "Safe, laters.$"

MatchCall_WildBattleText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\l"
	.string "Catching anything lately?\p"
	.string "A bit ago I nearly bagged one,\n"
	.string "but it got loose.\p"
	.string "Safe, take care!$"

MatchCall_WildBattleText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "Caught any decent POKéMON?\p"
	.string "I nearly nabbed one the other day.\n"
	.string "But it dashed on me.\p"
	.string "Stay safe.$"

MatchCall_WildBattleText7::
	.string "…Wait, {PLAYER}?\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "Yo, wait! Wait!\n"
	.string "I can catch this {STR_VAR_2}…\p"
	.string "Ahhh! It bolted loose!\n"
	.string "That was so peak!$"

MatchCall_WildBattleText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} on the line.\p"
	.string "You having any luck catching\n"
	.string "POKéMON lately?\p"
	.string "I was bare close a minute\n"
	.string "ago, but the target dipped.\p"
	.string "Need to step my game up!\n"
	.string "Safe, see you!$"

MatchCall_WildBattleText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "So? Are you getting your squad\n"
	.string "together or what?\p"
	.string "I’m having a stinker, man!\n"
	.string "They’re all dodging me!\p"
	.string "Laters!$"

MatchCall_WildBattleText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Listen, I came within a whisker of\n"
	.string "bagging this {STR_VAR_2}…\p"
	.string "But, it gave me the slip…\p"
	.string "I need to grind harder.\n"
	.string "See you around.$"

MatchCall_WildBattleText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "What’s the word with you?\p"
	.string "I tried to catch a wild {STR_VAR_2}\n"
	.string "earlier, but it managed to flee.\p"
	.string "I feel bare defeated…$"

MatchCall_WildBattleText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you still catching POKéMON?\p"
	.string "I’ve been trying to bag them\n"
	.string "myself, but it’s a madness.\p"
	.string "The POKéMON life is deep!$"

MatchCall_WildBattleText13::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Have you been catching POKéMON?\p"
	.string "I’ve been trying to bag them\n"
	.string "myself, but with zero success.\p"
	.string "The POKéMON life is deep!$"

MatchCall_WildBattleText14::
	.string "Yo, {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Just now, I tried to catch a\n"
	.string "sick {STR_VAR_2}.\p"
	.string "It got away, though!\n"
	.string "I was proper fuming, no lie!\p"
	.string "Laters!$"

MatchCall_WildBattleText15::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've been thinking about trying\n"
	.string "to catch me some POKéMON.\p"
	.string "But I can’t find a single one.\n"
	.string "It’s a proper head-scratcher!\p"
	.string "I’m losing my mind here!\n"
	.string "See you around!$"

MatchCall_NegativeBattleText1::
	.string "Yo! {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I stepped to another TRAINER,\n"
	.string "but I got cooked.\p"
	.string "It was proper peak.\n"
	.string "Safe, see you!$"

MatchCall_NegativeBattleText2::
	.string "WYS, {PLAYER}.\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "I challenged someone after\n"
	.string "we battled.\p"
	.string "I was close, but I took the L\n"
	.string "in the end. Safe then!$"

MatchCall_NegativeBattleText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I just got rinsed in a battle.\p"
	.string "Guess I need to level up the\n"
	.string "squad some more!$"

MatchCall_NegativeBattleText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I tried another battle yesterday,\n"
	.string "but I couldn't secure the win.\p"
	.string "My team needs more grinding.\n"
	.string "Safe, laters.$"

MatchCall_NegativeBattleText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "What’s the word with you?\p"
	.string "I've been battling away,\n"
	.string "but I’m catching nothing but Ls.\p"
	.string "I can't get it together.\n"
	.string "Safe, take care!$"

MatchCall_NegativeBattleText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been battling hard lately,\n"
	.string "but with zero luck.\p"
	.string "Can’t get into the groove.\n"
	.string "Stay safe.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going lately?\p"
	.string "I lost a battle yesterday,\n"
	.string "and it’s living in my head.\p"
	.string "I have to devise a plan…\n"
	.string "Safe.$"

MatchCall_NegativeBattleText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} on the line.\p"
	.string "How are your POKéMON doing?\n"
	.string "I lost a match the other day.\p"
	.string "I need to grind harder!\n"
	.string "Safe, see you!$"

MatchCall_NegativeBattleText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Listen, listen, you have to hear\n"
	.string "this madness!\p"
	.string "I had a battle earlier,\n"
	.string "but I lost at the last second.\p"
	.string "Oh, I’m proper fuming!$"

MatchCall_NegativeBattleText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "A bit earlier, I was in a battle.\n"
	.string "I got rinsed, though.\p"
	.string "I need to level my team more.\n"
	.string "See you around.$"

MatchCall_NegativeBattleText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are your POKéMON?\p"
	.string "I just took another L.\p"
	.string "Aight, safe!$"

MatchCall_NegativeBattleText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you still battling hard?\p"
	.string "As for me, I lost recently, so I’ve\n"
	.string "been grinding my team again.\p"
	.string "Link me later.$"

MatchCall_NegativeBattleText13::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you’ve been keeping well.\p"
	.string "I was in a battle just a little\n"
	.string "while before this.\p"
	.string "{PLAYER}, try to be active like me.\n"
	.string "Safe!$"

MatchCall_NegativeBattleText14::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Are you doing good?\p"
	.string "You should go home every so often,\n"
	.string "no cap.\p"
	.string "Laters!$"

MatchCall_PositiveBattleText1::
	.string "Yo! {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I battled another TRAINER earlier.\n"
	.string "I smoked them! I won!\p"
	.string "My {STR_VAR_2} really put in work.\n"
	.string "This is bare sick!$"

MatchCall_PositiveBattleText2::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}!\p"
	.string "I had a battle yesterday and\n"
	.string "I secured the W! Gassed!$"

MatchCall_PositiveBattleText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}!\l"
	.string "How’s your battling?\p"
	.string "Me, I had a scrap the other day,\n"
	.string "and my {STR_VAR_2} came up huge!\p"
	.string "Next time I battle you,\n"
	.string "{PLAYER}, I ain’t losing!$"

MatchCall_PositiveBattleText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I had a match earlier.\n"
	.string "I secured the win, but it was close.\p"
	.string "My {STR_VAR_2} put on an\n"
	.string "inspired showing, trust.$"

MatchCall_PositiveBattleText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "What’s the word with you?\n"
	.string "Battling much?\p"
	.string "I just won a while back!\n"
	.string "My {STR_VAR_2} was brilliant!\p"
	.string "You wait. I’m gonna rinse you\n"
	.string "next time! Safe, take care!$"

MatchCall_PositiveBattleText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I’ve been riding a hot streak.\n"
	.string "Why, I just won a battle.\p"
	.string "When we have our next battle,\n"
	.string "I’m definitely not losing!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} is a force!\n"
	.string "It won me another battle just now!\p"
	.string "I can’t wait to have a rematch\n"
	.string "with you.$"

MatchCall_PositiveBattleText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} on the line.\p"
	.string "I hope you’ve been well.\n"
	.string "I wanted to tell you I just won.\p"
	.string "My {STR_VAR_2} worked especially\n"
	.string "hard to get the win.\p"
	.string "Safe, see you!$"

MatchCall_PositiveBattleText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "How are your POKéMON holding up?\n"
	.string "Mine just secured the W!\p"
	.string "My {STR_VAR_2} was spectacular,\n"
	.string "I must say!\p"
	.string "I wish I could’ve shown you!\n"
	.string "Safe, see you!$"

MatchCall_PositiveBattleText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How has life been treating you?\p"
	.string "My POKéMON appear to be charged\n"
	.string "with energy.\p"
	.string "I just won a battle with them.\n"
	.string "See you around.$"

MatchCall_PositiveBattleText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I just won another one today!\p"
	.string "I’m on a roll! Mad! \n"
	.string "Aight, safe!$"

MatchCall_PositiveBattleText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I trust you’ve been well?\n"
	.string "I’m still full of energy!\p"
	.string "Why, just now, I won another match.\n"
	.string "I ain’t stepping aside for you\l"
	.string "younger ones yet!$"

MatchCall_PositiveBattleText13::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you’ve been keeping well.\n"
	.string "I still have a bounce in my step!\p"
	.string "Why, I just won a battle yet again.\n"
	.string "Oh, I won’t lose to youngsters\l"
	.string "quite yet!\p"
	.string "Safe, see you!$"

MatchCall_PositiveBattleText14::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I was in a battle recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it,\n"
	.string "{PLAYER}. Laters!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Yo! {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Huh? Wait, you’re near\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, mad, we have to battle, then!\n"
	.string "I’ll be waiting! Safe!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "Oh? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to battle now?\n"
	.string "I’ll wait for you! Laters!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "Oh, hey, are you near\n"
	.string "{STR_VAR_2} right now?\p"
	.string "How would you like to battle with\n"
	.string "me right now?\p"
	.string "I ain’t losing again!\n"
	.string "I’ll be waiting! Link me soon!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts are you now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to battle now?\n"
	.string "I’ll wait for you. Safe!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\l"
	.string "What’s the word with you?\p"
	.string "You’re where now?\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, how about we have a quick\n"
	.string "rematch right away?\p"
	.string "I’ll keep an eye out for you.\n"
	.string "Link me soon!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your POKéMON keeping?\p"
	.string "Oh, is that right? You’re around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we’d better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "Safe!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Wait, {PLAYER}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let’s battle.\n"
	.string "Right away, I mean.\p"
	.string "I’ll show you my POKéMON.\n"
	.string "I’ll wait for you.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} on the line.\p"
	.string "I hope you’re doing well.\n"
	.string "Oh, you’re near {STR_VAR_2}.\p"
	.string "Would you like to have a battle\n"
	.string "with me, then?\p"
	.string "I’ll wait for you.\n"
	.string "Safe, link me!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Are you keeping up?\n"
	.string "Oh, you’re near {STR_VAR_2}?\p"
	.string "Oh, well, then don’t you think we\n"
	.string "should scrap?\p"
	.string "Don’t keep me waiting too long!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Oh, you’re near {STR_VAR_2}.\p"
	.string "We should have a battle now, then.\p"
	.string "I’m ready and waiting.\n"
	.string "Be quick!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Ah, so where you are now is\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we just have to have\n"
	.string "a scrap, don’t you think?\p"
	.string "I’ll wait around for you!\n"
	.string "Safe, link me quick!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "{STR_VAR_2}?\n"
	.string "That’s quite close by!\p"
	.string "What do you say we have a battle\n"
	.string "now?\p"
	.string "I can wait.\n"
	.string "Safe!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you’ve been keeping well.\n"
	.string "Oh, you’re near {STR_VAR_2}?\p"
	.string "Since that’s not very far away,\n"
	.string "come see me for a battle.\p"
	.string "I’ll wait for you.\n"
	.string "Laters.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You’re what? …{STR_VAR_2}?\n"
	.string "That’s very close.\p"
	.string "Don’t you think we ought to have\n"
	.string "a battle?\p"
	.string "I’ll be looking for you!\n"
	.string "Laters!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Yo! {PLAYER}, WYS?\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "You want to have a scrap with me?\p"
	.string "I’m posted up around\n"
	.string "{STR_VAR_2}! Slide through!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "You want to go again for a\n"
	.string "rematch or what?\p"
	.string "You can find me at {STR_VAR_2}.\n"
	.string "I’ll be waiting for the smoke!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "My squad has grown bare\n"
	.string "tough since the last link.\p"
	.string "I want to see how they move\n"
	.string "against your team, {PLAYER}.\p"
	.string "So, let’s have a madness!\p"
	.string "I’m waiting for you at\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "WYS, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My POKéMON are looking proper\n"
	.string "dangerous lately.\p"
	.string "Yo, how would you like to have\n"
	.string "another scrap with me?\p"
	.string "Link me around {STR_VAR_2},\n"
	.string "yeah? Safe.$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "My squad is leveling up in\n"
	.string "some mad ways.\p"
	.string "I really want to have another\n"
	.string "clash with you.\p"
	.string "I’ll be watching out for you at\n"
	.string "{STR_VAR_2}. Link me soon!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you’re on top of your game.\p"
	.string "I was thinking I’d like another\n"
	.string "scrap. What do you say?\p"
	.string "If you’re ready for the heat,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "Laters!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Wait, {PLAYER}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Is your squad growing?\p"
	.string "Mine definitely got beefier.\n"
	.string "I want to show you the levels.\p"
	.string "I’ll be around {STR_VAR_2}.\n"
	.string "Slide through for a match.\p"
	.string "Safe, see you around.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you’re doing well.\n"
	.string "My POKéMON are feeling frisky.\p"
	.string "If you’re ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I’m posted at {STR_VAR_2}.\n"
	.string "Until then, safe!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How is your squad doing?\p"
	.string "My POKéMON keep getting better.\n"
	.string "I want to show you the sauce.\p"
	.string "I’m around {STR_VAR_2} now,\n"
	.string "so let’s scrap if you’re close.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My POKéMON have grown much\n"
	.string "stronger than before, no cap.\p"
	.string "I’d love another battle with you,\n"
	.string "{PLAYER}.\p"
	.string "I’ll be around {STR_VAR_2}.\n"
	.string "Slide through if you’re near.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Where you at right now?\p"
	.string "My POKéMON are full of life.\n"
	.string "They’re itching to see your\l"
	.string "squad again, {PLAYER}.\p"
	.string "I’m at {STR_VAR_2} now.\n"
	.string "I hope you’ll come find us.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I’m telling you, my squad has\n"
	.string "grown proper robust lately.\p"
	.string "I want to see them in a battle\n"
	.string "with you, {PLAYER}.\p"
	.string "We’ll be around {STR_VAR_2}.\n"
	.string "Slide through anytime!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Yo, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Is your team keeping well?\p"
	.string "My POKéMON have been so healthy,\n"
	.string "they don’t look like they can take an L!\p"
	.string "I would surely love to have another\n"
	.string "clash with you.\p"
	.string "If you’re near {STR_VAR_2},\n"
	.string "do come link us.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Yo, {PLAYER}, safe.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Oh, trust! My POKéMON are\n"
	.string "much stronger than before.\p"
	.string "Don’t you think we ought to have\n"
	.string "a scrap, {PLAYER}?\p"
	.string "We’ll be waiting for you at\n"
	.string "{STR_VAR_2}.\p"
	.string "Link us anytime, yeah?$"

MatchCall_PersonalizedText1::
	.string "It’s me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "So, since we met, have you grown\n"
	.string "to appreciate the peaks more?\p"
	.string "I rarely see you on the heights…\p"
	.string "Next time, we’ll link somewhere\n"
	.string "around {STR_VAR_2}. Safe!$"

MatchCall_PersonalizedText2::
	.string "This is {STR_VAR_1}.\n"
	.string "Safe.\p"
	.string "I was just telling a new TRAINER\n"
	.string "about you.\p"
	.string "Told her about a top-tier TRAINER\n"
	.string "who moves with bare care.\p"
	.string "I hope you become a legend\n"
	.string "that everyone respects.\p"
	.string "I hope we link again!$"

MatchCall_PersonalizedText3::
	.string "Yo! It’s {STR_VAR_1}.\p"
	.string "I love where I’m posted now.\n"
	.string "The aromas are proper sweet!\p"
	.string "I think someone planted BERRIES,\n"
	.string "and they’re blooming mad.\p"
	.string "Safe, see you again!$"

MatchCall_PersonalizedText4::
	.string "Yo! Thirty years on the grind,\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems you’re energetically\n"
	.string "traveling here and there.\p"
	.string "Found any new ruins yet?\n"
	.string "Let me know if you have!\p"
	.string "Now, if you’ll excuse me,\n"
	.string "I’ve got ruins to explore. Safe.$"

MatchCall_PersonalizedText5::
	.string "It’s {STR_VAR_1}!\p"
	.string "Know what I’m doing today?\n"
	.string "Watching waves from the beach!\p"
	.string "Sigh… The waves are bare sparkly.\n"
	.string "The sea is the prettiest from here.\l"
	.string "I’m getting hungry, so laters!$"

MatchCall_PersonalizedText6::
	.string "Munch-chew…\n"
	.string "Yo, it’s {STR_VAR_1}.\l"
	.string "I love eating on the beach.\p"
	.string "My POKéMON and I have been doing\n"
	.string "great. We’re fully fueled!\l"
	.string "I’m going for a swim. Safe!$"

MatchCall_PersonalizedText7::
	.string "Yo, this is {STR_VAR_1}…\p"
	.string "I’ve grown a bit tired of this\n"
	.string "whole COOLTRAINER wave…\p"
	.string "Everyone thinks I’m perfect,\n"
	.string "and I have to keep that energy up.\p"
	.string "But I guess that’s the life of\n"
	.string "a COOLTRAINER.\p"
	.string "I’ll just have to firm it…\n"
	.string "and keep it moving.\p"
	.string "You’re the only person I could\n"
	.string "confide in like this.\p"
	.string "But when I see you next,\n"
	.string "don’t worry, I won’t whine!$"

MatchCall_PersonalizedText8::
	.string "Yo, it’s {STR_VAR_1}!\n"
	.string "WYS?\p"
	.string "I’ve been raising my POKéMON with\n"
	.string "you as the main target.\p"
	.string "I don’t intend to take an L\n"
	.string "when we battle again.\p"
	.string "Isn’t it sick to have TRAINER\n"
	.string "mates? Let’s link again!$"

MatchCall_PersonalizedText9::
	.string "It’s {STR_VAR_1}…\n"
	.string "Right now, behind you…\l"
	.string "Wasn’t there something…?\p"
	.string "The power of the POKéMON that\n"
	.string "rest here at MT. PYRE…\p"
	.string "It’s telling me about you…\p"
	.string "You should leg it quickly and\n"
	.string "never once look back…\p"
	.string "Giggle…\n"
	.string "Safe…$"

MatchCall_PersonalizedText10::
	.string "This is {STR_VAR_1}.\n"
	.string "WYS?\p"
	.string "Isn’t it peak that we can\n"
	.string "chat like this from far away?\p"
	.string "Before, if I wanted to talk to\n"
	.string "anyone, I had to have my dad\l"
	.string "drive me…\p"
	.string "I should be going now.\n"
	.string "Glad we had this chat. Safe.$"

MatchCall_PersonalizedText11::
	.string "It’s {STR_VAR_1}!\n"
	.string "Will you listen to this?\p"
	.string "I like the SAFARI ZONE a lot,\n"
	.string "but I get lost every single time!\p"
	.string "All that tall grass!\n"
	.string "And it’s much too spread out!\p"
	.string "I feel better getting that off\n"
	.string "my chest!\p"
	.string "I’m off to the SAFARI ZONE again!\n"
	.string "Laters!$"

MatchCall_PersonalizedText12::
	.string "Yo, {STR_VAR_1} here.\n"
	.string "Yeah, trust, I am rich, yeah.\p"
	.string "I’m telling you, my stacks have\n"
	.string "grown since we last met.\p"
	.string "What’s more, my POKéMON have also\n"
	.string "grown bare strong.\p"
	.string "I can’t shake the feeling that\n"
	.string "this world belongs to me!\p"
	.string "Oh, no need to say a word!\n"
	.string "Everyone knows it’s true!\p"
	.string "You must excuse me, I have a\n"
	.string "formal dinner to attend. Safe.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "It’s me, {STR_VAR_1}…\p"
	.string "Can you guess what I’m seeing?\n"
	.string "A pair of {STR_VAR_2} in a scrap.\p"
	.string "Maybe I’ll catch the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I’m kind of busy now.\n"
	.string "I have to dip.$"

MatchCall_PersonalizedText14::
	.string "Oh, it’s {STR_VAR_1}!\p"
	.string "I was just thinking I’m getting\n"
	.string "bored of the ABANDONED SHIP.\p"
	.string "But since I’m already here,\n"
	.string "and I want to rinse you once,\l"
	.string "I’ll be sticking around a bit more.\p"
	.string "If you feel like it, why don’t\n"
	.string "you come see me?\p"
	.string "I think today is the day I\n"
	.string "finally challenge that guy next\l"
	.string "door to a match.\p"
	.string "Safe, see you!$"

MatchCall_PersonalizedText15::
	.string "I’m {STR_VAR_1}!\n"
	.string "The man of the sea!\p"
	.string "You know what I think?\p"
	.string "The TRAINERS out at sea are\n"
	.string "the toughest of the lot!\p"
	.string "You should learn from me and train\n"
	.string "in the sea…\p"
	.string "Whoops, giant surf rising!\p"
	.string "It’s a mad training opportunity!\n"
	.string "Sorry, but I have to dip!$"

MatchCall_PersonalizedText16::
	.string "It’s {STR_VAR_1}! Listen, I’ve been\n"
	.string "teaching karate to my POKéMON.\p"
	.string "But now they’re better than me!\n"
	.string "I’ve done nothing but take Ls!\p"
	.string "But even if I lose to POKéMON,\n"
	.string "I won’t lose to another TRAINER,\l"
	.string "no way!\p"
	.string "We have to scrap again!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "It’s me, {STR_VAR_1}.\n"
	.string "How’re your travels going?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds proper stimulating!\p"
	.string "I think I could write a tune about\n"
	.string "one of your adventures.\p"
	.string "…Oh, hey, I’m feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I’d better get this tune written,\n"
	.string "so I’ve got to fly! Later!$"

MatchCall_PersonalizedText18::
	.string "This is {STR_VAR_1}…\n"
	.string "Hear my new track.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Why are you that {STR_VAR_2}?\l"
	.string "Why can’t I be you, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} and {STR_VAR_1},\l"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "Repeat chorus, fade out…$"

MatchCall_PersonalizedText19::
	.string "I’m {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I took an L\n"
	.string "from you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "But win or lose, I love to scrap\n"
	.string "when I’m camping.\p"
	.string "Battle with us again, yeah?\n"
	.string "Oh, and let’s go camping, too!$"

MatchCall_PersonalizedText20::
	.string "It’s me, me, {STR_VAR_1}!\p"
	.string "I’d like to climb other mountains\n"
	.string "than this one, to be honest.\p"
	.string "But I’m not sure if there’d be any\n"
	.string "fit ladies like on MT. CHIMNEY.\p"
	.string "If you know any other mountain\n"
	.string "with ladies around, let me know!\p"
	.string "Ehehehe, see you around!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It’s {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That’s all for today…$"

MatchCall_PersonalizedText22::
	.string "This is {STR_VAR_1}. Today, I had\n"
	.string " this feeling I’d chat with you.\p"
	.string "My desire to rinse you builds\n"
	.string "by day and by night.\p"
	.string "You have a rival like that, yeah?\n"
	.string "I wish it were me…\p"
	.string "I’m glad you heard me out.\n"
	.string "Safe!$"

MatchCall_PersonalizedText23::
	.string "It’s {STR_VAR_1}.\p"
	.string "When there’s a top TRAINER\n"
	.string "nearby, I can sometimes sense it.\l"
	.string "Somehow.\p"
	.string "Did you pass close by, {PLAYER}?\n"
	.string "Maybe it was you.\p"
	.string "I’ll be waiting for your visit.\n"
	.string "Safe!$"

MatchCall_PersonalizedText24::
	.string "Yo, this is {STR_VAR_1}.\n"
	.string "You sound well, {PLAYER}.\p"
	.string "I’ve traveled the world,\n"
	.string "but I must say I’ve taken a great\l"
	.string "shine to this region.\p"
	.string "I plan to stay here a while.\n"
	.string "Perhaps we can meet again?\p"
	.string "I’ve not forgotten your sick\n"
	.string "techniques.\p"
	.string "I do hope for a rematch. Safe.$"

MatchCall_PersonalizedText25::
	.string "Snivel… It’s… {STR_VAR_1}…\n"
	.string "…Sob…\p"
	.string "ROXANNE chewed me out in class\n"
	.string "today.\p"
	.string "But I don’t dislike her or anything.\p"
	.string "ROXANNE tells me exactly what\n"
	.string "I did wrong so I can learn from it.\p"
	.string "You bet I’ll be at the\n"
	.string "TRAINER SCHOOL tomorrow!\p"
	.string "Safe, see you later!$"

MatchCall_PersonalizedText26::
	.string "It’s {STR_VAR_1}!\p"
	.string "ROXANNE let me have a scrap\n"
	.string "with her yesterday.\p"
	.string "The results…\n"
	.string "Proper peak, like you needed to ask.\p"
	.string "But I was gassed that ROXANNE\n"
	.string "even let me step to her!\p"
	.string "You wouldn't believe how much\n"
	.string "I respect her, for real!\p"
	.string "I’m gonna stay on my grind and work!\n"
	.string "I’d better dip! Safe!$"

MatchCall_PersonalizedText27::
	.string "Yo, it’s ANNA! I’m with my junior\n"
	.string "partner MEG again today.\p"
	.string "I love looking after MEG and the\n"
	.string "POKéMON. They’re bare cute!\p"
	.string "I wish I could look after them\n"
	.string "like they were my own siblings!\p"
	.string "Oh, yo, MEG!\n"
	.string "Did you grab the munch?\p"
	.string "Wait? No, no, I’m not treating you\n"
	.string "like my personal worker!\p"
	.string "You took the L in the match, so\n"
	.string "you have to go shop as punishment!\p"
	.string "I wouldn't move like that to you,\n"
	.string "MEG! You’re my family, for real!\p"
	.string "I have to dip now.\n"
	.string "It’s time for the snack! Safe!$"

MatchCall_PersonalizedText28::
	.string "I love POKéMON, no lie!\n"
	.string "It’s {STR_VAR_1} from the FAN CLUB!\p"
	.string "Yo, you have to hear this!\n"
	.string "My sweet POKéMON…\p"
	.string "Snort! Wahaha!\n"
	.string "I can’t even say more! It’s a secret!\l"
	.string "The cuteness is actually mad!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It’s looking proper cute, trust!\p"
	.string "Sorry, but I can’t chat now!\n"
	.string "Catch the rest of the story later!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "This is {STR_VAR_1}! I can’t wait to\n"
	.string "tell you about my darling POKéMON!\p"
	.string "Please, you have to listen to this.\n"
	.string "It’s about my darling {STR_VAR_2}.\p"
	.string "Whenever anyone tries to touch it,\n"
	.string "it leaps straight to me, fam!\p"
	.string "Oh… Oh… Could life be any\n"
	.string "more blissful?\p"
	.string "The vibes are actually heavenly!\p"
	.string "I’m gassed I could share some of\n"
	.string "this happiness with you.\p"
	.string "Well, I’ve got to dip.\n"
	.string "Safe, laters!$"

MatchCall_PersonalizedText30::
	.string "I am… {STR_VAR_1}.\n"
	.string "People call me an EXPERT.\p"
	.string "But there is one thing I know.\n"
	.string "I couldn't be a top man on my own\l"
	.string "power, you get me?\p"
	.string "Only with the help of the squad can\n"
	.string "a TRAINER reach these levels.\p"
	.string "Humph! I believe I just said\n"
	.string "something proper deep, fam!\p"
	.string "I shall leave you with those vibes!$"

MatchCall_PersonalizedText31::
	.string "It’s {STR_VAR_1}.\n"
	.string "Gassed to chat with you!\p"
	.string "I’m feeling alive and refreshed\n"
	.string "soaking in this hot-spring tub.\p"
	.string "I've been rinsing young TRAINERS\n"
	.string "since we met, but you're still\l"
	.string "the goat of the lot.\p"
	.string "I reckon you'll be a real EXPERT\n"
	.string "when you're an OG! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Yay! This is {STR_VAR_1}!\n"
	.string "WYS?\p"
	.string "I might be trippin', but when\n"
	.string "I secure the W, my shorts seem to\l"
	.string "feel, like, better. Materially.\p"
	.string "What do I mean by that?\n"
	.string "It's bare hard to explain, but…\l"
	.string "How would I say this now…\l"
	.string "My shorts feel silkier, fam!\p"
	.string "But when I scrapped with you, {PLAYER},\n"
	.string "my shorts felt icky and rough.\p"
	.string "… … … … … …\n"
	.string "You didn't actually buy that?\l"
	.string "Ehehehe, that's all! Safe now!$"

MatchCall_PersonalizedText33::
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I’m out here fishing\n"
	.string "with wild abandon, fam!\p"
	.string "Are there any other spots to fish\n"
	.string "besides the sea and rivers?\p"
	.string "I get these mad urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, allow it! Proper annoying!\n"
	.string "My line’s all tangled up!\p"
	.string "Gotta dip!\n"
	.string "Find me some new fishing spots. Safe!$"

MatchCall_PersonalizedText34::
	.string "Yo, what's the word! It’s {STR_VAR_1}.\n"
	.string "Are you taking it easy?\p"
	.string "Ever since I was a young buck, you\n"
	.string "know, I’ve always been chill, yeah?\p"
	.string "I never was one for getting all\n"
	.string "stressed or rushing the vibe.\p"
	.string "But wouldn’t you know it,\n"
	.string "I’m a TRIATHLETE now.\p"
	.string "You just can’t tell where life will\n"
	.string "take you, if you catch my drift.\p"
	.string "You’re a TRAINER now, but who\n"
	.string "knows the future plans, huh?\p"
	.string "Imagine yourself as a teacher,\n"
	.string "or maybe an artist. Sick, right?\p"
	.string "But, hey, stay cool. Keep it casual.\n"
	.string "See you around.$"

MatchCall_PersonalizedText35::
	.string "This is {STR_VAR_1}!\n"
	.string "I’m out here cycling right now.\p"
	.string "I love swimming and running,\n"
	.string "but cycling is my main love!\p"
	.string "It makes my whole body feel like\n"
	.string "I’m one with the wind, trust.\p"
	.string "It’s a madness, feels like\n"
	.string "I’m actually flying!\p"
	.string "Aight! Today, I’m gonna set a new\n"
	.string "CYCLING ROAD record!\p"
	.string "You should try the challenge too!\n"
	.string "Safe!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}! I’m smack\n"
	.string "in the middle of a triathlon!\p"
	.string "But, hey, I’ve always got time to\n"
	.string "have a quick chat!\p"
	.string "Grinding with POKéMON feels\n"
	.string "proper good!\p"
	.string "Without even speaking, we're in sync\n"
	.string "like we share the same heart.\p"
	.string "It’s inspiring, no lie!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I’m losing my breath here…\l"
	.string "Gasp… Have… to… dip…$"

MatchCall_PersonalizedText37::
	.string "Yo, it’s {STR_VAR_1}.\n"
	.string "If you want to step up your levels,\l"
	.string "high-altitude training is the one!\p"
	.string "Try running on a mountaintop.\n"
	.string "You’ll be gasping in no time!\p"
	.string "I’m proper oxygen starved, too!\n"
	.string "Safe!$"

MatchCall_PersonalizedText38::
	.string "Oh, it’s {STR_VAR_1}, safe.\p"
	.string "I’ve been swimming bare distance\n"
	.string "but I still can't reach EVERGRANDE.\p"
	.string "Maybe I’m just going in circles.\p"
	.string "Nah, nah, that ain't even possible.\n"
	.string "Wahahaha.\l"
	.string "Stay safe!$"

MatchCall_PersonalizedText39::
	.string "Yo, it’s {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Yo! Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my POKéNAV went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "But, boy, DEVON's POKéNAV is built\n"
	.string "proper tough. It survived the dunk!\p"
	.string "Anyway, I’m busy sunbathing,\n"
	.string "so let’s chat another time. Safe.$"

MatchCall_PersonalizedText40::
	.string "Yo, this is {STR_VAR_1}.\p"
	.string "Out of the three triathlon events,\n"
	.string "I like swimming the best.\p"
	.string "But if I stay in the sea too long,\n"
	.string "won’t I get all wrinkly and that?\p"
	.string "Ooh, triathlon is a proper grueling\n"
	.string "test of endurance! Laters!$"

MatchCall_PersonalizedText41::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How is your squad doing?\p"
	.string "My DRAGON POKéMON are looking\n"
	.string "to be in peak form. Safe for now.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than the last time.\p"
	.string "I’m definitely not losing to you again.\n"
	.string "Just you wait till next time!\p"
	.string "See you around. Safe!$"

MatchCall_PersonalizedText43::
	.string "It’s {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of moving silent.\p"
	.string "But I’ve been too successful.\n"
	.string "No one has been able to find me.\l"
	.string "Being this low-key makes me lonely…\p"
	.string "Like smoke I disappear!\n"
	.string "Laters!$"

MatchCall_PersonalizedText44::
	.string "This is {STR_VAR_1}.\n"
	.string "I’ve been on the grind since we met.\p"
	.string "My {STR_VAR_2} is looking proper\n"
	.string "tough now.\p"
	.string "Training on the beach is the meta,\n"
	.string "just like I thought. Safe now!$"

MatchCall_PersonalizedText45::
	.string "WYS? This is {STR_VAR_1}.\p"
	.string "I wonder when this peak volcanic\n"
	.string "ash is gonna stop falling?\p"
	.string "If it gets too deep, it’ll ruin the\n"
	.string "pattern on my parasol, no cap…\p"
	.string "Let’s link again soon!$"

MatchCall_PersonalizedText46::
	.string "Yo, {STR_VAR_1} here.\p"
	.string "Did you know it’s easier to\n"
	.string "float in the sea than a pool?\p"
	.string "If you just lie still, your body\n"
	.string "will float on its own, trust.\p"
	.string "But if you float for too long,\n"
	.string "watch you don’t get carried out\l"
	.string "too far from the ends.\p"
	.string "…Wait, where even am I?\n"
	.string "I’d better dip! Safe!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}, safe!\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I’m up in the mountains right now.\p"
	.string "But the ground is bare bumpy.\n"
	.string "I can’t even pitch my tent here…\p"
	.string "Oh, I had a mad idea!\p"
	.string "Maybe I can get my POKéMON to\n"
	.string "flatten the ground for me!\p"
	.string "I’m gonna try that right now!\n"
	.string "Laters!$"

MatchCall_PersonalizedText48::
	.string "Oh, yo, yo! This is {STR_VAR_1}!\p"
	.string "I’m raising POKéMON with LIV!\n"
	.string "We’re working bare hard!\p"
	.string "If we push it, can we reach the\n"
	.string "number one spot? Safe!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "I’m a SAILOR, but I’m not on a boat\n"
	.string "right now.\p"
	.string "It makes me wonder—what do you\n"
	.string "call a SAILOR when he’s on land?\p"
	.string "That’s what I’ve been thinking\n"
	.string "while staring at the waves.\p"
	.string "Alright, catch you next time!$"

MatchCall_PersonalizedText50::
	.string "It’s {STR_VAR_1}.\n"
	.string "So? Caught any more POKéMON?\p"
	.string "If you bag a new POKéMON,\n"
	.string "you have to come show me.\p"
	.string "I won’t whine about it, for real.\n"
	.string "I’ll be waiting. Safe.$"

MatchCall_PersonalizedText51::
	.string "This is {STR_VAR_1}.\p"
	.string "Are you raising your squad\n"
	.string "the most efficient way?\p"
	.string "The air is proper clean here.\n"
	.string "It’s the perfect vibe for\l"
	.string "leveling up POKéMON.\p"
	.string "If you want to focus on the grind,\n"
	.string "come out to {STR_VAR_2}. Safe!$"

MatchCall_PersonalizedText52::
	.string "Yo, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to love it, no lie.\p"
	.string "Turns out POKéMON have their own\n"
	.string "fave flavors with {POKEBLOCK}S.\p"
	.string "That’s actually bare interesting.\p"
	.string "Stay safe!$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} here.\p"
	.string "If you move right with POKéMON,\n"
	.string "you can live comfy in the wild.\p"
	.string "Everyone should realize that and\n"
	.string "link up with POKéMON more.\p"
	.string "That would be the dream.\n"
	.string "I really believe that.\p"
	.string "I think you’re on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54::
	.string "Yo, it’s {STR_VAR_1}. You know,\n"
	.string "the TRAINER who’s always ready!\p"
	.string "{PLAYER}, do you have enough items?\n"
	.string "Is your squad fit for the field?\p"
	.string "Keeping everything 10/10 around\n"
	.string "you is the secret to keeping\l"
	.string "the journey moving.\p"
	.string "I’d better go check my own\n"
	.string "supplies! Stay alert!$"

MatchCall_PersonalizedText55::
	.string "It’s {STR_VAR_1}!\n"
	.string "It’s {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a bare busy\n"
	.string "road, so I get challenged by\l"
	.string "all kinds of TRAINERS every day.\p"
	.string "Today, I secured five Ws and\n"
	.string "only took three Ls!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, yeah?$"

MatchCall_PersonalizedText56::
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I’m popular because I have bare\n"
	.string "BUG POKéMON, right?\p"
	.string "Well, I took a bunch of my faves\n"
	.string "to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try and show her why\n"
	.string "BUG POKéMON are actually sick.\p"
	.string "Snivel…\n"
	.string "Safe!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Yo! It’s {STR_VAR_1}! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While climbing…\l"
	.string "Is a mad workout… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "It’s steeper now…\l"
	.string "We’ll chat… another time…\l"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Oh, safe!\p"
	.string "I’m still hunting for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn’t even any loot\n"
	.string "here at all…\p"
	.string "But the main thing is that I’m\n"
	.string "searching alongside KIRA.\p"
	.string "Oh, yo, KIRA!\n"
	.string "Wh-why are you moving mad?\p"
	.string "I’m not ignoring you, babe!\n"
	.string "You’re my number one, for real!\p"
	.string "…{PLAYER}, I’ve gotta dip, safe!$"

MatchCall_PersonalizedText59::
	.string "This is {STR_VAR_1}!\p"
	.string "I went back to DEWFORD’S GYM\n"
	.string "to train again.\p"
	.string "BRAWLY, the GYM LEADER, seems\n"
	.string "to be even tougher now.\p"
	.string "Something about being built different\n"
	.string "by the wild waves…\p"
	.string "But he’s still as cool as ever.\n"
	.string "The girls are gassed for him!\l"
	.string "It makes me bare jealous, honestly.\p"
	.string "I wonder… Is his mate BRUNO\n"
	.string "the same way as BRAWLY?\p"
	.string "You know, all sweaty and that,\n"
	.string "always calling people “big wave.”\p"
	.string "But, hey, this jealousy thing isn’t\n"
	.string "a good look, is it?\p"
	.string "Forget we ever had this chat,\n"
	.string "yeah? Laters!$"

MatchCall_PersonalizedText60::
	.string "It’s a pleasure to chat with\n"
	.string "a young TRAINER like you.\p"
	.string "I reckon you’ll keep enjoying\n"
	.string "POKéMON no matter how old you get.\p"
	.string "Wouldn’t it be sick if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}, you already\n"
	.string "have the trust of your squad.\p"
	.string "You’ve got the foundation for\n"
	.string "long-term vibes already!\p"
	.string "Hahaha!\n"
	.string "Don’t ever get discouraged!$"

MatchCall_PersonalizedText61::
	.string "Yo, this is {STR_VAR_1}!\n"
	.string "We just secured a W!\p"
	.string "We don’t win often, but it was against\n"
	.string "this cool SWIMMER guy.\p"
	.string "My sister was fuming!\p"
	.string "She wanted to bait him by acting\n"
	.string "weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or take the L!\p"
	.string "{PLAYER}, can you say something\n"
	.string "to her next time?\p"
	.string "Alright, safe!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here, yeah.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I was hoping to find a new\n"
	.string "ruin to explore.\p"
	.string "But the tides somehow carried\n"
	.string "me right back to where I started.\p"
	.string "I’m still weak at battling, too…\n"
	.string "Feel free to mock me…\l"
	.string "But I won’t give up, trust.\p"
	.string "My day will come when I discover\n"
	.string "a new ruin!\p"
	.string "That’s all I’ve got to say!\n"
	.string "Safe for now!$"

MatchCall_PersonalizedText63::
	.string "Ahoy there!\n"
	.string "It’s me, {STR_VAR_1}!\l"
	.string "I’m out on ROUTE 108 now!\l"
	.string "Basically where I always am!\p"
	.string "Today, a fit SWIMMER \n"
	.string "swam past me!\p"
	.string "So I startled her with a shout!\p"
	.string "And she gave me a proper nasty look!\p"
	.string "That’s all from ROUTE 108!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "It’s {STR_VAR_1}!\p"
	.string "I’m kind of busy, but I figured\n"
	.string "I should let you know I’ve rinsed\l"
	.string "five TRAINERS again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we’ll be good rivals,\n"
	.string "you and I. Safe for now!$"

MatchCall_BattleFrontierStreakText1::
	.string "Yo! This is {STR_VAR_1}.\n"
	.string "I heard the news, fam!\p"
	.string "They’re saying you moved mad at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It’s sick, {STR_VAR_3} wins in a row?\n"
	.string "Safe, catch you later!$"

MatchCall_BattleFrontierStreakText2::
	.string "Yo, it’s {STR_VAR_1}!\n"
	.string "I heard about your run!\p"
	.string "They said you secured {STR_VAR_3} Ws\n"
	.string "straight at the {STR_VAR_2}.\p"
	.string "That’s special! I need to stay\n"
	.string "on my grind, too! Safe!$"

MatchCall_BattleFrontierStreakText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I heard you went on a madness at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A {STR_VAR_3}-win streak…\n"
	.string "That’s a big record, trust.\p"
	.string "I’d better step my game up!\n"
	.string "Link you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here. WYS?\p"
	.string "The streets are saying you copped\n"
	.string "{STR_VAR_3} straight wins at the {STR_VAR_2}.\p"
	.string "I’d better level up, too.\n"
	.string "Safe!$"

MatchCall_BattleFrontierStreakText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} in a row?\l"
	.string "That’s actually mad!\p"
	.string "I need to work on my squad more.\n"
	.string "Link you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here. You good?\p"
	.string "By the way, I heard you pulled off\n"
	.string "{STR_VAR_3} straight Ws at the {STR_VAR_2}.\p"
	.string "That’s gassed me up to focus on\n"
	.string "leveling my team. Safe!$"

MatchCall_BattleFrontierStreakText7::
	.string "…Wait, {PLAYER}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, check that rare POKéMON!\n"
	.string "I have to dip! Safe!$"

MatchCall_BattleFrontierStreakText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you’re doing well.\p"
	.string "Actually, I know you are. Heard\n"
	.string "you won {STR_VAR_3} matches straight\l"
	.string "at the {STR_VAR_2}.\p"
	.string "That’s bare impressive!\n"
	.string "Keep securing those Ws. Safe!$"

MatchCall_BattleFrontierStreakText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is too cool, no lie!\n"
	.string "I’d better stay on my grind, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That’s a proper achievement.\n"
	.string "I need to put in more work. Safe.$"

MatchCall_BattleFrontierStreakText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you’re the boss of\n"
	.string "the {STR_VAR_2} now?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row? Cold.\p"
	.string "You’re clear, fam.\n"
	.string "I wonder how many I can get?$"

MatchCall_BattleFrontierStreakText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone told me the word.\n"
	.string "How you won {STR_VAR_3} straight Ws\l"
	.string "at that {STR_VAR_2} place?\p"
	.string "That’s a legendary tale.\n"
	.string "Safe!$"

MatchCall_BattleFrontierStreakText13::
	.string "Yo, safe {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you’ve been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I respect the energy, for real!\n"
	.string "Laters.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn’t you just secure {STR_VAR_3} in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You’re an inspiration, trust!\n"
	.string "Safe!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Yo! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you moved mad at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It’s awesome—{STR_VAR_3} straight wins?\n"
	.string "Safe!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Yo, it’s {STR_VAR_1}!\n"
	.string "I heard about the run!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That’s special! I need to try\n"
	.string "harder, too! Safe!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That’s a record and a half, innit?\p"
	.string "I’d better get my life together!\n"
	.string "Link you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here. WYS?\p"
	.string "Rumor is you strung together {STR_VAR_3}\n"
	.string "straight Ws at the {STR_VAR_2}.\p"
	.string "I’d better step it up, too.\n"
	.string "Safe!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn’t that something else!\p"
	.string "Me? I’d say I’m doing my bits.\n"
	.string "Link you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here. How you doing?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I’d better work harder myself!\n"
	.string "Safe!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Wait, {PLAYER}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you secured {STR_VAR_3} straight Ws.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to dip! Safe!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you’re doing well.\p"
	.string "Actually, you are. I heard you\n"
	.string "won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That’s bare impressive!\n"
	.string "I’d better grind my team, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Yo, {PLAYER}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so sick, for real!\n"
	.string "I’d better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That’s quite the achievement.\n"
	.string "I need to work harder. Safe.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you’re the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You secured, what, {STR_VAR_3} matches in\n"
	.string "a row? Mad.\p"
	.string "You’re cold, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Word reached me about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at {STR_VAR_2}?\p"
	.string "That’s quite the story.\n"
	.string "Safe!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Yo, hello, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you’ve been doing bits.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I respect the energy, trust!\n"
	.string "Safe for now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard the news!\p"
	.string "Didn’t you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You’re an inspiration, for real!\n"
	.string "Safe!$"

MatchCall_BattleDomeText1::
	.string "Yo! {PLAYER}?\n"
	.string "Safe, this is {STR_VAR_1}!\l"
	.string "I heard the news, fam!\p"
	.string "You became the champ at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It’s sick! I need to step up my game!\n"
	.string "Laters!$"

MatchCall_BattleDomeText2::
	.string "Yo, it’s {STR_VAR_1}!\n"
	.string "I heard about your run!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That’s proper big! I wonder if I can\n"
	.string "reach champion levels too?$"

MatchCall_BattleDomeText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "WYS?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Secure another W next time!\n"
	.string "Link you soon!$"

MatchCall_BattleDomeText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champ\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you’re on your grind.\n"
	.string "I’ll try and keep up!$"

MatchCall_BattleDomeText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "straight at the {STR_VAR_2}.\p"
	.string "I’d better get with it, too!\n"
	.string "Link you soon!$"

MatchCall_BattleDomeText6::
	.string "Yo, {PLAYER}?\n"
	.string "{STR_VAR_1} here. You good?\p"
	.string "By the way, I heard you became\n"
	.string "the champ {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I’d better train my squad before\n"
	.string "you’re too far gone. Safe!$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That’s bare sick. By the way, caught\n"
	.string "any rare POKéMON lately?\p"
	.string "Oh, word?\n"
	.string "Aight, safe.$"

MatchCall_BattleDomeText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you’re doing well.\l"
	.string "Wait, obviously you are.\p"
	.string "I’ve heard you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I need to raise my team like you.\n"
	.string "See you again. Safe!$"

MatchCall_BattleDomeText9::
	.string "Yo, {PLAYER}, safe!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cold, for real!\n"
	.string "I’d better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That’s a proper achievement.\n"
	.string "I need to work harder. Safe.$"

MatchCall_BattleDomeText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you’re the boss of\n"
	.string "the {STR_VAR_2} now?\p"
	.string "You secured, what, {STR_VAR_3} titles\n"
	.string "now? Mad.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion like that?\p"
	.string "…Basically impossible?\n"
	.string "Well, laters!$"

MatchCall_BattleDomeText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You’ve won {STR_VAR_3} events at a place\n"
	.string "called {STR_VAR_2}?\p"
	.string "That’s quite the story, fam.\n"
	.string "Safe!$"

MatchCall_BattleDomeText13::
	.string "Yo, hello, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you’ve been doing bits.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I respect the energy, trust!\n"
	.string "Safe for now.$"

MatchCall_BattleDomeText14::
	.string "Oh, yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard the word!\p"
	.string "Didn’t you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You’re an inspiration, for real!\n"
	.string "Link you again!$"

MatchCall_BattlePikeText1::
	.string "Yo! {PLAYER}?\n"
	.string "Safe, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That’s proper sick!\n"
	.string "Safe!$"

MatchCall_BattlePikeText2::
	.string "Yo, it’s {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you rinsed {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I have to try bare harder now!\n"
	.string "Safe!$"

MatchCall_BattlePikeText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "WYS?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try and do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I’d better train the squad and\n"
	.string "try to keep up! Safe!$"

MatchCall_BattlePikeText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I’d better get with it, too!\n"
	.string "Link you soon!$"

MatchCall_BattlePikeText6::
	.string "Yo, {PLAYER}?\n"
	.string "{STR_VAR_1} here. You good?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I’d better raise my POKéMON before\n"
	.string "you pull further ahead. Safe!$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That’s wicked, no lie.\p"
	.string "Oh, check that rare POKéMON!\n"
	.string "Aight, safe.$"

MatchCall_BattlePikeText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you’re doing well.\l"
	.string "Wait, obviously you are.\p"
	.string "I’ve heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That’s proper impressive!\n"
	.string "I must raise my team like you.\l"
	.string "See you again. Safe!$"

MatchCall_BattlePikeText9::
	.string "Yo, {PLAYER}, safe!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cold, trust!\n"
	.string "I’d better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That’s a proper achievement.\n"
	.string "I need to work harder. Safe.$"

MatchCall_BattlePikeText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you’re the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That’s gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion like you?\p"
	.string "…Basically impossible?\n"
	.string "Aight, laters!$"

MatchCall_BattlePikeText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You’ve cleared {STR_VAR_3} rooms at a\n"
	.string "place called {STR_VAR_2}?\p"
	.string "That’s quite the story, fam.\n"
	.string "Safe!$"

MatchCall_BattlePikeText13::
	.string "Yo, hello, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you’ve been doing bits.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I respect the energy, for real!\n"
	.string "Laters.$"

MatchCall_BattlePikeText14::
	.string "Oh, yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard the news!\p"
	.string "Didn’t you clear {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You’re an inspiration, trust!\n"
	.string "Link you again!$"

MatchCall_BattlePyramidText1::
	.string "Yo! {PLAYER}?\n"
	.string "Safe, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, yeah?\p"
	.string "That’s proper sick!\n"
	.string "I should try that challenge myself.$"

MatchCall_BattlePyramidText2::
	.string "Yo, it’s {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you rinsed your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that’s actually mad!\n"
	.string "I’d better level up my team, too!$"

MatchCall_BattlePyramidText3::
	.string "Yo, {PLAYER}!\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "WYS?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even more next time!\n"
	.string "Link you soon!$"

MatchCall_BattlePyramidText4::
	.string "Yo, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I’d better work hard and try\n"
	.string "to keep up with your levels!$"

MatchCall_BattlePyramidText5::
	.string "Yo, {PLAYER}!\n"
	.string "It’s {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I’d better get with the grind, too!\n"
	.string "Link you soon!$"

MatchCall_BattlePyramidText6::
	.string "Yo, {PLAYER}?\n"
	.string "{STR_VAR_1} here. How you doing?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I’d better raise my squad before\n"
	.string "you pull further ahead. Safe!$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Sick. Were there any rare POKéMON\n"
	.string "up there?\p"
	.string "Nah? Allow it.\n"
	.string "Aight, safe.$"

MatchCall_BattlePyramidText8::
	.string "Yo {PLAYER}, WYS?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you’re doing well.\l"
	.string "Wait, obviously you are.\p"
	.string "I’ve heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That’s bare impressive!\n"
	.string "I must raise my team like you.\l"
	.string "See you again. Safe!$"

MatchCall_BattlePyramidText9::
	.string "Yo, {PLAYER}, safe!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cold, trust!\n"
	.string "I’d better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Yo, {PLAYER}, safe…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That’s a proper achievement.\n"
	.string "I need to work harder. Safe.$"

MatchCall_BattlePyramidText11::
	.string "Yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you’re the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That’s gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion like you?\p"
	.string "…Basically impossible?\n"
	.string "Laters!$"

MatchCall_BattlePyramidText12::
	.string "Yo, {PLAYER}.\n"
	.string "It’s me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You’ve won through {STR_VAR_3} floors in\n"
	.string "a place called {STR_VAR_2}?\p"
	.string "That’s quite the tale, fam.\n"
	.string "Safe!$"

MatchCall_BattlePyramidText13::
	.string "Yo, hello, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you’ve been doing bits.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I respect the energy, for real!\n"
	.string "Laters.$"

MatchCall_BattlePyramidText14::
	.string "Oh, yo, {PLAYER}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard the word!\p"
	.string "Didn’t you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You’re an inspiration, trust!\n"
	.string "Link you again!$"

MatchCall_Text_Mom1::
	.string "MOM: Your father and you…\n"
	.string "Everyone’s obsessed with POKéMON.\p"
	.string "What’s the hype even about?\p"
	.string "Me?\n"
	.string "I love the POKéMON that help me\l"
	.string "with my daily chores.$"

MatchCall_Text_Mom2::
	.string "MOM: Yo, {PLAYER}!\n"
	.string "Your dad is still locked away\l"
	.string "in the PETALBURG GYM.\p"
	.string "He comes home now and then.\n"
	.string "But he dips back to the GYM soon as\l"
	.string "he’s finished all the munch.\p"
	.string "I reckon losing to you was\n"
	.string "a proper blow to his pride!$"

MatchCall_Text_Mom3::
	.string "MOM: {PLAYER}…\n"
	.string "Don’t worry about me or the yard.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string " they're proper finished, honey!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, yo, {PLAYER}!\p"
	.string "I’ve been on a mad grind retraining\n"
	.string "since we met.\p"
	.string "I still need a bit of time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, you have to swing by\n"
	.string "for a rematch, for real!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Big congrats!\l"
	.string "I’ve been hearing about your bits!\p"
	.string "As for me, I need more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is finally ready!\p"
	.string "Pull up to RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we scrapped, {PLAYER},\l"
	.string "is a point of pride for me.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Yo, what's the word, {PLAYER}!\p"
	.string "I learned bare from the battle\n"
	.string "we had together.\p"
	.string "I’m gonna redo my training,\n"
	.string "then reopen the GYM.\p"
	.string "It’s gonna take a minute before\n"
	.string "I’m ready to run the GYM again.\p"
	.string "But once we're back, I want you\n"
	.string "to challenge us again, trust!$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Yo, {PLAYER}!\n"
	.string "Big congratulations!\p"
	.string "Word of your madness arrived\n"
	.string "on the tidal winds!\p"
	.string "Looks like I need to stay on\n"
	.string "my grind even more.\p"
	.string "It’s gonna take some time before\n"
	.string "I can reopen the GYM.\p"
	.string "But when I do, I want you to\n"
	.string "challenge us again!$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Yo, {PLAYER}!\n"
	.string "My GYM is ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another scrap!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}, I don’t think\n"
	.string "I’ll ever get tired of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, it’s you!\p"
	.string "After you left, I’ve been redoing\n"
	.string "my training from zero.\p"
	.string "I reckon I need a tiny bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You’ll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You’ve really done it, haven’t you?\n"
	.string "I’ve been hearing the word!\p"
	.string "It seems I still need to\n"
	.string "retrain some more.\p"
	.string "I reckon I need a tiny bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You’ll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, it’s you!\n"
	.string "My GYM is open!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power, fam!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we scrapped, I realized I’m\n"
	.string "actually bare immature.\p"
	.string "But I’m not finished yet!\p"
	.string "I’m gonna redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again, trust!$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Yo, {PLAYER}?\n"
	.string "Big congrats!\p"
	.string "Word of your success reached me\n"
	.string "like the heat of a volcano!\p"
	.string "Our training is going 10/10 right now.\p"
	.string "When the GYM is ready, a mark will\n"
	.string "pop up by my name in the\l"
	.string "MATCH CALL list. Safe!$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "The GYM is back open!\p"
	.string "Pull up to LAVARIDGE for a soak\n"
	.string "in the springs and a battle!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I’m certain you’re getting more\l"
	.string "legendary every time we speak.$"

MatchCall_Text_Winona1::
	.string "WINONA: Yo, {PLAYER}!\p"
	.string "Thanks to our battle, I finally\n"
	.string "clocked my weak points!\p"
	.string "When I reopen the GYM, I’m not\n"
	.string "taking any more Ls!$"

MatchCall_Text_Winona2::
	.string "WINONA: You’ve really done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… next time we scrap,\n"
	.string "it’s not gonna end the same way, trust.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in business!\p"
	.string "We’re waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Even if I take an L, my wings\l"
	.string "will never break.\p"
	.string "Just like how you never lost\n"
	.string "the vision for your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! You’re…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We’re back on the grind…\n"
	.string "LIZA: To reopen our GYM!\p"
	.string "TATE: When the GYM is ready…\n"
	.string "LIZA: When the GYM is ready…\p"
	.string "TATE: A mark will show by our name…\n"
	.string "LIZA: On the MATCH CALL list. Safe!$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congrats!\n"
	.string "LIZA: {PLAYER}, congrats!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still on the grind!\p"
	.string "TATE: We need a bit more time, but…\n"
	.string "LIZA: When the GYM is ready…\p"
	.string "TATE: A mark will show by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: The GYM is ready!\n"
	.string "LIZA: The GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, that battle we had…\n"
	.string "LIZA: Was an elite experience.\p"
	.string "TATE: It would be sick if…\n"
	.string "LIZA: We could all scrap again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}… was it?\p"
	.string "Our battle reminded me of when\n"
	.string "I first linked up with WALLACE.\p"
	.string "You might actually be a genius\n"
	.string "who can surpass him!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}…\n"
	.string "You’ve finally reached the top.\p"
	.string "My eye for talent is never wrong…\p"
	.string "I’d love another chance to link,\n"
	.string "since you’ve reached the peak of\l"
	.string "prestige and power. Safe!$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}…\p"
	.string "The SOOTOPOLIS GYM is finally\n"
	.string "back in operation.\p"
	.string "If you want to see me, you’re\n"
	.string "welcome to pull up anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}…\p"
	.string "Like the most elite track, our\n"
	.string "battles strike chords of mad\l"
	.string "inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to scrap with me\n"
	.string "again, pull up to the POKéMON\l"
	.string "LEAGUE whenever you like.\p"
	.string "I’ll always be here!\n"
	.string "I’ll be waiting! Safe.$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Yo, {PLAYER}!\p"
	.string "Why not swing back here again\n"
	.string "sometime?\p"
	.string "I want to see how much stronger\n"
	.string "the bond with your squad has grown.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Yo, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "lazy with your power?\p"
	.string "If you need to cool down your\n"
	.string "hype just a bit, pull up to\l"
	.string "the POKéMON LEAGUE…$"

MatchCall_Text_Drake::
	.string "DRAKE: That voice… {PLAYER}, yeah?\n"
	.string "You sound good, fam.\p"
	.string "I heard there’s a place called\n"
	.string "the BATTLE FRONTIER now for\l"
	.string "testing your skills.\p"
	.string "But if you want a real scrap,\n"
	.string "the POKéMON LEAGUE is the only\l"
	.string "place that matters.\p"
	.string "You feel me, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Yo, {PLAYER}.\n"
	.string "Have you met STEVEN?\p"
	.string "He’s actually…\n"
	.string "Incredibly skilled, no lie.\p"
	.string "But he’s a weird guy who\n"
	.string "hardly ever battles.\p"
	.string "He’d rather spend his time looking\n"
	.string "for rare stones.\p"
	.string "Probably digging in a cave or\n"
	.string "on some peak right now.\p"
	.string "But what even is a rare stone?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Yo, {PLAYER}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green POKéMON\n"
	.string "flying bare high in the sky.\p"
	.string "I…\n"
	.string "I’ve never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this a mad discovery or what?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Yo, {PLAYER}!\n"
	.string "I was just in PACIFIDLOG.\p"
	.string "I saw this massive green POKéMON\n"
	.string "flying across the sky.\p"
	.string "I’ve never seen anything that\n"
	.string "legendary in my life.\p"
	.string "I wish you were there to see it,\n"
	.string "{PLAYER}, for real.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1::
	.string "MAY: Yo, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him on the waves\l"
	.string "with PEEKO sometimes.\p"
	.string "He must still love the sea life.$"

MatchCall_Text_May2::
	.string "MAY: Yo, {PLAYER}!\p"
	.string "You know how small towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port\n"
	.string "of SLATEPORT doesn’t have one.\p"
	.string "When they finally build a GYM there,\n"
	.string "I’m applying for LEADER, no cap.$"

MatchCall_Text_May3::
	.string "MAY: Yo, {PLAYER}!\p"
	.string "Remember that guy called\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had that house there, yeah?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY! Mad.$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "links RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}, you good?\p"
	.string "I’m out on ROUTE 111 right now.\p"
	.string "I’m gonna get some rest at this\n"
	.string "old lady’s house.\p"
	.string "She lives just north of the desert.$"

MatchCall_Text_May6::
	.string "MAY: Yo, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say it just appears and\n"
	.string "vanishes like a ghost.\p"
	.string "I wish I could see it, for real.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}, yahoo!\n"
	.string "I’m on ROUTE 119 now.\p"
	.string "There’s a massive river here, and\n"
	.string "it’s raining bare hard.\p"
	.string "I’m soaked!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}, yo.\p"
	.string "MT. PYRE is a memorial for POKéMON\n"
	.string "that have passed on.\p"
	.string "Maybe that’s why it’s infested\n"
	.string "with so many GHOST-types!$"

MatchCall_Text_May9::
	.string "MAY: Yo, {PLAYER}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, near JAGGED PASS,\n"
	.string "I ran into some dodgy characters.\l"
	.string "The vibe was bare ugly!$"

MatchCall_Text_May10::
	.string "MAY: Yo, {PLAYER}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN found the\n"
	.string "SEAFLOOR CAVERN while he was\l"
	.string "out in his submarine.$"

MatchCall_Text_May11::
	.string "MAY: Yo, {PLAYER}!\n"
	.string "Don't you think it’s sick?\p"
	.string "Even if you don’t have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON move.\p"
	.string "And there’s more!\p"
	.string "There’s a move that actually\n"
	.string "lets you go underwater.$"

MatchCall_Text_May12::
	.string "MAY: Yo, {PLAYER}!\n"
	.string "Hope you’re doing bits!\p"
	.string "Have you ever been on the sea and\n"
	.string "found your path blocked?\p"
	.string "Try diving deep and following\n"
	.string "the trenches.\p"
	.string "When you reach the other side,\n"
	.string "just resurface. Easy!$"

MatchCall_Text_May13::
	.string "MAY: Yo, {PLAYER}!\p"
	.string "WYS? Are you filling up\n"
	.string "your POKéDEX?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "Like, three of them!\p"
	.string "I’d love to see even one, trust…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you’re almost at\n"
	.string " the end now, yeah?$"

MatchCall_Text_May15::
	.string "MAY: There isn’t a single TRAINER\n"
	.string "left in HOENN who doesn’t know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people we’re mates,\n"
	.string "they’re all bare surprised!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him on the waves\l"
	.string "with PEEKO sometimes.\p"
	.string "I guess he just loves\n"
	.string "the sea life, still.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "I don’t get how tiny towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "Makes no sense when a big port\n"
	.string "like SLATEPORT doesn't have one.\p"
	.string "When they finally build one there,\n"
	.string "I’m applying for LEADER, no cap.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Remember that guy called\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had that house there, yeah?\p"
	.string "Turns out his little brother\n"
	.string "lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY! Mad.$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: That voice… {PLAYER}?\p"
	.string "They named it RUSTURF TUNNEL\n"
	.string "because it links RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you even know that?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, what’s the word?\p"
	.string "Yo, I’m out on ROUTE 111 now.\p"
	.string "I’m gonna rest up at this old\n"
	.string "lady’s house north of the desert.\p"
	.string "If you’re around, you should\n"
	.string "swing by there, too. Safe!$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say it’s like a ghost—you\n"
	.string "can only see it sometimes.\p"
	.string "I’d love to see that, for real!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Who’s this? Oh, {PLAYER}?\n"
	.string "Guess what? I’m on ROUTE 119 now.\p"
	.string "There’s a massive river here, and\n"
	.string "it’s raining bare hard.\p"
	.string "I’m soaked to the bone!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial for POKéMON\n"
	.string "whose lives have ended.\p"
	.string "That’s probably why it’s infested\n"
	.string "with so many GHOST-types!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Yo, {PLAYER}.\p"
	.string "I was heading back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But near JAGGED PASS, I ran into\n"
	.string "some dodgy-looking characters.\p"
	.string "Those creeps…\n"
	.string "I’m pretty sure they were TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Yo, {PLAYER}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN found the\n"
	.string "SEAFLOOR CAVERN while he was\l"
	.string "out in his submarine expedition.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Yo, {PLAYER}!\n"
	.string "Don’t you think it’s sick?\p"
	.string "Even if you don’t have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON move.\p"
	.string "And there’s a move that lets you\n"
	.string "actually travel to the sea floor.\p"
	.string "Man, POKéMON are elite!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Yo, {PLAYER}!\n"
	.string "How you holding up?\p"
	.string "Ever found your path blocked\n"
	.string "while you were on the sea?\p"
	.string "Try diving deep and following\n"
	.string "the trenches at the bottom.\p"
	.string "When you reach the other side,\n"
	.string "just resurface. Simple, fam!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "WYS? Filling up that POKéDEX\n"
	.string "successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And not just one—three!\p"
	.string "I’d love to catch even one, trust…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the word!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Sick!\p"
	.string "You’re getting bare close now!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: There isn’t a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that we’re\n"
	.string "mates, they get bare envious!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I’ve been getting healthier and\n"
	.string "finding my fitness.\p"
	.string "I hope I can become an elite\n"
	.string "TRAINER like you soon, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, hello!\p"
	.string "Since RUSTURF TUNNEL opened\n"
	.string "up, WANDA’s been so happy!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle’s yard in\n"
	.string "VERDANTURF without saying a word.\p"
	.string "I wonder if he’s fuming with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is sick!\p"
	.string "When I have my POKéMON with me,\n"
	.string "everyone says hi!\p"
	.string "It’s like everyone’s getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? It’s amazing!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I’ve got talent…\p"
	.string "Oh, but I shouldn't get a big\n"
	.string "head about it!\p"
	.string "After all, the POKéMON is the\n"
	.string "one who deserves the praise!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV’s service area…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I’m on an adventure with\n"
	.string "my very own squad…\p"
	.string "{PLAYER}…\n"
	.string "Safe for everything…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Yo, {PLAYER}!\p"
	.string "You know how POKéMON are found\n"
	.string "absolutely everywhere?\p"
	.string "Like in the mountains, the sea,\n"
	.string "or just in the long grass?\p"
	.string "Just like POKéMON, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to rush\n"
	.string "everywhere, too. Bare busy!$"

MatchCall_Text_Scott2::
	.string "SCOTT: I’m on ROUTE 119 right now.\n"
	.string "It’s teeming with TRAINERS!\p"
	.string "It’s also overgrown with long grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "is bare ticklish, man!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Yo, yo, {PLAYER}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE yet?\p"
	.string "The place is a memorial for POKéMON\n"
	.string "that have passed away.\p"
	.string "It’s somewhere every TRAINER\n"
	.string "should climb at least once.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Yo, {PLAYER}!\p"
	.string "I’ve been hearing about these weird\n"
	.string "gangs causing a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were called.\p"
	.string "I’d imagine there are some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they’re just thugs…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, yo, {PLAYER}.\p"
	.string "Reckon there are tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can’t go check for myself.\n"
	.string "I can’t swim, for one.\l"
	.string "And I don’t even raise POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Yo, yo, {PLAYER}!\p"
	.string "You know you can challenge\n"
	.string "the POKéMON LEAGUE once you’ve\l"
	.string "bagged all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION is a real possibility.\p"
	.string "But did you know?\n"
	.string "There’s somewhere even better.\p"
	.string "But, that’s all I’m saying\n"
	.string "for now, fam.\p"
	.string "It’s something to look\n"
	.string "forward to.\p"
	.string "When you’ve rinsed the LEAGUE\n"
	.string "and made the HALL OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV’s service area…$"

MatchCall_Text_Norman1::
	.string "DAD: In RUSTBORO, there’s a man\n"
	.string "who goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you’re in the area, you should\n"
	.string "pay him a visit. Safe.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Bit by bit, but also\n"
	.string "very surely, you’re getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the further\n"
	.string "you fly from Mother and me…\p"
	.string "This feeling is hard to explain, kid.$"

MatchCall_Text_Norman3::
	.string "DAD: I see…\n"
	.string "You’ve bagged four GYM BADGES…\p"
	.string "There’s no avoiding it now.\n"
	.string "We scrap like I promised.\p"
	.string "Pull up anytime.\n"
	.string "We’ll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! You’d better visit\n"
	.string "Mother every once in a while.\p"
	.string "I’m staying here to double down\n"
	.string "on my training.\p"
	.string "The way of the battle is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, yo, {PLAYER}!\p"
	.string "What’s that? MAGMA EMBLEM?\n"
	.string "I don’t know about that.\p"
	.string "But with a name like that, it’s\n"
	.string "probably linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would’ve thought you’d become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Aight!\n"
	.string "I won’t be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I’m gonna be the one\n"
	.string "challenging you to a battle.\p"
	.string "I’m waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher can you soar?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Yo, {PLAYER}!\p"
	.string "Have you been to MAUVILLE\n"
	.string "already?\p"
	.string "You should hit the BIKE SHOP\n"
	.string "and grab a MACH BIKE.\p"
	.string "Then, try exploring GRANITE\n"
	.string "CAVE properly.\p"
	.string "You might find something mad\n"
	.string "down there.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Yo, {PLAYER}!\p"
	.string "I’ve met bare different\n"
	.string "TRAINERS on my travels.\p"
	.string "But you’re one of a kind, trust.\n"
	.string "You’re not like anyone else.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Yo, {PLAYER}!\p"
	.string "When you’re out on an adventure\n"
	.string "with your squad, WYS?\p"
	.string "Do you see them as elite\n"
	.string "partners?\p"
	.string "Or just fun companions to\n"
	.string "pass the time with?\p"
	.string "How you think about it changes\n"
	.string "the whole vibe of your journey.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Hello?\n"
	.string "{PLAYER}?\p"
	.string "I’m caught up in some madness\n"
	.string "at the SPACE CENTER.\p"
	.string "Sorry, I can’t talk now.\n"
	.string "Laters!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}!\p"
	.string "No need to talk.\n"
	.string "The time for talking is peak.\p"
	.string "You’ve gotta believe in yourself\n"
	.string "and do what’s right.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN doesn't seem to be picking\n"
	.string "up the call…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}… Huge congrats\n"
	.string "on making the HALL OF FAME.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can link up again\n"
	.string "somewhere soon. Safe!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Oh, {PLAYER}!\n"
	.string "I’ve already heard about you!\p"
	.string "Looks like your POKéNAV’s been\n"
	.string "upgraded with MATCH CALL.\p"
	.string "Well, I should sign up, too!\p"
	.string "That way, I can check your\n"
	.string "POKéDEX even while you’re\l"
	.string "out on the grind.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Registered PROF. BIRCH\n"
	.string "in the POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: When you’ve got the\n"
	.string "POKéDEX and POKéNAV, the grind\l"
	.string "becomes bare fun, eh?$"

MatchCall_Text_MrStone1::
	.string "MR. STONE: Oh? {PLAYER}!\p"
	.string "Since you called, the POKéNAV\n"
	.string "must be working 10/10!\p"
	.string "Other people will be registered,\n"
	.string "so try calling them, too!\p"
	.string "Safe! Safe!\n"
	.string "You seem proper happy!\p"
	.string "Hm…\n"
	.string "How do I know that?\p"
	.string "Because I’m looking down at\n"
	.string "you from my office window!\p"
	.string "Wahahaha!\n"
	.string "See you again!$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Oh? {PLAYER}!\p"
	.string "What’s wrong? Have you forgotten\n"
	.string "about that little job of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, take the parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, right?\p"
	.string "Now, I’m a bare busy PRESIDENT,\n"
	.string "so I’ve gotta dip! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "MR. STONE: Oh! {PLAYER}!\p"
	.string "Ah, so you finally linked STEVEN!\n"
	.string "I’d better reward you, then!\p"
	.string "When you’re back in RUSTBORO,\n"
	.string "come see me at my office.\p"
	.string "I’ll be waiting for you. Safe!$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Oh! {PLAYER}!\p"
	.string "Did you know DEVON was the one\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "But we shut it down to protect\n"
	.string "the POKéMON in the area.\p"
	.string "It’s a no-brainer, really.\p"
	.string "Protecting the POKéMON is more\n"
	.string "important than our own convenience.$"

MatchCall_Text_MrStone5::
	.string "MR. STONE: Yo, yo, {PLAYER}!\p"
	.string "I heard from someone in PETALBURG\n"
	.string "that you’re NORMAN’s kid!\p"
	.string "No wonder you’re doing bits out there!$"

MatchCall_Text_MrStone6::
	.string "MR. STONE: WYS?\p"
	.string "You actually scrapped your dad\n"
	.string "and won the battle?\p"
	.string "That is mad!\p"
	.string "I had no idea I was mates with\n"
	.string "someone so legendary! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hello!\n"
	.string "This is DEVON CORPORATI…\l"
	.string "Oh, yo, {PLAYER}!\p"
	.string "The PRESIDENT was here a bit\n"
	.string "ago, but he’s gone out.\p"
	.string "He’s bare busy, but you seem\n"
	.string "just as busy yourself, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Huh? …WYS?\p"
	.string "GROU… Yeah? …DON?\p"
	.string "The signal's moving mad…\n"
	.string "…can’t hear…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Huh? …WYS?\p"
	.string "Seafloo… Yeah? …Cavern…?\p"
	.string "You’re breaking up…\n"
	.string "…can’t hear you…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. STONE: {PLAYER}! It’s me!\p"
	.string "You’ve been involved in all sorts\n"
	.string "of madness, but I’ve been too busy\l"
	.string "to know exactly what!\p"
	.string "But yo, keep walking the path\n"
	.string "you believe in.\p"
	.string "I’ve always got your back!\n"
	.string "Take care!$"

MatchCall_Text_MrStone11::
	.string "MR. STONE: … … … … … …\n"
	.string "Is that {PLAYER}?\p"
	.string "Your voice sounds so confident now,\n"
	.string "I didn’t recognize you for a sec!\p"
	.string "Hm! You have to pull up to DEVON\n"
	.string "again sometime! Safe!$"

