MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move is a one-time deal.\n"
	.string "You sure you’re ready?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My POKéMON is a straight boss!\n"
	.string "Easily the flyest in the game!\p"
	.string "I was moving with bare swagger and\n"
	.string "lipping off until the CHAIRMAN\l"
	.string "properly put me in my place.\p"
	.string "That definitely killed my vibe.\p"
	.string "If you want, I’ll teach the move\n"
	.string "SWAGGER to one of your squad.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, nah? You’ve got zero\n"
	.string "spirit, man.$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Safe, which POKéMON wants to\n"
	.string "learn how to SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "I’ll just hype my POKéMON from now\n"
	.string "on without being so extra.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know you can head that way\n"
	.string "for ages and never have to\l"
	.string "change your line?\p"
	.string "I reckon I could even roll\n"
	.string "all the way there.\p"
	.string "Think your POKéMON wants to\n"
	.string "get rolling, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you’re feeling it.$"

MoveTutor_Text_RolloutDeclined:
	.string "No need to be shy, man.\n"
	.string "Let’s roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, safe! It’d be sick if\n"
	.string "the POKéMON looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling in the grass is a proper vibe.\n"
	.string "Come on, let’s roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There’s a move that gets bare strong\n"
	.string "if you keep spamming it.\p"
	.string "It’s a BUG-type move, and it is\n"
	.string "actually sick.\p"
	.string "It’s called FURY CUTTER.\n"
	.string "Want me to teach the squad?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We’re just not on the same wave.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Get in!\n"
	.string "Show me which POKéMON I’m teaching.$"

MoveTutor_Text_FuryCutterTaught:
	.string "It’s a proper rush seeing if\n"
	.string "the move keeps landing!$"

MoveTutor_MimicTeach:
	.string "Yo, young blood!\p"
	.string "I’m a younger too, but I mimic\n"
	.string " how the OGs in this town\l"
	.string "talk and move.\p"
	.string "What’s the word? You want\n"
	.string "me to teach your lot how to\l"
	.string "use the move MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Rah, peak! I really wanted to teach\n"
	.string "MIMIC to your squad!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! Say no more!\n"
	.string "Let’s see the POKéMON\l"
	.string "you want me to train.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC is a move with bare depth.\p"
	.string "Reckon you can pull it off as\n"
	.string "smoothly as me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want bare things, man!\n"
	.string "But I’ve spent all my dough…\p"
	.string "Wouldn't it be sick if there was\n"
	.string "a cheat code to make cash appear\l"
	.string "just by waggling a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "No cash, but they’ll waggle a finger\n"
	.string "like a boss. Yeah?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Calm. I’ll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Safe! I’ll teach it!\n"
	.string "Which POKéMON is the one?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of mad\l"
	.string "things happen.\p"
	.string "Imagine if we could do that, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife uses HIDDEN\n"
	.string "POWER just to stay awake.\p"
	.string "She should just nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to\n"
	.string "SLEEP TALK instead. You in?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, a kid with taste!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I’ve never once got my wife’s\n"
	.string "coin trick right.\p"
	.string "I’d be gassed if I got it right\n"
	.string "even while I SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I look at the roads from up\n"
	.string "here on the roof…\p"
	.string "I think how sick it would be\n"
	.string "if there were more than one of me\l"
	.string "to live out all sorts of lives.\p"
	.string "Obviously it’s not possible.\n"
	.string "Giggle…\p"
	.string "I know! You want a POKéMON to\n"
	.string "learn how to use SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, nah?\p"
	.string "A POKéMON can make a proper clone\n"
	.string "of itself with that, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON wants me to\l"
	.string "teach them SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We only live once, so we gotta\n"
	.string "live it to the absolute max!\p"
	.string "Hope you find your vibe, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can’t do this anymore, man!\p"
	.string "It’s proper peak!\p"
	.string "I’m a FIGHTING-type TRAINER,\n"
	.string "but I can’t touch the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What? Don't look at me like that!\n"
	.string "I’m only hitting the floor!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Rah! You’re even mocking me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Wait, you actually do? You’re a legend!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I need you to smash the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is actually\n"
	.string "a proper hero.\p"
	.string "But that means I’ve got bare rivals\n"
	.string "trying to get his attention.\p"
	.string "His charm is like a DOUBLE-EDGE.\n"
	.string "I didn't even get a look-in.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you’re airing me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Safe, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I’m done living for love!\n"
	.string "I’m gonna become a beast!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don’t plan on being stuck in the\n"
	.string "sticks like this forever.\p"
	.string "You watch, I’m gonna hit the city\n"
	.string "and become a massive name.\p"
	.string "Seriously, my popularity is gonna\n"
	.string "properly EXPLODE!\p"
	.string "Since you heard that, I’ll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You’re airing me just because\n"
	.string "I live in the countryside?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! EXPLOSION it is!\n"
	.string "Which POKéMON wants to go boom?$"

MoveTutor_Text_ExplosionTaught:
	.string "I’ve taught POKéMON how to blow up\n"
	.string "for ages, but I haven’t made my\l"
	.string "own EXPLOSION yet…\p"
	.string "Maybe it’s 'cause deep down,\n"
	.string "I’d actually rather stay here…$"

