gOtherText_NewName::
	.string "CUSTOM$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "I’m gonna show you how the buttons\n"
	.string "work so you can pattern up properly.$"

gControlsGuide_Text_DPad::
	.string "Moves the main character.\n"
	.string "Also used to choose headings\n"
	.string "and navigate through the data.$"

gControlsGuide_Text_AButton::
	.string "Used to confirm a choice, check\n"
	.string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
	.string "Used to exit, low it, cancel a\n"
	.string "choice, or back out of a mode.$"

gControlsGuide_Text_StartButton::
	.string "Press this button to open the\n"
	.string "MENU and check your motive.$"

gControlsGuide_Text_SelectButton::
	.string "Used to shift items or use\n"
	.string "a registered item quickly.$"

gControlsGuide_Text_LRButtons::
	.string "If things are looking peak and\n"
	.string "you need a hint on what to do,\n"
	.string "hit the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Now tell me. Are you a big man?\n"
	.string "Or are you a girl?$"

gPikachuIntro_Text_Page1::
	.string "In the world you’re about to enter,\n"
	.string "you’re the top boy on a serious\n"
	.string "adventure.\n"
	.string "\n"
	.string "Link with people and check your\n"
	.string "surrounds, from the ends to the\n"
	.string "cunch. Get the intel from everyone.$"

gPikachuIntro_Text_Page2::
	.string "New paths open when you help people,\n"
	.string "overcome challenges, and solve the\n"
	.string "mad mysteries you find.\n"
	.string "\n"
	.string "At times, opps will challenge you\n"
	.string "or wild creatures will attack.\n"
	.string "Don't look shook—keep pushing on.$"

gPikachuIntro_Text_Page3::
	.string "Through your journey, we hope you\n"
	.string "interact with real ones and achieve\n"
	.string "personal growth. That's the objective.\n"
	.string "\n"
	.string "Press the A Button, and let your\n"
	.string "legend begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Wagwan! Glad to meet you!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People out here refer to me\n"
	.string "as the POKéMON PROFESSOR.\p$"

gOakSpeech_Text_ThisWorld::
	.string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…is inhabited far and wide by\n"
	.string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "For some people, POKéMON are pets.\n"
	.string "Others use them for battling.\p"
	.string "As for myself…\p"
	.string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "But first, tell me about yourself.\n"
	.string "Pattern me up on the basics.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Let's begin with your name.\n"
	.string "What do you go by?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Safe…\n"
	.string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "This is my grandson.\p"
	.string "He’s been your rival since you both\n"
	.string "were little yutes.\p"
	.string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "Truss! I remember now!\n"
	.string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "Your very own POKéMON legend is\n"
	.string "about to unfold!\p"
	.string "A world of dreams and adventure\n"
	.string "awaits! Keep on the grind!$"

