gText_ObtainedTheItem::
	.string "Copped the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BAG is rammed…$"

gText_PutItemInPocket::
	.string "{PLAYER} tucked the {STR_VAR_2}\n"
	.string "into the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Peak!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} stashed the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
	.string "Copped the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Peak! There’s no space left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was sent\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Copped {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} stashed the COINS in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Peak!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Peak!\n"
	.string "There’s nothing to stash them in…$"

