Text_BootUpPC:
	.string "{PLAYER} logged into the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC are you accessing?$"

gText_AccessedSomeonesPC::
	.string "Logged into SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System active.$"

gText_AccessedPlayersPC::
	.string "Logged into {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Logged into LANETTE'S PC.$"

gText_AccessedBillsPC::
	.string "Logged into BILL'S PC.$"

