gText_WouldYouLikeToRestYourPkmn::
	.string "Wagwan, babes! Welcome to my\n"
	.string "POKéMON CENTER.\p"
	.string "Your squad’s looking a bit dead,\n"
	.string "let me get them back to 100%.\p"
	.string "You want me to pattern them up?$"

gText_IllTakeYourPkmn::
	.string "Safe, hand over the squad.\n"
	.string "I’ll have them right in a sec.$"

gText_RestoredPkmnToFullHealth::
	.string "Thanks for waiting, lovely.\p"
	.string "Your squad is looking leng again\n"
	.string "and ready for the motive.$"

gText_WeHopeToSeeYouAgain::
	.string "Don't let them scuff your creps!$"

gText_WelcomeCutShort::
	.string "Wagwan, babes! Welcome to my\n"
	.string "POKéMON CENTER.\p"
	.string "Your squad’s looking a bit dead,\n"
	.string "let me get them back to 100%.\p"
	.string "Do you want to…$"

gText_NoticesGoldCard::
	.string "Wait… hold on… that card…\n"
	.string "Is that actually the GOLD CARD?!\p"
	.string "The drip on that is unreal!\n"
	.string "The stars are sparkling, truss!\p"
	.string "I’ve seen bare yutes with the\n"
	.string "SILVER CARD, but {PLAYER}, you’re\l"
	.string "the first real one I’ve seen\l"
	.string "stepping correct with the GOLD!\p"
	.string "Say no more, {PLAYER}. It’s a literal\n"
	.string "honor to pattern up your squad!$"

gText_YouWantTheUsual::
	.string "Always a vibe seeing you, {PLAYER}!\n"
	.string "You want the usual fix-up, yeah?$"

gText_IllTakeYourPkmn2::
	.string "Safe, hand over the squad.\n"
	.string "I’ll have them right in a sec.$"

gText_ThankYouForWaiting::
	.string "Thanks for waiting, babes.$"

gText_WeHopeToSeeYouAgain2::
	.string "Keep on the grind, darling!$"

