gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Yo, {PLAYER}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX grind is coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON yet. Don't be a wasteman.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've copped {STR_VAR_2} species…$"

gBirchDexRatingText_LessThan10::
	.string "Step into the tall grass more.\n"
	.string "You need to look more carefully.$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But the grind gets harder.$"

gBirchDexRatingText_LessThan30::
	.string "Some POKéMON only pull up in\n"
	.string "certain areas. Don't be lazy.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it needs more volume, but\n"
	.string "this is looking like a real\l"
	.string "POKéDEX now. Rating.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along quite nice.\n"
	.string "Keep up the effort, real one.$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any RODS?\n"
	.string "There’s bare POKéMON in the sea.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching them,\n"
	.string "why not evolve them, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is gonna be a legendary\n"
	.string "POKéDEX. Trust, I can feel it.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many? Your\n"
	.string "talent is serious!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear some POKéMON only pull up\n"
	.string "in that spot.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally hit the 100 mark.\p"
	.string "This POKéDEX is lookin' serious!$"

gBirchDexRatingText_LessThan120::
	.string "There might be POKéMON hidden\n"
	.string "where you use ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should link with your bredrins\n"
	.string "and trade to get more species.$"

gBirchDexRatingText_LessThan140::
	.string "I’ve heard of POKéMON that evolve\n"
	.string "when they truly rate their TRAINER.$"

gBirchDexRatingText_LessThan150::
	.string "Mad ting! I had no idea there were\n"
	.string "this many species in HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Sometimes POKéMON appear in\n"
	.string "outbreaks like a massive motive.\p"
	.string "Don't miss those opportunities.$"

gBirchDexRatingText_LessThan170::
	.string "Man can get a proper idea about\n"
	.string "the HOENN region just by\l"
	.string "looking through your POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "I'd say you're already a PROFESSOR\n"
	.string "level researcher. Top boy status.$"

gBirchDexRatingText_LessThan190::
	.string "With a POKéDEX this complete,\n"
	.string "you're a real pro at the game!$"

gBirchDexRatingText_LessThan200::
	.string "You're so close to finishing.\n"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Madness! Congratulations!\n"
	.string "Your POKéDEX is 100% complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide scale…\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've copped {STR_VAR_2} of them…$"

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Safe to see you!\n"
	.string "How is the POKéDEX grind going?\p"
	.string "Here, let me see your progress.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The work you've put into your\n"
	.string "POKéDEX so far is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have bare work to do.\p"
	.string "Check every patch of grass and\n"
	.string "pattern up your collection!$"

PokedexRating_Text_LessThan20::
	.string "It looks like you're finally\n"
	.string "stepping correct!\p"
	.string "I’ve given my AIDE a FLASH HM.\n"
	.string "Make sure you link up and get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX needs more volume!\n"
	.string "It’s looking a bit dead still.\p"
	.string "Try to catch different species!$"

PokedexRating_Text_LessThan40::
	.string "Good, I see you're on the grind!\p"
	.string "I’ve given my AIDE an ITEMFINDER.\n"
	.string "Be sure to go collect that!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along\n"
	.string "properly! Nice work.\p"
	.string "I’ve given my AIDE an AMULET COIN.\n"
	.string "Don't forget to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species! Legendary status.\p"
	.string "I’ve given my AIDE an EXP. SHARE.\n"
	.string "Make sure you go grab it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into a\n"
	.string "respectable POKéDEX. I rate that!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll find even more\n"
	.string "POKéMON if you go fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… you\n"
	.string "really like the grind, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed! Completing this\n"
	.string "must have been a mad ting!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how elite you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms?\n"
	.string "Serious work! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "pattern up the rest!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You're a real pro at this now!$"

PokedexRating_Text_LessThan150::
	.string "Say no more! You're basically\n"
	.string "the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is 100% complete!\n"
	.string "Madness! Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I’m looking forward to seeing\n"
	.string "you fill that NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally finished the\n"
	.string "whole POKéDEX!\p"
	.string "It's magnificent! Truly, this\n"
	.string "is a legendary feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Respect, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is the POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I already know, but I\n"
	.string "love seeing the progress anyway!\p"
	.string "Let's see…$"

