Questionnaire_Text_FillOut::
	.string "There's a questionnaire here.\n"
	.string "You wanna pattern us up with some info?$"

Questionnaire_Text_ThankYou::
	.string "Respect for taking the time to\n"
	.string "fill out the form.\p"
	.string "We’ll use your intel to keep the\n"
	.string "future motives looking sharp.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Wagwan! Hold on…\n"
	.string "You know the code?\p"
	.string "That means you’re in the loop\n"
	.string "about the MYSTERY GIFT.\p"
	.string "From now, I’m gonna make sure you\n"
	.string "receive those MYSTERY GIFTS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Once you save your progress, you can\n"
	.string "access the MYSTERY GIFT motive.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Wagwan! Hold on…\n"
	.string "You know the code?\p"
	.string "That means you’re in the loop\n"
	.string "about the MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Once you save your progress, you can\n"
	.string "access the MYSTERY EVENT motive.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Respect for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}, yeah?\n"
	.string "I’ve got a ticket here for you.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "It’s for the port over in\n"
	.string "LILYCOVE CITY.\p"
	.string "Why not head over there and see\n"
	.string "what the motive is about?$"

