	.align 2
gText_ConfirmSave::
	.string "You wanna lock in your progress\n"
	.string "and save the game?$"

gText_AlreadySavedFile::
	.string "There’s already a file saved.\n"
	.string "Is it safe to overwrite it?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON’T CUT THE POWER.$"

gText_PlayerSavedGame::
	.string "{PLAYER} locked in the progress.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There’s a different game file\n"
	.string "already on this system.\p"
	.string "If you save now, that other yute's\n"
	.string "adventure and squad will be\l"
	.string "gone forever—it’s peak.\p"
	.string "You sure you want to save now\n"
	.string "and dead the other file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "The memory is moving bookey.\n"
	.string "Exchange the backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON’T CUT THE POWER.$"

