@ Trainer 0: The Secret Spot Scout
SecretBase_Text_Trainer0Intro:
	.string "You copped a SECRET BASE yet?\p"
	.string "I scouted every corner of the ends\n"
	.string "before I picked this spot.\p"
	.string "Since you’ve pulled up, you want\n"
	.string "to test the squad?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Say no more!\n"
	.string "We’re coming for you!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Huh?\n"
	.string "Oh, you’re not ready...$"

SecretBase_Text_Trainer0Defeated::
	.string "Madness! You’re way too strong!\n"
	.string "About my loss... keep it quiet, yeah?$"

SecretBase_Text_Trainer0PostBattle:
	.string "How you rating the SECRET BASE?\n"
	.string "Link me again tomorrow.$"

SecretBase_Text_Trainer0PreChampion:
	.string "You copped a SECRET BASE yet?\p"
	.string "I scouted every corner of the ends\n"
	.string "before I picked this spot.\p"
	.string "Feel free to hang out!$"

@ Trainer 5: The Loyal Local
SecretBase_Text_Trainer5Intro:
	.string "There’s bare places to set up a\n"
	.string "SECRET BASE out here.\p"
	.string "But I rate this spot the most.\n"
	.string "It’s a vibe, innit?\p"
	.string "Want to see if my squad is serious?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Safe, let’s get it!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh...\n"
	.string "You’re moving busy, that’s fine.$"

SecretBase_Text_Trainer5Defeated::
	.string "Peak... that’s an L for me...\n"
	.string "But don’t tell the mandem!\l"
	.string "Keep it on the low!$"

SecretBase_Text_Trainer5PostBattle:
	.string "If you’re in the ends again,\n"
	.string "make sure you pull up.$"

@ Trainer 1: The Gatekeeper
SecretBase_Text_Trainer1Intro:
	.string "This spot is legendary.\n"
	.string "It’s always taken.\p"
	.string "Oh! You were thinking about\n"
	.string "trying to claim this area?\p"
	.string "Tell you what, you can have the\n"
	.string "spot if you can violate my squad.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Safe!\n"
	.string "I’m defending my ends!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Huh? Is that right?\n"
	.string "You don't think you can handle it?$"

SecretBase_Text_Trainer1Defeated::
	.string "I’m finished!\n"
	.string "I surrender!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Fine, when I move out one day,\n"
	.string "this spot is yours.$"

@ Trainer 6: The Secret Researcher
SecretBase_Text_Trainer6Intro:
	.string "Welcome to the Lab.\p"
	.string "I’m researching secret battle\n"
	.string "tactics away from the feds.\p"
	.string "Want to see if my tech is serious?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "I’m going all out, truss me!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Another motive, then!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm... I’ve still got bare to learn.\n"
	.string "I need to pattern up my research.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Respect for the battle.\n"
	.string "Pull up again tomorrow.$"

@ Trainer 2: The Social Host
SecretBase_Text_Trainer2Intro:
	.string "A big mansion is dead, I prefer\n"
	.string "this kind of hideout.\p"
	.string "It’s safe because all kinds of real\n"
	.string "ones come visit me.\p"
	.string "So, you want a battle?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "That’s the spirit!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "When you’re ready to step, holla!$"

SecretBase_Text_Trainer2Defeated::
	.string "Ayy! Done in!\n"
	.string "Still a serious motive though!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Anyway, I need to go cop some new\n"
	.string "decorations and garms for the base.\p"
	.string "I want this spot to be elite for\n"
	.string "everyone who visits.$"

@ Trainer 7: The Shopaholic
SecretBase_Text_Trainer7Intro:
	.string "I literally live for shopping for\n"
	.string "new base decorations.\p"
	.string "But I keep the squad looking\n"
	.string "just as peng.\p"
	.string "Would you be so kind as to test\n"
	.string "my POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Respect.\n"
	.string "Shall we begin?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "That’s proper peak...$"

SecretBase_Text_Trainer7Defeated::
	.string "I concede...$"

SecretBase_Text_Trainer7PostBattle:
	.string "That was a serious vibe!\n"
	.string "Time to go shopping again.$"

@ Trainer 3: The Low-Key Hider
SecretBase_Text_Trainer3Intro:
	.string "Some yutes hide their bases in\n"
	.string "bookey places.\l"
	.string "They just trying to lie low?\p"
	.string "Since you found the link, how about\n"
	.string "we have a battle?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "I’m not going down easily!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh... you looking shook from\n"
	.string "searching for this place?$"

SecretBase_Text_Trainer3Defeated::
	.string "I’m dead...$"

SecretBase_Text_Trainer3PostBattle:
	.string "Where’s your ends at?\n"
	.string "I should pull up to your base.$"

@ Trainer 8: The Decor Racer
SecretBase_Text_Trainer8Intro:
	.string "I heard you can cop decorations\n"
	.string "in bare different ways.\p"
	.string "We should race to see who gets\n"
	.string "the most legendary setup!\p"
	.string "In the meantime, you want to step?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "This is my base.\n"
	.string "I can’t take an L here!$"

SecretBase_Text_Trainer8Defeated::
	.string "Huh?\n"
	.string "Did I just get smoked?$"

SecretBase_Text_Trainer8PostBattle:
	.string "I won’t lose at collecting garms.\n"
	.string "Visit me again!$"

@ Trainer 4: The Dedicated Grinder
SecretBase_Text_Trainer4Intro:
	.string "I found a spot I rate, and I did it\n"
	.string "up with my favorite setup.\p"
	.string "I grind with my favorite POKéMON\n"
	.string "to get the squad stronger.\p"
	.string "That’s the motive.\n"
	.string "Want to battle?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Show me if you’re a real one!$"

SecretBase_Text_Trainer4Defeated::
	.string "I see your level now. Respect.$"

SecretBase_Text_Trainer4PostBattle:
	.string "We can both reach the top.\n"
	.string "Keep on the grind!$"

@ Trainer 9: The Taste-Maker
SecretBase_Text_Trainer9Intro:
	.string "You can tell if someone is a wasteman\n"
	.string "by how they decorate their base.\p"
	.string "What you thinking of my taste?\n"
	.string "You look speechless.\p"
	.string "Want to see my taste in battling?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "No holding back, truss me!$"

SecretBase_Text_Trainer9Defeated::
	.string "You’re supremely talented!\n"
	.string "Your power is limitless... mad ting.$"

SecretBase_Text_Trainer9PostBattle:
	.string "What you thinking of my style?\n"
	.string "I’ll keep polishing it!$"

