ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "You planning on heading deep\n"
	.string "inside there?\p"
	.string "How about bringing me back some\n"
	.string "SHOAL SALT and SHOAL SHELLS?\p"
	.string "I can pattern you up something serious\n"
	.string "if you bring me the ingredients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "If you bring me four of each—the\n"
	.string "SALT and the SHELLS—I can craft\l"
	.string "a SHELL BELL for you...\p"
	.string "You can find those ingredients\n"
	.string "every day if you're on the grind.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Yo, safe! SHOAL SALT and SHOAL SHELLS!\n"
	.string "And you’ve got the full amount, too!\p"
	.string "You want me to pattern up\n"
	.string "a SHELL BELL for you now?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Say no more! I'll make that\n"
	.string "SHELL BELL for you right away.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Truss! Done!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Let a POKéMON hold on to that.\n"
	.string "They’ll rate it for sure.\p"
	.string "The chime on that SHELL BELL...\n"
	.string "it’s a mad ting, proper sublime!\p"
	.string "The ingredients pull up every day,\n"
	.string "so I can craft you more whenever.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh... is that how it is?\n"
	.string "I was ready to craft that for you...$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Your bag is way too rammed.\n"
	.string "I can't give it to you like that.\p"
	.string "Pattern up your inventory and\n"
	.string "come back for the SHELL BELL.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "There was some SHOAL SALT here.\n"
	.string "But the spot is dead now.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "There was a SHOAL SHELL here.\n"
	.string "But the spot is dead now.$"

