Route102_Text_CalvinIntro:
	.string "If you’re rolling with POKéMON, you’re\n"
	.string "an official TRAINER in my books!\l"
	.string "You can't say no to this challenge!$"

Route102_Text_CalvinDefeated:
	.string "Allow it, I lost…\n"
	.string "I should’ve leveled the squad more…$"

Route102_Text_CalvinPostBattle:
	.string "Listen, you. If you were moving that\n"
	.string "strong, you should’ve told me before!$"

Route102_Text_CalvinRegister:
	.string "I’ve been on the grind since we\n"
	.string "last crossed paths.\p"
	.string "I need a run-back, so let me\n"
	.string "register you in the POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "I need the rematch. Add me on\n"
	.string "the POKéNAV real quick?$"

Route102_Text_CalvinRematchIntro:
	.string "Ever since I took that L, I’ve been\n"
	.string "desperately training the team.\l"
	.string "You can't duck this challenge!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, I lost again…\n"
	.string "Is my method not hitting right?$"

Route102_Text_CalvinRematchPostBattle:
	.string "If you’re gonna keep getting stronger,\n"
	.string "I’m gonna stay on that same energy.$"

Route102_Text_AllenIntro:
	.string "You just started your journey too?\n"
	.string "We’re both fresh to this!$"

Route102_Text_AllenDefeated:
	.string "I stepped to you because I thought\n"
	.string "I had this one in the bag...$"

Route102_Text_AllenPostBattle:
	.string "I haven't caught a single win yet…\n"
	.string "I need my luck to change soon...$"

Route102_Text_RickIntro:
	.string "Hahaha! We locked eyes!\n"
	.string "My BUG POKéMON are gonna test you!$"

Route102_Text_RickDefeated:
	.string "Rah!\n"
	.string "Down and out!$"

Route102_Text_RickPostBattle:
	.string "If you catch eyes with a TRAINER,\n"
	.string "you have to step up. It's the law!$"

Route102_Text_TianaIntro:
	.string "I’m gonna keep winning until I’m the\n"
	.string "top girl in the whole region.\p"
	.string "Don't mess up my career!$"

Route102_Text_TianaDefeated:
	.string "I ended up furthering your career…$"

Route102_Text_TianaPostBattle:
	.string "To keep on the rise, I can see I’ve\n"
	.string "got to cop more POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Did you feel the pull of our\n"
	.string "soul-soothing fragrance?$"

Route103_Text_DaisyDefeated:
	.string "You weren't led astray by the aroma…$"

Route103_Text_DaisyPostBattle:
	.string "Aromatherapy is for mental healing,\n"
	.string "keeping the vibes right, you know?$"

Route103_Text_AmyIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We roll together!$"

Route103_Text_AmyDefeated:
	.string "AMY: Uh-oh, we lost.$"

Route103_Text_AmyPostBattle:
	.string "AMY: You have to think about bare\n"
	.string "things when you're battling against\l"
	.string "a whole duo.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Uh-oh, you only have one\n"
	.string "POKéMON with you.\l"
	.string "You can't step to us like that.$"

Route103_Text_LivIntro:
	.string "LIV: We battle as one team,\n"
	.string "one motive.$"

Route103_Text_LivDefeated:
	.string "LIV: Oh, we lost, big sister…$"

Route103_Text_LivPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still got smoked…$"

Route103_Text_AmyLivRegister:
	.string "LIV: For real, we're better than this…\n"
	.string "Truss! We'll show you next time!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: If you want to battle us, you\n"
	.string "need two POKéMON!\l"
	.string "It’s not a fair link-up otherwise!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We’re back on the grind!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Aww, boo!\n"
	.string "We couldn't catch the win again…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: You have to be moving smart\n"
	.string "when you're battling two of us.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Uh-oh, only one POKéMON?\n"
	.string "You can't battle us like that.$"

Route103_Text_LivRematchIntro:
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Awww, we lost again…\n"
	.string "Big sister…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But why did we get done again?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: If you want the battle, you\n"
	.string "need two POKéMON!\l"
	.string "Don't be a wasteman!$"

Route103_Text_AndrewIntro:
	.string "Gah! My line is all snarled up!\n"
	.string "I’m moving frustrated and mean!\l"
	.string "Say no more! Battle me!$"

Route103_Text_AndrewDefeated:
	.string "Gah! Lost it!\n"
	.string "I’m even more vexed now!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, I’m still boiling mad…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "My POKéMON is literally adorable!\n"
	.string "Don't be shy--I’ll show you!$"

Route103_Text_MiguelDefeated:
	.string "Oh, my gosh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "My POKéMON looks peng even when\n"
	.string "it’s fainted, truss me!$"

Route103_Text_MiguelRegister:
	.string "I’ll make sure you pull up and look\n"
	.string "in on my darling POKéMON again!$"

Route103_Text_MiguelRematchIntro:
	.string "Hi, you! My delightfully adorable\n"
	.string "POKéMON is looking even better!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "The more time we spend together,\n"
	.string "the more elite my POKéMON gets.$"

Route103_Text_PeteIntro:
	.string "This sort of distance…\n"
	.string "You should just swim it, easy!$"

Route103_Text_PeteDefeated:
	.string "Oh, that’s serious movement!$"

Route103_Text_PetePostBattle:
	.string "Oh, I see where you’re coming\n"
	.string "from now.\p"
	.string "If I had a POKéMON that trusty,\n"
	.string "I’d want to SURF on it, too!$"

Route103_Text_IsabelleIntro:
	.string "Watch where you’re stepping!\n"
	.string "We’re gonna crash!$"

Route103_Text_IsabelleDefeated:
	.string "Groan…$"

Route103_Text_IsabellePostBattle:
	.string "I’m a dead swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_RhettIntro:
	.string "Whoa!\n"
	.string "How’d you squeeze into a spot this small?$"

Route103_Text_RhettDefeated:
	.string "Whoa!\n"
	.string "The kid can actually move!$"

Route103_Text_RhettPostBattle:
	.string "You actually like cramped spots\n"
	.string "like this?$"

Route103_Text_MarcosIntro:
	.string "Did my guitar’s wailing draw you in?$"

Route103_Text_MarcosDefeated:
	.string "My one-man show is ruined…$"

Route103_Text_MarcosPostBattle:
	.string "I was playing where no one was\n"
	.string "around, but bare fans gathered.\p"
	.string "Heh, maybe I should go pro.$"

Route104_Text_GinaIntro:
	.string "GINA: Safe, let’s battle with our\n"
	.string "POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Losing actually vexes me!$"

Route104_Text_GinaPostBattle:
	.string "GINA: You're strong!\n"
	.string "We have to train way more!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh? Only one POKéMON?\n"
	.string "Then we’re not battling you.\p"
	.string "If there’s only one POKéMON, it’ll be\n"
	.string "lonesome. That’s not a vibe.$"

Route104_Text_MiaIntro:
	.string "MIA: We’re twins, so we battle\n"
	.string "POKéMON as a team.$"

Route104_Text_MiaDefeat:
	.string "MIA: We rolled together, but we\n"
	.string "both took the L…$"

Route104_Text_MiaPostBattle:
	.string "MIA: We’re gonna train the squad\n"
	.string "and get strong like you.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: You want to step to us?\p"
	.string "It’s a no-go if you don’t have two\n"
	.string "POKéMON with you. We’re too much!$"

Route104_Text_IvanIntro:
	.string "Why keep it a secret?\n"
	.string "I’m the WATER POKéMON expert!\p"
	.string "Huh?\n"
	.string "You don't know my face?$"

Route104_Text_IvanDefeat:
	.string "I thought I was moving elite, if I\n"
	.string "may say so, but I guess not… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "I got too into the fishing grind.\n"
	.string "I forgot I had to raise my squad…$"

Route104_Text_BillyIntro:
	.string "Leaving footprints in the sand is\n"
	.string "such a vibe!$"

Route104_Text_BillyDefeat:
	.string "Waah! I got sand in my creps!\n"
	.string "They're all gritty!$"

Route104_Text_BillyPostBattle:
	.string "I want to leave my mark in the\n"
	.string "sand everywhere, but it goes fast…$"

Route104_Text_HaleyIntro:
	.string "Should I…\n"
	.string "Or shouldn't I?\p"
	.string "Say no more, let’s just step!$"

Route104_Text_HaleyDefeat:
	.string "I shouldn't have stepped to you…$"

Route104_Text_HaleyPostBattle:
	.string "If you’re stuck on a decision and\n"
	.string "let someone else pick the motive,\l"
	.string "you’re gonna regret it later, truss.$"

Route104_Text_HaleyRegister1:
	.string "You’re strong, but should I add you\n"
	.string "on the POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Safe, let's just do it!$"

Route104_Text_HaleyRegister2:
	.string "You’re strong, but should I add you\n"
	.string "on the POKéNAV?\l"
	.string "Maybe I shouldn't…\p"
	.string "Safe, let's just do it!$"

Route104_Text_HaleyRematchIntro:
	.string "Come on, let’s have a proper run-back!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "I thought I had the win this time…$"

Route104_Text_HaleyPostRematch:
	.string "I chose to battle, so I can take this\n"
	.string "L like a real one.\p"
	.string "I’m still vexed about losing though!$"

Route104_Text_WinstonIntro:
	.string "Yeah, I’ll accept the challenge.\n"
	.string "I’ve got plenty of funds to back it.$"

Route104_Text_WinstonDefeat:
	.string "How did I not win that?$"

Route104_Text_WinstonPostBattle:
	.string "There’s some things money can’t buy.\n"
	.string "That's POKéMON bonds…$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Ah, you’ve copped a POKéNAV.\p"
	.string "I’ll register you. Money isn’t\n"
	.string "an issue for me, anyway.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Ah, you’ve copped a POKéNAV.\p"
	.string "I’ll register you. Money isn’t\n"
	.string "an issue for me, anyway.$"

Route104_Text_WinstonRematchIntro:
	.string "After you smoked me, I learned bare\n"
	.string "stuff about POKéMON tech.$"

Route104_Text_WinstonRematchDefeat:
	.string "Another L?\n"
	.string "Why can't I buy a win?$"

Route104_Text_WinstonPostRematch:
	.string "I’m fabulously wealthy, but I can’t\n"
	.string "seem to be the top boy at POKéMON…\p"
	.string "It’s deep, the POKéMON world…$"

Route104_Text_CindyIntro:
	.string "It must be fate that we linked up.\n"
	.string "You want to battle?$"

Route104_Text_CindyDefeat:
	.string "Oh, my!$"

Route104_Text_CindyPostBattle:
	.string "Every link-up has an end.\n"
	.string "Hope to see you on the roads again.$"

Route104_Text_CindyRegister1:
	.string "Wagwan, we meet again.\p"
	.string "We’re clearly meant to link. Let’s\n"
	.string "put each other in the POKéNAV.$"

Route104_Text_CindyRegister2:
	.string "We should mark this link-up since we\n"
	.string "keep crossing paths.\p"
	.string "Add me on the POKéNAV.$"

Route104_Text_CindyRematchIntro:
	.string "Wagwan, back again.\n"
	.string "Can I get a battle?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, my…\n"
	.string "I did the best I could…$"

Route104_Text_CindyPostRematch:
	.string "Every link-up has an end.\n"
	.string "See you around the ends.$"

Route104_Text_DarianIntro:
	.string "I fished up a POKéMON looking\n"
	.string "proper tough!\p"
	.string "It’s got a magical vibe to it!\n"
	.string "Looking dangerous, truss me!$"

Route104_Text_DarianDefeat:
	.string "What the…$"

Route104_Text_DarianPostBattle:
	.string "Yo, MAGIKARP, you’re moving proper\n"
	.string "weak. You’re not him!$"

Route105_Text_FosterIntro:
	.string "There’s meant to be a mystical\n"
	.string "rock around here.\l"
	.string "You know where the motive is?$"

Route105_Text_FosterDefeated:
	.string "I was too focused on the rock, and\n"
	.string "my squad ended up moving dead…$"

Route105_Text_FosterPostBattle:
	.string "I can spend bare time just staring\n"
	.string "at a nice rock. It’s a vibe.$"

Route105_Text_LuisIntro:
	.string "Whew! I thought you were drowning\n"
	.string "when I saw you in the deep.\p"
	.string "You look safe, so you want to step\n"
	.string "to me in a battle?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "If you’re ever in trouble, just wave\n"
	.string "one arm at the beach. Stay safe.$"

Route105_Text_DominikIntro:
	.string "Swimming the deep blue sea…\n"
	.string "The feelings are 10/10!$"

Route105_Text_DominikDefeated:
	.string "I lost…\n"
	.string "Now the vibes are dead…$"

Route105_Text_DominikPostBattle:
	.string "Why is the sea blue?\p"
	.string "I heard the tech at the SLATEPORT\n"
	.string "MUSEUM, but I forgot the intel.$"

Route105_Text_BeverlyIntro:
	.string "My body feels lighter in the water.\n"
	.string "Like I’ve copped a slimmer build!$"

Route105_Text_BeverlyDefeated:
	.string "I’m just floating…$"

Route105_Text_PostBattle:
	.string "Your weight drops to a tenth when\n"
	.string "you’re in the sea.\p"
	.string "That would make me…\n"
	.string "Hold on! Don't look at my stats!$"

Route105_Text_ImaniIntro:
	.string "The blue sky…\n"
	.string "The vast sea…\l"
	.string "Proper peaceful ends…$"

Route105_Text_ImaniDefeated:
	.string "I took the L while I was lounging!$"

Route105_Text_ImaniPostBattle:
	.string "I want people to say I’m a chill\n"
	.string "one to be around. Hehe.$"

Route105_Text_AndresIntro:
	.string "I’m convinced the sea is hiding\n"
	.string "bare secrets from us.$"

Route105_Text_AndresDefeated:
	.string "Yes…\n"
	.string "I’m dead at battling…$"

Route105_Text_AndresPostBattle:
	.string "I’m sure there’s bare secrets to find\n"
	.string "deep in the ocean.\p"
	.string "I’m gonna scout them all!$"

Route105_Text_AndresRegister:
	.string "Huh? My squad is weak, but you still\n"
	.string "want me on your POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "I told you I wasn't moving strong…\n"
	.string "You sure you want this rematch?$"

Route105_Text_AndresRematchDefeated:
	.string "Yeah…\n"
	.string "I didn’t think I could win.$"

Route105_Text_AndresRematchPostBattle:
	.string "I might be dead at battling, but my\n"
	.string "scouting game is 10/10.\p"
	.string "I’m gonna travel all the seas!$"

Route105_Text_JosueIntro:
	.string "I’m drained from all this swimming.\n"
	.string "I’m not used to the grind.\p"
	.string "I need a battle for a change of pace!$"

Route105_Text_JosueDefeated:
	.string "I lost because the sea motive is peak.$"

Route105_Text_JosuePostBattle:
	.string "Yeah, for me, the sky is a much\n"
	.string "better link-up than the sea.$"

Route106_Text_ElliotIntro:
	.string "What you rating more, fishing in the\n"
	.string "sea or a stream?$"

Route106_Text_ElliotDefeated:
	.string "Like deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_ElliotPostBattle:
	.string "Fishing is elite whether it’s in\n"
	.string "the sea or a stream, innit?$"

Route106_Text_ElliotRegister:
	.string "Fishing is good, but so is stepping.\n"
	.string "Add me, let’s link again later?$"

Route106_Text_ElliotRematchIntro:
	.string "I copped bare POKéMON fishing.\n"
	.string "Let me show you a serious battle!$"

Route106_Text_ElliotRematchDefeated:
	.string "Smoked again! Properly peak!$"

Route106_Text_ElliotRematchPostBattle:
	.string "W or L, POKéMON is the best grind!\n"
	.string "You rate that, right?$"

Route106_Text_NedIntro:
	.string "What do people do if they need to go\n"
	.string "to the toilet out here?\p"
	.string "What if my ROD hooks a big one while\n"
	.string "I’m busy? I can’t leave the spot…$"

Route106_Text_NedDefeated:
	.string "I lost because I’m desperate for\n"
	.string "the washroom…$"

Route106_Text_NedPostBattle:
	.string "Oh, no! I’ve got a feeling I’m\n"
	.string "about to hook a legendary catch!$"

Route106_Text_DouglasIntro:
	.string "Hahahah! I’m a dead runner, but in\n"
	.string "the water you can't catch me!$"

Route106_Text_DouglasDefeated:
	.string "I surrender!$"

Route106_Text_DouglasPostBattle:
	.string "I wouldn't lose a race in the sea...$"

Route106_Text_KylaIntro:
	.string "The sea is my backyard. I’m not\n"
	.string "holding back just 'cause you’re a kid!$"

Route106_Text_KylaDefeated:
	.string "Did you take it easy on me by\n"
	.string "any chance?$"

Route106_Text_KylaPostBattle:
	.string "Drifting with the waves…\n"
	.string "Total vibe! You should try it.$"

Route107_Text_DarrinIntro:
	.string "Yawn…\p"
	.string "I must have drifted off while I\n"
	.string "was floating in the waves.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, I took the L…\n"
	.string "Think I’ll just go back to sleep…$"

Route107_Text_DarrinPostBattle:
	.string "Floating and getting rocked by\n"
	.string "the waves--it’s like crashing on\l"
	.string "a plush, designer bed, truss.$"

Route107_Text_TonyIntro:
	.string "The sea is basically my backyard.\n"
	.string "Let’s step to it!$"

Route107_Text_TonyDefeated:
	.string "I lost on my home turf…\n"
	.string "I’m actually in shock!$"

Route107_Text_TonyPostBattle:
	.string "I swim the seas with a heart full of\n"
	.string "dreams…\p"
	.string "It’s a bars! A proper tune!\n"
	.string "Anyways, I’m back to the swim.$"

Route107_Text_TonyRegister:
	.string "You’ve rattled me to the core!\n"
	.string "Better add me so you don't forget me…$"

Route107_Text_TonyRematchIntro:
	.string "Swimming in the big, wide sea,\n"
	.string "my squad has leveled up proper!$"

Route107_Text_TonyRematchDefeated:
	.string "What a shock!\p"
	.string "The squad got stronger, but I’m still\n"
	.string "moving like a rookie TRAINER!$"

Route107_Text_TonyRematchPostBattle:
	.string "What you learn in a scrap makes you\n"
	.string "a tougher TRAINER. The waves\l"
	.string "taught me that life lesson.$"

Route107_Text_DeniseIntro:
	.string "You know about that little spot\n"
	.string "called DEWFORD?$"

Route107_Text_DeniseDefeated:
	.string "I proper hate this!$"

Route107_Text_DenisePostBattle:
	.string "Some weird slang is getting really\n"
	.string "trendy at DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "You trying to step to me?\n"
	.string "Safe, let’s get it then!$"

Route107_Text_BethDefeated:
	.string "I wasn’t elite enough for you.$"

Route107_Text_BethPostBattle:
	.string "I can see you’re gonna keep on the\n"
	.string "rise. I’m gonna go for it, too!$"

Route107_Text_LisaIntro:
	.string "LISA: We’re challenging you as a\n"
	.string "sister and brother duo!$"

Route107_Text_LisaDefeated:
	.string "LISA: Unreal.\n"
	.string "You’re in a different league of tough.$"

Route107_Text_LisaPostBattle:
	.string "LISA: You even got any mates who\n"
	.string "would hit the beach with you?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: If you want to battle us,\n"
	.string "bring a full squad.$"

Route107_Text_RayIntro:
	.string "RAY: Me and my sis always battle.\p"
	.string "I usually take the L, but we can\n"
	.string "smoke you in a 2-on-2!$"

Route107_Text_RayDefeated:
	.string "RAY: Wowee, you’re on a much higher\n"
	.string "level than us!$"

Route107_Text_RayPostBattle:
	.string "RAY: My sis gave me my POKéMON.\n"
	.string "I did the grind, and now it’s my\l"
	.string "main partner!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: If you want to step to us,\n"
	.string "go bring some more POKéMON!$"

Route107_Text_CamronIntro:
	.string "I’m in the middle of a triathlon,\n"
	.string "but I’m not even gassed yet!$"

Route107_Text_CamronDefeated:
	.string "That actually exhausted me…$"

Route107_Text_CamronPostBattle:
	.string "I’ve still got the swim and the run\n"
	.string "to do after this scrap.\p"
	.string "Am I gonna be okay? Bare peak.$"

Route108_Text_JeromeIntro:
	.string "My dream is to swim all seven\n"
	.string "seas in the world!$"

Route108_Text_JeromeDefeated:
	.string "I’m never gonna conquer the seas\n"
	.string "moving like this…$"

Route108_Text_JeromePostBattle:
	.string "Chilling with marine POKéMON is\n"
	.string "the best part of the swim!$"

Route108_Text_MatthewIntro:
	.string "Wagwan! You heading out to that\n"
	.string "ABANDONED SHIP, too?$"

Route108_Text_MatthewDefeated:
	.string "I’m sinking!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "Some man actually go inside that\n"
	.string "ABANDONED SHIP. Bare bookey.$"

Route108_Text_TaraIntro:
	.string "My liar of a boyfriend told me\n"
	.string "I look 10/10 in a bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, boo! Total violation!$"

Route108_Text_TaraPostBattle:
	.string "Even if it’s cap, I love being told\n"
	.string "I look peng… We girls are complex.$"

Route108_Text_MissyIntro:
	.string "I love the sea!\n"
	.string "I forget all the drama when I swim!$"

Route108_Text_MissyDefeated:
	.string "When I take an L, I get proper\n"
	.string "stressed out!$"

Route108_Text_MissyPostBattle:
	.string "Work off your stress by swimming!\n"
	.string "It’s a healthy vibe!$"

Route108_Text_CoryIntro:
	.string "I rate WATER-type POKéMON.\n"
	.string "But I rate the others, too!$"

Route108_Text_CoryDefeated:
	.string "Waaah! I lost!\n"
	.string "That’s proper peak! Waaah!$"

Route108_Text_CoryPostBattle:
	.string "Shouting is good for the soul!\n"
	.string "It patterns me up!$"

Route108_Text_CoryRegister:
	.string "I rate tough TRAINERS, too!\n"
	.string "Add me on the POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "W or L, I love stepping to people\n"
	.string "out at sea!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaah! Smoked again!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "If you’re faced with a challenge,\n"
	.string "just scream at the ocean!$"

Route108_Text_CarolinaIntro:
	.string "I take serious pride in my squad.\n"
	.string "We’ll show you a lightning battle!$"

Route108_Text_CarolinaDefeated:
	.string "That wasn’t cute at all, fam.$"

Route108_Text_CarolinaPostBattle:
	.string "Since I’m out at sea, I wouldn’t mind\n"
	.string "copping a fresh pink swimsuit…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Look at the definition!\n"
	.string "This is what you call “shredded”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "Totally flopped!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "Turns out my abs have zero to do\n"
	.string "with POKéMON battles!$"

Route109_Text_AliceIntro:
	.string "You properly protected against\n"
	.string "the sun? Don't get burned.$"

Route109_Text_AliceDefeated:
	.string "Ouch, ouch, ouch!$"

Route109_Text_AlicePostBattle:
	.string "Your cheeks are the first thing to\n"
	.string "get roasted by the sun!$"

Route109_Text_HueyIntro:
	.string "I’ve anchored in ports all over the\n"
	.string "world, but SLATEPORT is 10/10.$"

Route109_Text_HueyDefeated:
	.string "You’re the top boy!$"

Route109_Text_HueyPostBattle:
	.string "The best port has the best\n"
	.string "TRAINER… respect.$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "A battle? Now?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "I’m finished… Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "I’m usually way tougher!\n"
	.string "I’m just seasick as a dog right now!\p"
	.string "And I’m a SAILOR… it’s peak.$"

Route109_Text_RickyIntro:
	.string "I’m parched… I need a SODA POP\n"
	.string "from the SEASHORE HOUSE…$"

Route109_Text_RickyDefeated:
	.string "Groan…$"

Route109_Text_RickyPostBattle:
	.string "I’m getting famished… My inner tube\n"
	.string "is looking like a glazed doughnut…$"

Route109_Text_RickyRegister:
	.string "Can we have a run-back when I’m\n"
	.string "not dying of thirst?$"

Route109_Text_RickyRematchIntro:
	.string "I’m hungry, but I’ve still got enough\n"
	.string "energy to step to you!$"

Route109_Text_RickyRematchDefeated:
	.string "I lost…\n"
	.string "It’s definitely the hunger…$"

Route109_Text_RickyRematchPostBattle:
	.string "When you eat on the beach, everything\n"
	.string "tastes like a gourmet meal.$"

Route109_Text_LolaIntro:
	.string "Doesn’t a beach umbrella look like\n"
	.string " a massive flower from the ends?$"

Route109_Text_LolaDefeated:
	.string "Mommy!$"

Route109_Text_LolaPostBattle:
	.string "If you look at the beach from a bird's\n"
	.string "eye view, it’s like a garden!$"

Route109_Text_LolaRegister:
	.string "Me?\n"
	.string "I’m on this block every day!$"

Route109_Text_LolaRematchIntro:
	.string "I’m not taking another L!\n"
	.string "That’s why I copped the inner tube!$"

Route109_Text_LolaRematchDefeated:
	.string "Mommy!$"

Route109_Text_LolaRematchPostBattle:
	.string "If I have an inner tube, me and my\n"
	.string "squad’s cuteness goes up bare!$"

Route109_Text_AustinaIntro:
	.string "I can’t swim without my inner tube,\n"
	.string "but I won’t lose at POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "Did I lose because of the tube?$"

Route109_Text_AustinaPostBattle:
	.string "My inner tube is a fashion piece.\n"
	.string "I can’t be seen without it.$"

Route109_Text_GwenIntro:
	.string "Wagwan, big TRAINER.\n"
	.string "You want to battle with me?$"

Route109_Text_GwenDefeated:
	.string "Oh, you’re actually moving strong.$"

Route109_Text_GwenPostBattle:
	.string "How did you get the squad to\n"
	.string "move like that?$"

Route109_Text_CarterIntro:
	.string "Wahahah! This man is about to catch\n"
	.string "himself a legendary one!$"

Route109_Text_CarterDefeated:
	.string "This man just lost one…$"

Route109_Text_CarterPostBattle:
	.string "This man thinks you’re a big one.\n"
	.string "Nah, you’re a legend-in-the-making!$"

Route109_Text_PaulIntro:
	.string "PAUL: Talk about a mood-killer.\p"
	.string "I wish you wouldn’t disturb our\n"
	.string "exclusive time together.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Fine, I give up.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Just don’t tell the mandem\n"
	.string "we’re out here.\l"
	.string "This is our private world!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: We’re totally, deeply in love.\n"
	.string "That’s why our squad battles as one.$"

Route109_Text_MelIntro:
	.string "MEL: We’re, like, totally in love.\n"
	.string "Our romance is heating up all HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: We lost, and it’s my fault!\n"
	.string "PAUL is gonna hate me!$"

Route109_Text_MelPostBattle:
	.string "MEL: Um, PAUL, are you vexed with me?\n"
	.string "Please don’t be angry.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: We’re, like, deeply in love.\n"
	.string "That’s why our POKéMON battle\l"
	.string "together, innit.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! See?\n"
	.string "My inner tube is proper round!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Proper peak!$"

Route109_Text_ChandlerPostBattle:
	.string "And after I showed you my legendary\n"
	.string "round inner tube, too…$"

Route109_Text_HaileyIntro:
	.string "I can’t swim, so I’m just faking\n"
	.string "the movement.$"

Route109_Text_HaileyDefeated:
	.string "I knew it!\n"
	.string "I didn’t think we could win.$"

Route109_Text_HaileyPostBattle:
	.string "When I learn how to swim, I think\n"
	.string "the squad will get way tougher.$"

Route109_Text_ElijahIntro:
	.string "For a man as macho as me, this kind\n"
	.string "of POKéMON is the perfect accessory!$"

Route109_Text_ElijahDefeated:
	.string "I’m still cold even in defeat, yeah?$"

Route109_Text_ElijahPostBattle:
	.string "For a man as macho as me, a port\n"
	.string "is the elite setting!\p"
	.string "Think I’ll head for SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Whoa! Watch the movement!\n"
	.string "I guess you're not used to BIKE racing.$"

Route110_Text_JacobDefeated:
	.string "Whoa!\n"
	.string "My brakes just failed me!$"

Route110_Text_JacobPostBattle:
	.string "Flat tires and brake drama can\n"
	.string "leave you proper finished!\l"
	.string "Check your BIKE before you roll!$"

Route110_Text_AnthonyIntro:
	.string "Yo, you!\n"
	.string "Can you even keep up with my pace?$"

Route110_Text_AnthonyDefeated:
	.string "Crash and burn! Total violation!$"

Route110_Text_AnthonyPostBattle:
	.string "Speed alone isn't enough for the W.\n"
	.string "I need to pattern my strategy…$"

Route110_Text_BenjaminIntro:
	.string "Don't panic just 'cause the BIKE\n"
	.string "is moving fast!$"

Route110_Text_BenjaminDefeated:
	.string "I shouldn't panic during the scrap…$"

Route110_Text_BenjaminPostBattle:
	.string "No need for the stress, fam.\n"
	.string "Take it easy. We’ve got bare time.$"

Route110_Text_BenjaminRegister:
	.string "I’m gonna keep rolling, no stress.\n"
	.string "Give me a shout if you want a go.$"

Route110_Text_BenjaminRematchIntro:
	.string "Aren't you moving a bit too fast?\n"
	.string "Chill for a sec and let’s battle.$"

Route110_Text_BenjaminRematchDefeated:
	.string "I stayed calm, but I still took the L…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "No need for the panic or stress.\n"
	.string "Just keep it 100. There's bare time.$"

Route110_Text_AbigailIntro:
	.string "The triathlon grind is peak.\p"
	.string "You’ve gotta complete the swim, the\n"
	.string "cycle, and the run. No days off.$"

Route110_Text_AbigailDefeated:
	.string "POKéMON battles are peak, too!$"

Route110_Text_AbigailPostBattle:
	.string "I’m gassed, I need a breather.\n"
	.string "Getting your rest is vital, truss.$"

Route110_Text_AbigailRegister:
	.string "You know what, I rate you!\n"
	.string "Let’s do a run-back on CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "Isn't it a vibe to battle while\n"
	.string "you’re cycling?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "How are you moving this strong?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Were you chasing a personal record?\p"
	.string "My bad if I held up your pace!$"

Route110_Text_JasmineIntro:
	.string "I’ve been riding with no stops.\n"
	.string "My thighs are moving like granite!$"

Route110_Text_JasmineDefeated:
	.string "I’m worried the muscles might cramp…$"

Route110_Text_JasminePostBattle:
	.string "Oh, you’ve copped some GYM BADGES?\n"
	.string "No wonder your squad moves like that!$"

Route110_Text_EdwardIntro:
	.string "I already saw your next move!\n"
	.string "I can't possibly take an L!$"

Route110_Text_EdwardDefeated:
	.string "I failed to see my own downfall!$"

Route110_Text_EdwardPostBattle:
	.string "I can see your future…\p"
	.string "Hmm…\n"
	.string "The light is blinding, fam.$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "I’ll dazzle you with my wonders!$"

Route110_Text_JaclynDefeated:
	.string "I wondrously flopped!$"

Route110_Text_JaclynPostBattle:
	.string "You only won because it was a fluke!\n"
	.string "A total wonder! Don't think you can\l"
	.string "stay winning forever!$"

Route110_Text_EdwinIntro:
	.string "Can I check your POKéMON?\n"
	.string "Just one look at the gear?$"

Route110_Text_EdwinDefeated:
	.string "I just wanted to complete\n"
	.string "the collection…$"

Route110_Text_EdwinPostBattle:
	.string "When I see a POKéMON I don't know,\n"
	.string "the collector passion gets ignited!$"

Route110_Text_EdwinRegister:
	.string "I’m collecting MATCH CALL\n"
	.string "registrations, too. Add me!$"

Route110_Text_EdwinRematchIntro:
	.string "Yo, copped any new POKéMON recently?\p"
	.string "Can I see the squad?\n"
	.string "Just one look, please!$"

Route110_Text_EdwinRematchDefeated:
	.string "Your squad…\n"
	.string "The envy is real.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Man, I just want to make all the\n"
	.string "rarest POKéMON mine!$"

Route110_Text_DaleIntro:
	.string "Yo!\n"
	.string "Don't just creep up on a man!$"

Route110_Text_DaleDefeated:
	.string "I lost!\n"
	.string "That’s dead!$"

Route110_Text_DalePostBattle:
	.string "Fishing is all about the focus.\n"
	.string "You’ve gotta watch the floater.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! I’ll go anywhere just to\n"
	.string "show off my elite POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, man, this won't do at all.$"

Route110_Text_IsabelPostBattle:
	.string "Maybe I should stop battling and\n"
	.string "just flex at the FAN CLUB instead.$"

Route110_Text_IsabelRegister:
	.string "That wasn't even my full power.\p"
	.string "I’m gonna make you my audience\n"
	.string "whenever I can!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! I’m happy to flex my\n"
	.string "squad whenever you like!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, dear, the vibe is gone.$"

Route110_Text_IsabelRematchPostBattle:
	.string "I don't think I could ever stop\n"
	.string "showing off my POKéMON.\p"
	.string "But I do love a good scrap!$"

Route110_Text_TimmyIntro:
	.string "I found some cold POKéMON in the\n"
	.string "long grass round here!$"

Route110_Text_TimmyDefeated:
	.string "Being cold isn't enough to win…$"

Route110_Text_TimmyPostBattle:
	.string "It’s hard to battle with a squad\n"
	.string "you literally just copped.$"

Route110_Text_AlyssaIntro:
	.string "I literally fell off CYCLING ROAD…\p"
	.string "I’m gonna erase the embarrassment\n"
	.string "by smoking you in a battle!$"

Route110_Text_AlyssaDefeated:
	.string "Oops!\n"
	.string "I ended up taking the L!$"

Route110_Text_AlyssaPostBattle:
	.string "Falling… Losing…\n"
	.string "The humiliation is real, fam!$"

Route110_Text_JosephIntro:
	.string "Okay! Full-throttle time! If you\n"
	.string "can't catch the groove, you’re dust!$"

Route110_Text_JosephDefeated:
	.string "You caught the groove, fair play…$"

Route110_Text_JosephPostBattle:
	.string "This isn't gonna break me!\n"
	.string "Losing only makes a man tougher!$"

Route110_Text_KalebIntro:
	.string "When cute POKéMON back each other up…\n"
	.string "It’s the most wholesome sight, truss!$"

Route110_Text_KalebDefeated:
	.string "Have you no pity for the small ones?$"

Route110_Text_KalebPostBattle:
	.string "Safe, safe, you did your best,\n"
	.string "my little ones.$"

Route111_Text_DrewIntro:
	.string "Oh, yo! Those GO-GOGGLES are fresh.\n"
	.string "But they look better on me, innit.\p"
	.string "Let's see who’s got the real drip\n"
	.string "with a battle!$"

Route111_Text_DrewDefeat:
	.string "I couldn't see the flank because\n"
	.string "of these GO-GOGGLES.$"

Route111_Text_DrewPostBattle:
	.string "GO-GOGGLES make the sandstorms\n"
	.string "light work. That’s a result!$"

Route111_Text_HeidiIntro:
	.string "I’m having a desert picnic.\p"
	.string "You can always find a TRAINER out\n"
	.string "here, so I can get a battle in!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! You’re moving mean!$"

Route111_Text_HeidiPostBattle:
	.string "When you’re scrap in a sandstorm,\n"
	.string "watch your squad's HP closely.\p"
	.string "They’ll drop before you know it if\n"
	.string "you’re not focused!$"

Route111_Text_BeauIntro:
	.string "Wearing these GO-GOGGLES makes me\n"
	.string "feel like a proper hero.\l"
	.string "Right now, nobody can touch me!$"

Route111_Text_BeauDefeat:
	.string "Can't win on just the spirit…$"

Route111_Text_BeauPostBattle:
	.string "I’m gonna be a legend one day.\n"
	.string "I’m gonna grind harder to make\l"
	.string "my squad the strongest in the ends.$"

Route111_Text_BeckyIntro:
	.string "I heard there’s fossils in the\n"
	.string "sand out here. Where’s the spot?$"

Route111_Text_BeckyDefeat:
	.string "I came up short…$"

Route111_Text_BeckyPostBattle:
	.string "If there’s fossils in the desert,\n"
	.string "this place must’ve been the sea\l"
	.string "back in the day. Mad.$"

Route111_Text_DustyIntro:
	.string "For thirty years I’ve searched for\n"
	.string "the ancient ruins!\l"
	.string "You really want to challenge me?$"

Route111_Text_DustyDefeat:
	.string "I spent too long looking for ruins\n"
	.string "and not enough for strong POKéMON.$"

Route111_Text_DustyPostBattle:
	.string "For thirty years I’ve searched for\n"
	.string "the ancient ruins!\p"
	.string "Wait, was it forty? I’m losing track.$"

Route111_Text_DustyRegister:
	.string "I haven't been looking for a fight.\p"
	.string "But for some reason, I really rate\n"
	.string "these POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "For thirty years I’ve searched for\n"
	.string "the ancient ruins!\p"
	.string "Or forty? Anyway, you still want\n"
	.string "to step to me?$"

Route111_Text_DustyRematchDefeat:
	.string "No ruins found, and no W today either…$"

Route111_Text_DustyPostRematch:
	.string "For thirty years I’ve searched for\n"
	.string "the ancient ruins!\p"
	.string "Actually, it might be fifty…\n"
	.string "How long have I been on this block?$"

Route111_Text_TravisIntro:
	.string "I’m full of energy!\n"
	.string "And my squad is lively, too!$"

Route111_Text_TravisDefeat:
	.string "My POKéMON lost its hype…$"

Route111_Text_TravisPostBattle:
	.string "When I see a TRAINER moving with\n"
	.string "that much energy, I have to look.$"

Route111_Text_IreneIntro:
	.string "I don't know where you’re heading,\n"
	.string "but you want to battle?$"

Route111_Text_IreneDefeat:
	.string "Oh, you’re disgustingly good!$"

Route111_Text_IrenePostBattle:
	.string "I was thinking of hitting MT. CHIMNEY,\n"
	.string "but the view here is a total vibe.$"

Route111_Text_DaisukeIntro:
	.string "To train myself, I challenge anyone\n"
	.string "I cross paths with!$"

Route111_Text_DaisukeDefeat:
	.string "Safe! I give up!$"

Route111_Text_DaisukePostBattle:
	.string "I just gotta keep on the grind until\n"
	.string "I can beat elite TRAINERS like you.$"

Route111_Text_WiltonIntro:
	.string "Show me how much you’ve actually\n"
	.string "toughened up your squad.$"

Route111_Text_WiltonDefeat:
	.string "I see, you’ve toughened them up\n"
	.string "considerably. Respect.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON and TRAINERS learn bare\n"
	.string "knowledge through a scrap.\p"
	.string "What’s vital is to never stop the\n"
	.string "grind, even when you take an L.$"

Route111_Text_WiltonRegister:
	.string "There’s bare to be learned from\n"
	.string "your training style.\p"
	.string "I’m requesting a run-back if you’re\n"
	.string "feeling up to it.$"

Route111_Text_WiltonRematchIntro:
	.string "We’re out here training to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and grind with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, you’re moving proper!$"

Route111_Text_WiltonPostRematch:
	.string "Since you’re that strong, you should\n"
	.string "be aiming for the POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "Oh, your POKéMON look like some\n"
	.string "serious main characters.\l"
	.string "I have to ask you for a link-up.$"

Route111_Text_BrookeDefeat:
	.string "They didn’t just look strong,\n"
	.string "they’re actually built different!$"

Route111_Text_BrookePostBattle:
	.string "I thought I was raising my squad\n"
	.string "properly, but clearly there’s still\l"
	.string "bare work to be done.$"

Route111_Text_BrookeRegister:
	.string "I wish I could link with more\n"
	.string "elite people like you!$"

Route111_Text_BrookeRematchIntro:
	.string "You can make a squad strong or\n"
	.string "weak depending on the tech you\l"
	.string "teach them.\p"
	.string "What kind of moves is your squad\n"
	.string "carrying?$"

Route111_Text_BrookeRematchDefeat:
	.string "You’ve taught them some elite moves!$"

Route111_Text_BrookePostRematch:
	.string "Maybe I should’ve stopped my\n"
	.string "squad from evolving until they\l"
	.string "learned the best tech…$"

Route111_Text_CeliaIntro:
	.string "I definitely picked the wrong spot\n"
	.string "to set up a picnic!$"

Route111_Text_CeliaDefeat:
	.string "Aww!\n"
	.string "I really shouldn't have come out!$"

Route111_Text_CeliaPostBattle:
	.string "In a sandstorm like this, I can't even\n"
	.string "see the vibes even with my\l"
	.string "GO-GOGGLES on…$"

Route111_Text_BryanIntro:
	.string "How tough are you really?\n"
	.string "Time to expose the truth!$"

Route111_Text_BryanDefeat:
	.string "Oh! Your strength!\n"
	.string "It’s shrouded in mystery, fam!$"

Route111_Text_BryanPostBattle:
	.string "This desert hides bare mysteries in\n"
	.string "the shifting sands!$"

Route111_Text_BrandenIntro:
	.string "I’ll give you half my sandwich\n"
	.string "if you just take the L.$"

Route111_Text_BrandenDefeat:
	.string "Tch! I thought a sandwich would be\n"
	.string "enough to bribe you…$"

Route111_Text_BrandenPostBattle:
	.string "My SANDSHREW is always trying to\n"
	.string "thieve my sandwiches.$"

Route111_Text_TyronIntro:
	.string "This is my favorite kind of squad!$"

Route111_Text_TyronDefeat:
	.string "Wait!\n"
	.string "Did you get a good look at my POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "When having a scrap, I get a kick out\n"
	.string "of flexing my POKéMON.\p"
	.string "I bet everyone feels that way when\n"
	.string "they step into a battle!$"

Route111_Text_CelinaIntro:
	.string "Show me how to put a little hype\n"
	.string "into my life.$"

Route111_Text_CelinaDefeat:
	.string "Oh… My…\n"
	.string "That was too much hype for me.$"

Route111_Text_CelinaPostBattle:
	.string "My pulse is still racing.\n"
	.string "You’re a legendary TRAINER, truss.$"

Route111_Text_HaydenIntro:
	.string "When you’re as famished as I am,\n"
	.string "pity isn't an option!$"

Route111_Text_HaydenDefeat:
	.string "Groan… I’m finished…$"

Route111_Text_HaydenPostBattle:
	.string "My stomach is rumbling proper!\n"
	.string "Maybe I can grill some BERRIES…$"

Route111_Text_BiancaIntro:
	.string "Did you just come from MAUVILLE?\n"
	.string "You should be full of energy!$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala!\n"
	.string "That’s a lot to deal with!$"

Route111_Text_BiancaPostBattle:
	.string "This road here…\n"
	.string "You’ve got a long journey ahead, fam.$"

Route112_Text_BriceIntro:
	.string "Hahahaha!\n"
	.string "How about we have a scrap?\l"
	.string "Just you and me!\l"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "I lost!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Something flew up my nose!\n"
	.string "Hahahaha-hatchoo!$"

Route112_Text_TrentIntro:
	.string "My legs are solid from pounding\n"
	.string "up and down these mountains.\p"
	.string "They’re not going to buckle easily!$"

Route112_Text_TrentDefeat:
	.string "Ouch! My legs just cramped up!$"

Route112_Text_TrentPostBattle:
	.string "Try hiking these mountain trails\n"
	.string "with a heavy pack. No days off.\p"
	.string "That, my friend, will get your body\n"
	.string "moving correct.$"

Route112_Text_TrentRegister:
	.string "Ow, the cramp is real.\n"
	.string "Grab some bandages from my bag?\p"
	.string "Wait, that’s my POKéNAV!\n"
	.string "Oh, fine, I’ll register you.$"

Route112_Text_TrentRematchIntro:
	.string "I’ve been keeping fit on the trails.\n"
	.string "I’ve got power in spades!$"

Route112_Text_TrentRematchDefeat:
	.string "I got trumped in power? Mad.$"

Route112_Text_TrentRematchPostBattle:
	.string "I hear there are some seriously tough\n"
	.string "TRAINERS on top of MT. CHIMNEY.\p"
	.string "I’m gonna get up there and test them!$"

Route112_Text_LarryIntro:
	.string "I’m strong.\n"
	.string "I’m not gonna cry if I lose.$"

Route112_Text_LarryDefeat:
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:
	.string "I’m not crying because I miss home!\n"
	.string "Snivel…$"

Route112_Text_CarolIntro:
	.string "When you’re out on a picnic,\n"
	.string "you’ve simply got to sing!\l"
	.string "Come on, jump on the track!$"

Route112_Text_CarolDefeat:
	.string "Oh, you’re so strong!$"

Route112_Text_CarolPostBattle:
	.string "Doesn't matter if you’re dead at singing\n"
	.string "or POKéMON.\p"
	.string "If you’re having the most fun, you win!$"

Route112_Text_BryantIntro:
	.string "I copped hot POKéMON in FIERY PATH!\n"
	.string "Check the heat!$"

Route112_Text_BryantDefeat:
	.string "What a bumpy ride that was!$"

Route112_Text_BryantPostBattle:
	.string "I rate the way you battle.\n"
	.string "It’s got a certain flair to it, innit.$"

Route112_Text_ShaylaIntro:
	.string "Oh, aren't you an adorable TRAINER!\n"
	.string "Please, I need a romantic scrap!\l"
	.string "I’m somewhat decent!$"

Route112_Text_ShaylaDefeat:
	.string "Oh, how strong you are!\n"
	.string "You’ve given me quite a shock!$"

Route112_Text_ShaylaPostBattle:
	.string "You busy right now?\n"
	.string "I was thinking maybe we could do\l"
	.string "a rematch right this second…\l"
	.string "But it’s safe if you’re busy.$"

Route113_Text_JaylenIntro:
	.string "Can you guess why the temperature\n"
	.string "is so chill around here?$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw!\n"
	.string "That stinks!$"

Route113_Text_JaylenPostBattle:
	.string "The volcanic ash blocks the sun,\n"
	.string "so it doesn't get very warm.\p"
	.string "Good for me—I can't stand the heat!$"

Route113_Text_DillonIntro:
	.string "The volcano's eruption is proof that\n"
	.string "the earth is alive, fam.$"

Route113_Text_DillonDefeat:
	.string "You’re some kind of strong!$"

Route113_Text_DillonPostBattle:
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was dead, sorry…$"

Route113_Text_MadelineIntro:
	.string "I use this parasol to keep this\n"
	.string "filthy volcanic ash off\l"
	.string "my dear NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Huff, huff…\n"
	.string "I am exhausted…$"

Route113_Text_MadelinePostBattle:
	.string "You’re very good at this.\n"
	.string "I must say I’m impressed!$"

Route113_Text_MadelineRegister:
	.string "Here, slide under my parasol.\n"
	.string "Let me put you in the POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hello, has it been a minute?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, how super!$"

Route113_Text_MadelinePostRematch:
	.string "You’ve stayed very good at this.\n"
	.string "I must say I’m impressed!$"

Route113_Text_LaoIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostBattle:
	.string "I must refine the art of stealth.\n"
	.string "I bid thee farewell.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of POKéNAV registration!$"

Route113_Text_LaoRematchIntro:
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoRematchDefeat:
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostRematch:
	.string "My flawless stealth was let down\n"
	.string "by my rookie battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Safe for finding me!\n"
	.string "But we still have to scrap!$"

Route113_Text_LungDefeat:
	.string "I’ll use my ninjutsu on you…\n"
	.string "“VOLCANIC ASH SWIRL CLOAK”!\p"
	.string "…What?\n"
	.string "It’s already over?$"

Route113_Text_LungPostBattle:
	.string "You know what’s dead about hiding?\n"
	.string "It’s lonely if no one comes along.$"

Route113_Text_ToriIntro:
	.string "TORI: Both of us are on the ash\n"
	.string "grind. We battle POKéMON, too.$"

Route113_Text_ToriDefeat:
	.string "TORI: We lost… That’s dead. I’m going\n"
	.string "back to gathering more ashes.$"

Route113_Text_ToriPostBattle:
	.string "TORI: How much ash we got? Hopefully\n"
	.string "enough to cop a WHITE FLUTE.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: We only do 2-on-2 scraps.\n"
	.string "If we didn't, we’d get smoked!$"

Route113_Text_TiaIntro:
	.string "TIA: Both of us are out here for\n"
	.string "the ash. We do battles, too.$"

Route113_Text_TiaDefeat:
	.string "TIA: We couldn't take the W… Boring.\n"
	.string "Back to the ash gathering, then.$"

Route113_Text_TiaPostBattle:
	.string "TIA: We’ve got bare ashes now!\n"
	.string "Defo enough for a WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: We only want 2-on-2 scraps.\n"
	.string "If we don't, we won't win!$"

Route113_Text_CobyIntro:
	.string "Pfft, with these wings I can\n"
	.string "flick you away like dust!$"

Route113_Text_CobyDefeat:
	.string "A… What just happened?$"

Route113_Text_CobyPostBattle:
	.string "I don't even have the words when\n"
	.string "I get beaten that easily…$"

Route113_Text_SophieIntro:
	.string "The warmth here is making me drowsy.\n"
	.string "Let’s scrap so I can stay awake.$"

Route113_Text_SophieDefeat:
	.string "This has to be a dream.\n"
	.string "I'm certain of it…$"

Route113_Text_SophiePostBattle:
	.string "Taking an L burns me up…\n"
	.string "I'm just gonna kersh right here!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Were you in the middle of your\n"
	.string "ash-gathering grind as well?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "We got beaten proper cleanly.$"

Route113_Text_LawrencePostBattle:
	.string "Maybe I should just hide under\n"
	.string "the ashes, too. Low profile.$"

Route113_Text_WyattIntro:
	.string "Y-you want to step to me?\n"
	.string "Even though I just copped these?$"

Route113_Text_WyattDefeat:
	.string "Y-you're actually gassed about winning?\n"
	.string "Even though it's just me?$"

Route113_Text_WyattPostBattle:
	.string "Oh, so now you’ve got words for\n"
	.string "the loser? Moving like a big man?\p"
	.string "Think you’re the coolest, eh?\n"
	.string "Humph!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "You’re supposed to shout it back!\n"
	.string "There’s zero echo out here, fam!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo! (That’s an L)$"

Route114_Text_LennyPostBattle:
	.string "When I was a little tyke, I thought\n"
	.string "someone was copycatting me and\l"
	.string "shouting back. Proper bookey.$"

Route114_Text_LucasIntro:
	.string "If you’re not prepared, you shouldn’t\n"
	.string "be up in these mountains!$"

Route114_Text_LucasDefeat:
	.string "The mountains are unforgiving…$"

Route114_Text_LucasPostBattle:
	.string "In the winter, these peaks turn deadly.\n"
	.string "Blizzards and avalanches—no joke.$"

Route114_Text_ShaneIntro:
	.string "Camping's a vibe! Fishing, roasting\n"
	.string "snacks, and telling spooky stories!\p"
	.string "But the best part is the scrap!$"

Route114_Text_ShaneDefeat:
	.string "Way too strong, man!$"

Route114_Text_ShanePostBattle:
	.string "It’s top-tier being able to go\n"
	.string "camping with the squad.$"

Route114_Text_NancyIntro:
	.string "I need a bit of cardio after a meal.\n"
	.string "Let’s have a match!$"

Route114_Text_NancyDefeat:
	.string "Oh, no! My rhythm!$"

Route114_Text_NancyPostBattle:
	.string "That was a heavy meal.\n"
	.string "I’m getting bare drowsy now…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Want to step to my POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M-My squad…$"

Route114_Text_StevePostBattle:
	.string "A massive body, lumpy and hard,\n"
	.string "huge horns, and vicious fangs…\p"
	.string "Ufufufufu…\n"
	.string "I need to cop a POKéMON like that…$"

Route114_Text_SteveRegister:
	.string "Don't forget what you did to me!\n"
	.string "I’ll make sure you can't forget!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Come on, battle my squad…$"

Route114_Text_SteveRematchDefeat:
	.string "I feel so lucky just seeing your\n"
	.string "squad in action…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "When I see POKéMON scrap, I get all\n"
	.string "shivery and shaky… it’s a vibe.$"

Route114_Text_BernieIntro:
	.string "If you're lighting a campfire,\n"
	.string "keep some water handy. Safety first.$"

Route114_Text_BernieDefeat:
	.string "Safe for dousing my fire!$"

Route114_Text_BerniePostBattle:
	.string "You really have to watch it with\n"
	.string "fire in the woods. Serious stuff.\p"
	.string "Don't ever underestimate the heat.$"

Route114_Text_BernieRegister:
	.string "You set my spirit on fire, fam.\n"
	.string "Let's exchange details!$"

Route114_Text_BernieRematchIntro:
	.string "Have you learned to keep that water\n"
	.string "handy for the campfires yet?$"

Route114_Text_BernieRematchDefeat:
	.string "I got hosed down before I could\n"
	.string "even flare up. Peak.$"

Route114_Text_BerniePostRematch:
	.string "You really do have to be careful with\n"
	.string "fire in the forest. It’s no joke.$"

Route114_Text_ClaudeIntro:
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me, truss.\l"
	.string "But for now, bring on your squad!$"

Route114_Text_ClaudeDefeat:
	.string "If we were fishing, I would’ve won…$"

Route114_Text_ClaudePostBattle:
	.string "Think I’ll try my luck landing a big\n"
	.string "one at METEOR FALLS.\p"
	.string "There’s gotta be a legendary catch\n"
	.string "in there. I just know it.$"

Route114_Text_NolanIntro:
	.string "I rate fishing. But I also rate\n"
	.string "a good scrap!\p"
	.string "If anyone steps to me, I’m there,\n"
	.string "even if I’m mid-catch.$"

Route114_Text_NolanDefeat:
	.string "I love the battle, but that doesn't\n"
	.string "mean I’m actually good at it…$"

Route114_Text_NolanPostBattle:
	.string "Next time I’ll bag the W!\p"
	.string "I always tell myself that, so I can't\n"
	.string "stop fishing or battling. Ever.$"

Route114_Text_TyraIntro:
	.string "TYRA: Well, sure.\n"
	.string "I’m in the mood for a scrap.\l"
	.string "I’ll teach you a bit about POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: What an amazing battle style!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: I was just teaching my junior\n"
	.string "IVY the ropes of the game.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Giggle…\n"
	.string "If you want to step to us, one POKéMON\l"
	.string "isn’t enough of a challenge!$"

Route114_Text_IvyIntro:
	.string "IVY: Who taught you the game?$"

Route114_Text_IvyDefeat:
	.string "IVY: Your style is actually unreal!$"

Route114_Text_IvyPostBattle:
	.string "IVY: I started training because TYRA,\n"
	.string "my mentor, showed me the way!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I bet it feels bare lonely.$"

Route114_Text_KaiIntro:
	.string "I landed a big one!\n"
	.string "A massive one, I’m telling you!$"

Route114_Text_KaiDefeat:
	.string "What was that about?\n"
	.string "Did mine lose on the size?$"

Route114_Text_KaiPostBattle:
	.string "Safe!\n"
	.string "I’ll just fish me an even bigger one!$"

Route114_Text_CharlotteIntro:
	.string "Me!\n"
	.string "I’m not just a peng face, you know!$"

Route114_Text_CharlotteDefeat:
	.string "That wasn't cute in the slightest!$"

Route114_Text_CharlottePostBattle:
	.string "I don't want a squad that's\n"
	.string "just cute.\p"
	.string "I adore the ones that have a proper\n"
	.string "quirk or two!$"

Route114_Text_AngelinaIntro:
	.string "Have you been evolving your squad\n"
	.string "much lately?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, I see.\n"
	.string "Good to know the level.$"

Route114_Text_AngelinaPostBattle:
	.string "Some POKéMON change so much when\n"
	.string "they evolve, it’s actually mental!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "You seem like you’ve got talent…\l"
	.string "Let’s see what you’re about!$"

Route115_Text_TimothyDefeat:
	.string "You're much stronger than\n"
	.string "I’d even imagined!$"

Route115_Text_TimothyPostBattle:
	.string "No such thing as a born genius, fam.\n"
	.string "It’s all about the effort!\l"
	.string "That’s what I believe in…$"

Route115_Text_TimothyRegister:
	.string "Hmm… A loss this thorough hasn't\n"
	.string "happened in a minute.\p"
	.string "If you're up for it, I want a\n"
	.string "rematch down the line.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… As always, your movement speaks\n"
	.string "for itself.\l"
	.string "Come, show me more!$"

Route115_Text_TimothyRematchDefeat:
	.string "Strong as ever, truss!$"

Route115_Text_TimothyPostRematch:
	.string "All it takes is the grind!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort yet!$"

Route115_Text_KoichiIntro:
	.string "You!\p"
	.string "My MACHOP!\p"
	.string "Demand a scrap!$"

Route115_Text_KoichiDefeat:
	.string "Ouch, ouch, ouch! Violation!$"

Route115_Text_KoichiPostBattle:
	.string "My MACHOP crew!\p"
	.string "As long as they're chasing gains,\n"
	.string "I’ll be right there grinding with them!$"

Route115_Text_NobIntro:
	.string "My best party trick is busting bricks\n"
	.string "with my forehead!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "My head is finished!$"

Route115_Text_NobPostBattle:
	.string "I’ve been teaching the squad karate.\p"
	.string "Looks like they’re gonna be way more\n"
	.string "elite than me soon. I love to see it.$"

Route115_Text_NobRegister:
	.string "You’re moving proper! Give me a\n"
	.string "run-back once I’ve reset the grind!$"

Route115_Text_NobRematchIntro:
	.string "Since you smoked me, we’ve been on a\n"
	.string "serious training arc.\l"
	.string "Come on, give us the rematch!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "Another L for the books!$"

Route115_Text_NobPostRematch:
	.string "The squad is gonna get even stronger!\n"
	.string "I’m redoubling the effort!$"

Route115_Text_CyndyIntro:
	.string "This beach is my secret gym spot!\n"
	.string "Don't come butting in on my sets!$"

Route115_Text_CyndyDefeat:
	.string "I haven't put in enough reps!$"

Route115_Text_CyndyPostBattle:
	.string "The sand is like a natural cushion for\n"
	.string "the joints, keeps the impact low.\l"
	.string "Perfect spot for a workout, truss.$"

Route115_Text_CyndyRegister:
	.string "Okay, safe, you can train here.\n"
	.string "But only if you agree to a rematch.$"

Route115_Text_CyndyRematchIntro:
	.string "Alright, let's get this scrap on!$"

Route115_Text_CyndyRematchDefeat:
	.string "I’m fit for it, but my squad…$"

Route115_Text_CyndyPostRematch:
	.string "Even when I take the L, it’s a vibe.\n"
	.string "I guess I just love POKéMON that much.$"

Route115_Text_HectorIntro:
	.string "I’ve got a rare POKéMON!\n"
	.string "Want me to flex it for you?$"

Route115_Text_HectorDefeat:
	.string "You…\n"
	.string "You’re tryna thieve my squad, ain't it?$"

Route115_Text_HectorPostBattle:
	.string "Just having this rare POKéMON is\n"
	.string "enough to keep me satisfied, fam.$"

Route115_Text_KyraIntro:
	.string "I’m battling while I’m on my run!\n"
	.string "Try and keep up with the pace!$"

Route115_Text_KyraDefeat:
	.string "Gasp, gasp… Out of breath…$"

Route115_Text_KyraPostBattle:
	.string "Mistake. I shouldn't have tried a\n"
	.string "scrap mid-sprint!\p"
	.string "I need another lap just to calm down…$"

Route115_Text_JaidenIntro:
	.string "Take this!\n"
	.string "Ultra POKéMON ninja tech!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "The strategy flopped!$"

Route115_Text_JaidenPostBattle:
	.string "But the squad was ultra, though,\n"
	.string "right? Tell me they were ultra.$"

Route115_Text_HeleneIntro:
	.string "My squad has that black belt\n"
	.string "energy, truss!$"

Route115_Text_HeleneDefeat:
	.string "This is peak humiliation!$"

Route115_Text_HelenePostBattle:
	.string "I rarely meet anyone who’s actually\n"
	.string "better than me…\p"
	.string "Wait, I get it!\n"
	.string "You’re a GYM LEADER, aren't you?$"

Route115_Text_AlixIntro:
	.string "Eye contact! No running away now,\n"
	.string "you’re locked in!$"

Route115_Text_AlixDefeat:
	.string "Gah!\n"
	.string "Not bad at all!$"

Route115_Text_AlixPostBattle:
	.string "Oh well. Think I’ll just\n"
	.string "TELEPORT back to the ends.$"

Route115_Text_MarleneIntro:
	.string "You’ve disturbed my meditation…\n"
	.string "You’re gonna have to pay for that.$"

Route115_Text_MarleneDefeat:
	.string "You’ve completely broken my focus!$"

Route115_Text_MarlenePostBattle:
	.string "I was trying to meditate with the\n"
	.string "squad, but the vibe here is dead.$"

Route116_Text_ClarkIntro:
	.string "If the tunnel isn't open, I’ll just\n"
	.string "go over the top. Light work.$"

Route116_Text_ClarkDefeat:
	.string "Gasp… Gasp…\n"
	.string "Taking an L is exhausting…$"

Route116_Text_ClarkPostBattle:
	.string "Tunnel or no tunnel, it’s nothing.\n"
	.string "To a HIKER, the mountain IS the road!$"

Route116_Text_JoeyIntro:
	.string "My squad is legendary!\n"
	.string "Check the levels!$"

Route116_Text_JoeyDefeat:
	.string "Ouch! A scrape!\n"
	.string "Need a bandage on that, quick!$"

Route116_Text_JoeyPostBattle:
	.string "Bandages are a sign of toughness!\n"
	.string "See? I’ve got bare ones!$"

Route116_Text_JoseIntro:
	.string "My BUG POKéMON are built different!\n"
	.string "Let’s scrap!$"

Route116_Text_JoseDefeat:
	.string "I lost!\n"
	.string "I thought I had you in the bag!$"

Route116_Text_JosePostBattle:
	.string "BUG POKéMON evolve fast. That’s why\n"
	.string "they get strong so quickly, fam.$"

Route116_Text_JaniceIntro:
	.string "Let me show you the power of a\n"
	.string "truly adorable squad!$"

Route116_Text_JaniceDefeat:
	.string "You’re a couple levels above me…$"

Route116_Text_JanicePostBattle:
	.string "A squad that has the looks and\n"
	.string "the power? That’s the dream.$"

Route116_Text_JerryIntro:
	.string "We learn all the theory at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "Time to see if the practice holds up!$"

Route116_Text_JerryDefeat:
	.string "I definitely slacked off in class…\n"
	.string "That’s why I took the L.$"

Route116_Text_JerryPostBattle:
	.string "I’m gonna have to retake those courses.\n"
	.string "If I don't, ROXANNE will be fuming.$"

Route116_Text_JerryRegister1:
	.string "They said in class that a POKéNAV can\n"
	.string "register other TRAINERS.\p"
	.string "Don't really get the tech, but\n"
	.string "can I try it out on you?$"

Route116_Text_JerryRegister2:
	.string "I heard at SCHOOL that POKéNAVS are\n"
	.string "the way to keep in touch.\p"
	.string "Can we try registering? For science?$"

Route116_Text_JerryRematchIntro:
	.string "I’ve been hitting the books at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "No way I lose like last time.$"

Route116_Text_JerryRematchDefeat:
	.string "Hunh?\n"
	.string "But I studied so hard!$"

Route116_Text_JerryPostRematch:
	.string "Retakes for me, definitely.\n"
	.string "ROXANNE’s gonna be so steamed…$"

Route116_Text_KarenIntro:
	.string "I study at school, then I study on\n"
	.string "the commute home, too! No breaks!$"

Route116_Text_KarenDefeat:
	.string "I'm in shock—I actually lost?$"

Route116_Text_KarenPostBattle:
	.string "Awww, I’m never gonna be an elite\n"
	.string "TRAINER like ROXANNE at this rate!$"

Route116_Text_KarenRegister1:
	.string "Oh, wow! Is that a POKéNAV?\n"
	.string "I’ve got one, too! Register me, quick!$"

Route116_Text_KarenRegister2:
	.string "Wait, let's link up on the POKéNAV!\n"
	.string "I need more strong contacts!$"

Route116_Text_KarenRematchIntro:
	.string "I’ve put in bare hours since we met.\n"
	.string "Check out the results!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm in shock.\n"
	.string "Another L? How?$"

Route116_Text_KarenPostRematch:
	.string "You’ve actually beaten ROXANNE?\n"
	.string "Then I stood no chance. Not yet.$"

Route116_Text_SarahIntro:
	.string "Just so you’re aware, I’ve never once\n"
	.string "been beaten at anything. Ever.$"

Route116_Text_SarahDefeat:
	.string "Oh, my goodness.\n"
	.string "This is a new experience for me.$"

Route116_Text_SarahPostBattle:
	.string "My luxury life gives me everything\n"
	.string "I could ever want.\p"
	.string "But with POKéMON, my bank account\n"
	.string "doesn't mean a thing. Peak.$"

Route116_Text_DawsonIntro:
	.string "When you see my squad’s elite fur,\n"
	.string "you’ll be too dazzled to move!$"

Route116_Text_DawsonDefeat:
	.string "Oh, baby, tell me it ain't so!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"
	.string "You’ve messed up the fur coat!\l"
	.string "You’ve ruined my trim, too!\l"
	.string "I need my stylist on the phone, NOW!$"

Route116_Text_DevanIntro:
	.string "We're gonna rock you proper!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "Not even a contest!$"

Route116_Text_DevanPostBattle:
	.string "I should probably try some different\n"
	.string "types. That’s the play.$"

Route116_Text_JohnsonIntro:
	.string "It's a dead end up here.\n"
	.string "I'm bored, you want to scrap?$"

Route116_Text_JohnsonDefeat:
	.string "That was a vibe even though I lost.$"

Route116_Text_JohnsonPostBattle:
	.string "You want to stay here and keep\n"
	.string "me company for a bit?$"

Route117_Text_IsaacIntro:
	.string "Yo, could you test out the squad\n"
	.string "I’ve been raising?$"

Route117_Text_IsaacDefeat:
	.string "You’ve raised yours superbly, fam…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON isn't just about the power.\p"
	.string "Polishing a unique vibe is another\n"
	.string "way to enjoy the game.$"

Route117_Text_IsaacRegister:
	.string "I’m gonna double down on the grind.\n"
	.string "Come back and check on us later?$"

Route117_Text_IsaacRematchIntro:
	.string "The squad I’ve been raising is looking\n"
	.string "cold, just like last time.$"

Route117_Text_IsaacRematchDefeat:
	.string "You really know how to train 'em.\n"
	.string "You’ve got DAY CARE skills, truss.$"

Route117_Text_IsaacPostRematch:
	.string "Your squad is moving right!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "Please, allow me to check if your\n"
	.string "squad is being raised properly.$"

Route117_Text_LydiaDefeat:
	.string "Yes, they’re growing proper.$"

Route117_Text_LydiaPostBattle:
	.string "Try raising POKéMON with more\n"
	.string "focus on their individual traits.$"

Route117_Text_LydiaRegister:
	.string "I’m glad I met an elite TRAINER like you.\n"
	.string "I hope our paths cross again.$"

Route117_Text_LydiaRematchIntro:
	.string "Allow me to re-evaluate if you’ve\n"
	.string "kept up the standard with your squad.$"

Route117_Text_LydiaRematchDefeat:
	.string "They are growing admirably, truss.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON seem to rate different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:
	.string "I’m mid-triathlon right now, but\n"
	.string "whatever—let’s have a quick scrap!$"

Route117_Text_DylanDefeat:
	.string "I’ve run out of gas!$"

Route117_Text_DylanPostBattle:
	.string "I might have blown the lead…\p"
	.string "I probably dropped to last place\n"
	.string "during that battle. Peak.$"

Route117_Text_DylanRegister:
	.string "POKéMON have to be fit, too?\n"
	.string "I need you to show me the ropes!$"

Route117_Text_DylanRematchIntro:
	.string "I’m smack in the middle of a triathlon,\n"
	.string "but I’m comfortably ahead.\l"
	.string "Let’s make this a quick one!$"

Route117_Text_DylanRematchDefeat:
	.string "I’ve run out of gas again!$"

Route117_Text_DylanPostRematch:
	.string "I was top-tier in swimming and cycling,\n"
	.string "but I’m not quite that confident with\l"
	.string "the POKéMON game yet.$"

Route117_Text_MariaIntro:
	.string "I do my triathlon training with my\n"
	.string "squad, so my speed is unreal.$"

Route117_Text_MariaDefeat:
	.string "I need to get more reps in,\n"
	.string "I guess.$"

Route117_Text_MariaPostBattle:
	.string "The grind is only meaningful if you\n"
	.string "keep it up daily.\p"
	.string "Safe! I’ll resume the training!\n"
	.string "Starting tomorrow!$"

Route117_Text_MariaRegister:
	.string "You seem to be training proper…\n"
	.string "If you’re up for it, let's link later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your reps?\n"
	.string "I sure am!\l"
	.string "Let me show you the results!$"

Route117_Text_MariaRematchDefeat:
	.string "I need to get more practice in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:
	.string "Back to the grind tomorrow.\n"
	.string "Let’s scrap again sometime!$"

Route117_Text_DerekIntro:
	.string "Once a BUG CATCHER!\n"
	.string "Now a full-blown BUG MANIAC!\p"
	.string "But the love for the squad remains\n"
	.string "unchanged, fam!$"

Route117_Text_DerekDefeat:
	.string "My lack of skill also remains\n"
	.string "unchanged…$"

Route117_Text_DerekPostBattle:
	.string "I just followed my heart, and now\n"
	.string "the mandem call me a BUG MANIAC…\p"
	.string "Still, I’m an expert on the BUG types,\n"
	.string "so the name fits, innit.$"

Route117_Text_AnnaIntro:
	.string "ANNA: I’m with my junior student today.\n"
	.string "I have to move proper!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: I’m with my junior student!\n"
	.string "You were supposed to let me win!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Your squad has some cold\n"
	.string "combinations.\p"
	.string "I’d say you’re second only to us!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: We can't just take this L!\n"
	.string "You’ll come back for a rematch, yeah?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: If you want to step to us,\n"
	.string "bring two POKéMON with you.$"

Route117_Text_MegIntro:
	.string "MEG: I’m tagging up with my senior\n"
	.string "mentor to smoke you!$"

Route117_Text_MegDefeat:
	.string "MEG: Oh, no!\n"
	.string "I’m sorry, ANNA! I flopped…$"

Route117_Text_MegPostBattle:
	.string "MEG: I dragged ANNA down…\n"
	.string "If it wasn't for me, she’d have won!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't scrap with you, then.\p"
	.string "We only do 2-on-2 battles.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: I can't keep taking Ls in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: I just couldn't get in the zone.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Your squad has elite chemistry.\p"
	.string "I’d say you’re second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: If you want to scrap with us,\n"
	.string "you need two POKéMON, fam.$"

Route117_Text_MegRematchIntro:
	.string "MEG: I’m tagging up with my senior\n"
	.string "partner and winning this time!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Way too strong!$"

Route117_Text_MegPostRematch:
	.string "MEG: I teamed up with my senior,\n"
	.string "but we still lost…\p"
	.string "That’s so discouraging, man…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Only one POKéMON?\n"
	.string "We can't battle you like that.\p"
	.string "We’re out here for 2-on-2s.$"

Route117_Text_MelinaIntro:
	.string "Isn't it a vibe? To scrap while looking\n"
	.string "at all these pretty flowers?$"

Route117_Text_MelinaDefeat:
	.string "Oh, that’s actually impressive!$"

Route117_Text_MelinaPostBattle:
	.string "It feels wonderful to go for a jog\n"
	.string "and take in the scenery.$"

Route117_Text_BrandiIntro:
	.string "Let me show you the hidden tech\n"
	.string "inside a PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Astonishing! Mad levels!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC types are complex, fam.\n"
	.string "You should try copping some.$"

Route117_Text_AishaIntro:
	.string "Focus 100% on getting the W.\n"
	.string "That’s how I move!$"

Route117_Text_AishaDefeat:
	.string "I don't waste time being vexed over\n"
	.string "a loss—I’d rather just train.$"

Route117_Text_AishaPostBattle:
	.string "I think if you're worried about the L,\n"
	.string "you're more likely to take one.$"

Route118_Text_RoseIntro:
	.string "The aroma of flowers is a vibe.\n"
	.string "It cleanses the body and soul, truss.$"

Route118_Text_RoseDefeat:
	.string "Oh, dear me.\n"
	.string "I seem to have lost.$"

Route118_Text_RosePostBattle:
	.string "Flowers, POKéMON…\n"
	.string "I love anything that smells peng.\p"
	.string "Stinky things?\n"
	.string "I’ll pass on that.$"

Route118_Text_RoseRegister:
	.string "Sniff… That scent—it’s a POKéNAV!\n"
	.string "We have to link up right now!$"

Route118_Text_RoseRematchIntro:
	.string "Were you drawn here by the sweet\n"
	.string "aroma, fam?$"

Route118_Text_RoseRematchDefeat:
	.string "The power of aroma…\n"
	.string "It didn't seem to do much today.$"

Route118_Text_RosePostRematch:
	.string "If you use a sweet aroma properly,\n"
	.string "the squad will be drawn to it.$"

Route118_Text_PerryIntro:
	.string "BIRD POKéMON that FLY elegantly in\n"
	.string "the sky… They’re the goats!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "I crashed out…$"

Route118_Text_PerryPostBattle:
	.string "You’ve got a legendary squad.\n"
	.string "I’ll have to train mine better.$"

Route118_Text_ChesterIntro:
	.string "Take flight!\n"
	.string "My BIRD squad!$"

Route118_Text_ChesterDefeat:
	.string "Well, they took flight, alright…$"

Route118_Text_ChesterPostBattle:
	.string "If they get stronger, they’ll be able\n"
	.string "to fly even more freely…$"

Route118_Text_BarnyIntro:
	.string "I’m a FISHERMAN, but also a TRAINER.\n"
	.string "I’m raising the POKéMON I hooked.$"

Route118_Text_BarnyDefeat:
	.string "I thought my training was going\n"
	.string "well, you know?$"

Route118_Text_BarnyPostBattle:
	.string "I couldn't win by training the squad\n"
	.string "while I fished…\p"
	.string "Was I moving with half measures?$"

Route118_Text_WadeIntro:
	.string "For FISHERMEN, the gear is key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are the squad and the heart, truss!$"

Route118_Text_WadeDefeat:
	.string "Beaten in heart? Violation.$"

Route118_Text_WadePostBattle:
	.string "Come to think of it, fishing is just a\n"
	.string "scrap between a man and a POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Let my melody rock your soul, fam!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala… (A minor key L)$"

Route118_Text_DaltonPostBattle:
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody…$"

Route118_Text_DaltonRegister:
	.string "When I’ve composed a better track,\n"
	.string "you have to come listen, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "A melody from the squad and me…\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala… Still out of tune.$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my emotions should reach\n"
	.string "you through the electric guitar…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go!\n"
	.string "POKéMON 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "Come in, squad! Are you okay?\n"
	.string "Numbers 1, 2, and 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Isn't it cool that I have an actual\n"
	.string "battle team system?\p"
	.string "You can copy the tech—I don't mind!$"

Route119_Text_BrentIntro:
	.string "We're the MIMIC CIRCLE!\n"
	.string "We copy your every move!$"

Route119_Text_BrentDefeat:
	.string "Whoopsie!\n"
	.string "I took the L!$"

Route119_Text_BrentPostBattle:
	.string "What's the hype about mimicry?\p"
	.string "Fufufu…\n"
	.string "You'll never understand the vibe…$"

Route119_Text_DonaldIntro:
	.string "So, we finally meet!\n"
	.string "My BUG squad will keep you company!$"

Route119_Text_DonaldDefeat:
	.string "I wish we’d never crossed paths…$"

Route119_Text_DonaldPostBattle:
	.string "I’m tryna MIMIC you some more.\n"
	.string "Can you hurry up and move, fam?$"

Route119_Text_TaylorIntro:
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we’re turning too…$"

Route119_Text_TaylorDefeat:
	.string "But if you win, I take the L…$"

Route119_Text_TaylorPostBattle:
	.string "I can’t MIMIC you winning the scrap.\n"
	.string "That’s just impossible…\l"
	.string "It’s actually burning me up…$"

Route119_Text_DougIntro:
	.string "Yep, you’ve finally caught me!\n"
	.string "Or were you tryna duck me?$"

Route119_Text_DougDefeat:
	.string "Whoop, that was a legendary match!$"

Route119_Text_DougPostBattle:
	.string "We’re the MIMIC CIRCLE!\n"
	.string "Hope you rated the performance.$"

Route119_Text_GregIntro:
	.string "You don’t know who I am, do you?\p"
	.string "But I don't know you either, so\n"
	.string "it’s only right we battle!$"

Route119_Text_GregDefeat:
	.string "You’re moving proper strong!$"

Route119_Text_GregPostBattle:
	.string "Until you move out the area, we’re\n"
	.string "gonna keep mimicking every step.$"

Route119_Text_KentIntro:
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who just love to MIMIC.\p"
	.string "It’s on sight the moment we meet!$"

Route119_Text_KentDefeat:
	.string "I’m done! I give up!$"

Route119_Text_KentPostBattle:
	.string "You want in on the MIMIC CIRCLE?$"

Route119_Text_JacksonIntro:
	.string "Who’s got the survival tech and\n"
	.string "the knowledge of the wild?\p"
	.string "POKéMON RANGERS, that’s who!$"

Route119_Text_JacksonDefeat:
	.string "I didn’t have enough POKéMON\n"
	.string "know-how…$"

Route119_Text_JacksonPostBattle:
	.string "To cut off civilization and awaken\n"
	.string "the wild spirit within!\p"
	.string "That’s the vision, fam.$"

Route119_Text_JacksonRegister:
	.string "I hope you’ll give me a run-back without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro:
	.string "I’m gonna regain that wild spirit by\n"
	.string "grinding alongside my squad.$"

Route119_Text_JacksonRematchDefeat:
	.string "You’ve stayed elite!$"

Route119_Text_JacksonPostRematch:
	.string "Trust in your squad.\n"
	.string "Trust in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:
	.string "Oh? Look at you.\p"
	.string "For someone on a journey, you’re\n"
	.string "traveling awfully light, innit?$"

Route119_Text_CatherineDefeat:
	.string "Accidents happen when you’re not\n"
	.string "prepared for the roads!$"

Route119_Text_CatherinePostBattle:
	.string "You’re traveling light but you’ve got\n"
	.string "the essentials.\p"
	.string "You’re sharp mentally and physically,\n"
	.string "I rate that.$"

Route119_Text_CatherineRegister:
	.string "You got a POKéNAV? It’s a must-have\n"
	.string "tool for any serious TRAINER.\p"
	.string "Oh, you’re already on it!\n"
	.string "Let’s exchange details, then!$"

Route119_Text_CatherineRematchIntro:
	.string "How’s the journey with the squad\n"
	.string "going lately?$"

Route119_Text_CatherineRematchDefeat:
	.string "I’m still missing a bit of tech…$"

Route119_Text_CatherinePostRematch:
	.string "Just like you rely on your squad,\n"
	.string "your squad is counting on you.$"

Route119_Text_HughIntro:
	.string "The vast sky holds untold promise!\p"
	.string "Nothing compares to the sheer\n"
	.string "exhilaration of being airborne!$"

Route119_Text_HughDefeat:
	.string "Down and out! Grounded!$"

Route119_Text_HughPostBattle:
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flight a reality, truss.$"

Route119_Text_PhilIntro:
	.string "I’ll show you the true potential of\n"
	.string "me and my BIRD squad!$"

Route119_Text_PhilDefeat:
	.string "We lacked potential today…$"

Route119_Text_PhilPostBattle:
	.string "Ever since I was a little kid, I always\n"
	.string "admired the BIRD POKéMON…$"

Route119_Text_YasuIntro:
	.string "To lurk in shadows and live in the\n"
	.string "darkness… That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:
	.string "I admit the L!$"

Route119_Text_YasuPostBattle:
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows.\l"
	.string "That, too, is destiny…$"

Route119_Text_TakashiIntro:
	.string "If you’re not on your guard,\n"
	.string "you’re in for a world of pain!$"

Route119_Text_TakashiDefeat:
	.string "You’re surprisingly elite!$"

Route119_Text_TakashiPostBattle:
	.string "My surprise attack was a total\n"
	.string "failure…$"

Route119_Text_HideoIntro:
	.string "To hide a tree, use a forest!$"

Route119_Text_HideoDefeat:
	.string "I bow to your superiority, fam.$"

Route119_Text_HideoPostBattle:
	.string "To hide a tree, use a forest!\n"
	.string "To hide a POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning\n"
	.string "to that. It’s just logic.$"

Route119_Text_ChrisIntro:
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I’ll test out the squad I\n"
	.string "caught while SURFING!$"

Route119_Text_ChrisDefeat:
	.string "I don’t have a clue what it\n"
	.string "actually takes to win.$"

Route119_Text_ChrisPostBattle:
	.string "Going for a SURF on my POKéMON…\p"
	.string "Then fishing off its back…\p"
	.string "It’s a luxury vibe, I can’t even lie.$"

Route119_Text_FabianIntro:
	.string "Hit me with a power chord!\n"
	.string "The W is mine!\l"
	.string "It’s our time to shine, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "You showed me who’s the boss!\n"
	.string "Taking the L, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Hit me with another power chord!\n"
	.string "Leave me alone!\l"
	.string "Your win is a violation, oh!$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "I like these kid TRAINERS!\l"
	.string "Let’s have a proper one!$"

Route119_Text_DaytonDefeat:
	.string "You’re actually amazing!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "I’ll try emulating the energy of kid\l"
	.string "TRAINERS like you! It’s inspiring.$"

Route119_Text_RachelIntro:
	.string "Wherever and whenever I may be,\n"
	.string "I always have my parasol in hand.$"

Route119_Text_RachelDefeat:
	.string "Oh, but…\n"
	.string "That’s not fair at all.$"

Route119_Text_RachelPostBattle:
	.string "You’re asking if my parasol is heavy?\n"
	.string "Your BAG is filled with more junk than\l"
	.string "I’d ever carry around, darling.$"

Route120_Text_ColinIntro:
	.string "You got any moves that can actually\n"
	.string "touch a flying POKéMON?$"

Route120_Text_ColinDefeat:
	.string "You soared right above me!$"

Route120_Text_ColinPostBattle:
	.string "The move FLY is proper convenient,\n"
	.string "don’t you think?\p"
	.string "While they’re airborne,\n"
	.string "almost nothing can touch them.$"

Route120_Text_RobertIntro:
	.string "My squad is strong!\n"
	.string "How’s yours looking?$"

Route120_Text_RobertDefeat:
	.string "Your squad was stronger…$"

Route120_Text_RobertPostBattle:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can always count on, truss.$"

Route120_Text_RobertRegister:
	.string "I can count on you to keep improving.\n"
	.string "I’m registering you in my POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can always count on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your squad is seriously strong, fam.$"

Route120_Text_RobertPostRematch:
	.string "My squad is growing stronger.\n"
	.string "I have to level up my own game, too.$"

Route120_Text_LorenzoIntro:
	.string "I’ll check your squad and see if\n"
	.string "they’re fit for the outdoors.$"

Route120_Text_LorenzoDefeat:
	.string "With POKéMON that strong, you don't\n"
	.string "need a rescue service, ever!$"

Route120_Text_LorenzoPostBattle:
	.string "To travel wherever your heart desires\n"
	.string "with your squad…\l"
	.string "That’s the joy of being a TRAINER.$"

Route120_Text_JennaIntro:
	.string "How’s your physical fitness?\n"
	.string "If you’re not fit, you’ll have a\l"
	.string "rough time in a crisis, truss.$"

Route120_Text_JennaDefeat:
	.string "I’m totally fit, but still…$"

Route120_Text_JennaPostBattle:
	.string "Fitness training is my daily routine.\n"
	.string "I always run with my squad.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to scrap?$"

Route120_Text_JeffreyDefeat:
	.string "Lost it… My head's gone…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I’ll grind harder…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "You got a POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want a run-back?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Another L for me…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I’ll grind harder…\l"
	.string "For my precious BUG squad…$"

Route120_Text_JenniferIntro:
	.string "POKéMON have bare special abilities.\n"
	.string "If you want to be an elite TRAINER,\l"
	.string "you need to learn the tech.$"

Route120_Text_JenniferDefeat:
	.string "You’re clearly thinking ahead.$"

Route120_Text_JenniferPostBattle:
	.string "Special abilities change the whole\n"
	.string "meta of the battle, truss.$"

Route120_Text_ChipIntro:
	.string "Who might you be?\p"
	.string "Are you scouting for those ancient\n"
	.string "ruins from the legends?$"

Route120_Text_ChipDefeat:
	.string "What a disgraceful setback…$"

Route120_Text_ChipPostBattle:
	.string "That massive rock… I’m convinced there\n"
	.string "are ruins inside. But I can't find\l"
	.string "the entrance anywhere, fam.$"

Route120_Text_ClarissaIntro:
	.string "Why the parasol? Easy.\p"
	.string "I’ll tell you if you can actually\n"
	.string "beat me in a scrap.$"

Route120_Text_ClarissaDefeat:
	.string "A parasol can’t block POKéMON\n"
	.string "attacks, clearly…$"

Route120_Text_ClarissaPostBattle:
	.string "I don’t think peak sunlight is good\n"
	.string "for my squad’s skin.\l"
	.string "So I shield them with the brolly.$"

Route120_Text_AngelicaIntro:
	.string "Me, the squad, and my parasol…\p"
	.string "If even one is missing, the whole\n"
	.string "aesthetic is ruined, darling.$"

Route120_Text_AngelicaDefeat:
	.string "You’ve completely ruined my vibe…$"

Route120_Text_AngelicaPostBattle:
	.string "A parasol wouldn’t suit you at all.\p"
	.string "It’d just get in your way while\n"
	.string "you’re out here running about.$"

Route120_Text_KeigoIntro:
	.string "I’m studying POKéMON movements to\n"
	.string "invent some fresh ninja tech.$"

Route120_Text_KeigoDefeat:
	.string "The new ninja tech is still a\n"
	.string "distant dream…$"

Route120_Text_KeigoPostBattle:
	.string "Maybe I need to apprentice under\n"
	.string "an actual ninja sensei.$"

Route120_Text_RileyIntro:
	.string "We ninjas move silent in our\n"
	.string "camo cloaks.\l"
	.string "Bet you didn't even see me!$"

Route120_Text_RileyDefeat:
	.string "I lost!\n"
	.string "I need to camouflage my shame!$"

Route120_Text_RileyPostBattle:
	.string "These camo cloaks are all\n"
	.string "handmade, you know.$"

Route120_Text_CallieIntro:
	.string "If you aren't paying attention,\n"
	.string "you’re gonna get hurt!$"

Route120_Text_CallieDefeat:
	.string "Ouch!\n"
	.string "I’m the one who got hurt!$"

Route120_Text_CalliePostBattle:
	.string "I wonder… should I evolve the squad?\n"
	.string "They’re so cute as they are, though.$"

Route120_Text_LeonelIntro:
	.string "Your party…\n"
	.string "You got a good mix of types?$"

Route120_Text_LeonelDefeat:
	.string "I’ve seen your strategy in action!$"

Route120_Text_LeonelPostBattle:
	.string "It’s actually cold how strong you are\n"
	.string "using just your favorite POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Want to play with my delightfully\n"
	.string "pretty squad?$"

Route121_Text_VanessaDefeat:
	.string "This isn’t what I meant at all!$"

Route121_Text_VanessaPostBattle:
	.string "I’m heading to a CONTEST in LILYCOVE.\p"
	.string "My squad is definitely gonna sweep\n"
	.string "the MASTER CLASS, no cap.$"

Route121_Text_WalterIntro:
	.string "I’ve traveled to the world’s four\n"
	.string "corners with my squad.\p"
	.string "You could say I’ve got some serious\n"
	.string "confidence in my game.$"

Route121_Text_WalterDefeat:
	.string "Ah, well played, fam.$"

Route121_Text_WalterPostBattle:
	.string "I’d love to circle the globe one\n"
	.string "more time with my POKéMON.$"

Route121_Text_WalterRegister:
	.string "Your POKéMON prowess is legendary.\n"
	.string "Let’s exchange details as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "Back from my travels!\p"
	.string "Let’s see if I’ve picked up any new\n"
	.string "international tech since last time.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, still well played.$"

Route121_Text_WalterPostRematch:
	.string "You and your squad…\p"
	.string "That kind of chemistry would be\n"
	.string "rated highly anywhere in the world.$"

Route121_Text_TammyIntro:
	.string "There are powers in this world that\n"
	.string "we just don't understand…$"

Route121_Text_TammyDefeat:
	.string "I’ve taken the L…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "There’s some mysterious energy\l"
	.string "at work up there, truss.$"

Route121_Text_KateIntro:
	.string "KATE: Together, we’ve got no fear!\n"
	.string "Check the levels on us!$"

Route121_Text_KateDefeat:
	.string "KATE: I flopped right in front of\n"
	.string "my junior student partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone’s looking up to me,\n"
	.string "I just want to look elite for them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you’ve only got one POKéMON,\n"
	.string "we can't battle you.\p"
	.string "That’d just be a violation.$"

Route121_Text_JoyIntro:
	.string "JOY: Together, we’re fearless!\n"
	.string "We’ll show you how we move!$"

Route121_Text_JoyDefeat:
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, I need to train with KATE,\n"
	.string "my senior student, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: You need at least two POKéMON\n"
	.string "if you’re gonna step to us!$"

Route121_Text_JessicaIntro:
	.string "Stop! Get a proper look at my\n"
	.string "precious squad!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you!\n"
	.string "Why are you taking it so seriously?$"

Route121_Text_JessicaPostBattle:
	.string "Maybe I’ll go catch some fresh types\n"
	.string "at the SAFARI ZONE.$"

Route121_Text_JessicaRegister:
	.string "I was taking it easy on you!\n"
	.string "Next time, the gloves are off!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious squad has leveled up!\n"
	.string "Take a look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won’t go easy on me!$"

Route121_Text_JessicaPostRematch:
	.string "Back to the SAFARI ZONE for me.\n"
	.string "I need more recruits.$"

Route121_Text_CristinIntro:
	.string "I have a routine.\n"
	.string "Smoke five TRAINERS a day.\l"
	.string "Guess what? You’re number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You’re actually horrid!$"

Route121_Text_CristinPostBattle:
	.string "I didn’t expect to lose that easily…\n"
	.string "I’ll get the W next time!$"

Route121_Text_CristinRegister:
	.string "Total humiliation!\n"
	.string "I’m not forgetting this…\l"
	.string "Hand over your POKéNAV details!$"

Route121_Text_CristinRematchIntro:
	.string "New routine.\n"
	.string "Smoke ten TRAINERS a day.\l"
	.string "Guess what? You’re number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That’s nasty!\n"
	.string "I demand a run-back!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can’t beat…\n"
	.string "Snivel…\l"
	.string "I can’t believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can’t you see I’m carrying bare\n"
	.string "shopping, fam?\p"
	.string "And you still want to scrap?$"

Route121_Text_CaleDefeat:
	.string "Of course I lost!\n"
	.string "I’ve got bags in both hands!$"

Route121_Text_CalePostBattle:
	.string "I bought way too much stuff at the\n"
	.string "LILYCOVE DEPT. STORE.\p"
	.string "It’s just up the road. I wish I had\n"
	.string "a BAG as big as yours, honestly.$"

Route121_Text_MylesIntro:
	.string "There’s nothing I love more than\n"
	.string "checking out other people’s squads!$"

Route121_Text_MylesDefeat:
	.string "Super awesome! Total madness!$"

Route121_Text_MylesPostBattle:
	.string "Your squad is elite, fam!\n"
	.string "How are you even raising them?$"

Route121_Text_PatIntro:
	.string "I want everyone to see the squad\n"
	.string "I’ve been grinding with!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spectacular levels!$"

Route121_Text_PatPostBattle:
	.string "I raise every POKéMON with the same\n"
	.string "love and care—I don’t pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My squad has never taken an L!\n"
	.string "After this win, I’m entering them\l"
	.string "into CONTESTS, truss.$"

Route121_Text_MarcelDefeat:
	.string "Oh, what’s actually happened here?$"

Route121_Text_MarcelPostBattle:
	.string "I might need to train the gang a bit\n"
	.string "more before we hit the stage.$"

Route123_Text_WendyIntro:
	.string "Want to see if you’re actually fit\n"
	.string "for this? I’ll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "To smoke even me…\n"
	.string "Your power is marvelous, fam!$"

Route123_Text_BraxtonIntro:
	.string "You’ve got a big collection of\n"
	.string "GYM BADGES there.\p"
	.string "Let’s see if you’re actually worthy\n"
	.string "of that hardware!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you’re worthy, no cap!$"

Route123_Text_BraxtonPostBattle:
	.string "You did those BADGES proud in that\n"
	.string "match, truss!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of an L…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER’s garden is filled\n"
	.string "with uplifting fragrances, innit.$"

Route123_Text_CameronIntro:
	.string "Being psychic is all about willpower.\p"
	.string "I’ve manifested a win-streak that\n"
	.string "won't end. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "Now I just feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Psychic power is about the mind.\n"
	.string "I really thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I are gonna scrap again!\l"
	.string "Can’t tell if I’ll win, though…\p"
	.string "Let’s see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I’ve convinced myself I’m not taking\n"
	.string "any more Ls. My mindset is elite!$"

Route123_Text_CameronRematchDefeat:
	.string "Vibe check failed… I’m sad…$"

Route123_Text_CameronPostRematch:
	.string "I should go train at MT. PYRE…\n"
	.string "I’m never gonna beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don’t get gassed if your squad\n"
	.string "develops psychic powers.\p"
	.string "You need to refine that tech to\n"
	.string "make it really useful.$"

Route123_Text_JackiDefeat:
	.string "Completely overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers, fam.\n"
	.string "We just forgot how to use 'em.$"

Route123_Text_JackiRegister:
	.string "I want to face you again.\n"
	.string "Is that cool with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic tech\n"
	.string "buried deep within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding! Mad levels!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic ability, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "squad won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we took the L.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your squad is strong\n"
	.string "because you're actually friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It’s no fun to scrap if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We’re gonna smoke this TRAINER!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We’ve literally never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It’s dead to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Is your squad ready to rest?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must be full of a power that\n"
	.string "soothes the soul, truss.$"

Route123_Text_FernandoIntro:
	.string "I’ll turn your lights out while\n"
	.string "I rip through this solo!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You’re rock steady, fam.\n"
	.string "I’d love to write a track about you.$"

Route123_Text_FernandoRegister:
	.string "Next time, make sure you listen to\n"
	.string "the full song, yeah?$"

Route123_Text_FernandoRematchIntro:
	.string "Today’s the day I’m doing it!\n"
	.string "Lights out before the first chorus!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the bridge yet!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you’d be so gassed by my\n"
	.string "tune that you’d just forfeit.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother copped it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You’re a meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret, safe?$"

Route123_Text_JazmynIntro:
	.string "My confidence is gonna peak once\n"
	.string "I smoke someone as strong as you!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say you can't judge a book by\n"
	.string "its cover.\p"
	.string "But usually, the looks don’t lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time for an elder?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your pocket money.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough, fam?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my absolute obsession!\p"
	.string "Birds are elite!\n"
	.string "They're the goats!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cold!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather feathers that fly off\n"
	.string "during the scraps.\p"
	.string "I’m gonna make a legendary hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS about,\n"
	.string "I let my squad scrap each other.\l"
	.string "I just like to watch.$"

Route123_Text_EdDefeat:
	.string "I actually quite like your squad.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I’m swiping your battle tech!\n"
	.string "I think it’ll make me much better.$"

Route123_Text_JonasIntro:
	.string "I was lying in ambush, and a TRAINER\n"
	.string "just walked into the trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I’m gonna ambush a weaker-looking\n"
	.string "TRAINER next time. No more risks.$"

Route123_Text_KayleyIntro:
	.string "I just copped this parasol.\n"
	.string "My cuteness levels should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You’re better than me by about\n"
	.string "five times, it’s a joke!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the real secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Yo, you lost at sea, fam?\p"
	.string "If you can beat my squad,\n"
	.string "I’ll serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in the scrap!$"

Route124_Text_SpencerPostBattle:
	.string "Plenty of man lose their way at sea.\p"
	.string "If you’re that type, you should refer\n"
	.string "to the POKéNAV's MAP, truss.$"

Route124_Text_RolandIntro:
	.string "Hm! You’re riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I’m actually bare jealous!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "I can’t move…$"

Route124_Text_RolandPostBattle:
	.string "I’m catching a chill…\n"
	.string "I’ve been in the water way too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, the squad comes around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, man.\n"
	.string "I’ve gone and taken the L.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed some POKéMON\n"
	.string "attack, and some just watch.\p"
	.string "I guess POKéMON have their own\n"
	.string "distinct personalities, innit.$"

Route124_Text_JennyRegister:
	.string "It’s just on a whim, but maybe I’ll\n"
	.string "get you to register me in the NAV.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS will step to you for a scrap!$"

Route124_Text_JennyRematchDefeat:
	.string "That’s strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I’ll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I’m getting bored of just swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea you were moving\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:
	.string "All the grind you put in must have\n"
	.string "given you these mad levels.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to move deep undercover.\l"
	.string "The depths are my domain, fam!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "I’m sinking…$"

Route124_Text_ChadPostBattle:
	.string "I have it on good authority that\n"
	.string "there’s a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again, truss…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Out here in the sea, but who’s with me?\n"
	.string "My annoying little brother!\p"
	.string "Let’s scrap so I can stop dwelling\n"
	.string "on it!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! It’s your fault we lost!\n"
	.string "You’re catching it later, I swear!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a peng boyfriend…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You tryna battle us?\n"
	.string "Not unless you have two POKéMON, fam.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is tough at this!\p"
	.string "Don’t cry when you take the L!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister is gonna chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is actually scary\n"
	.string "when she’s vexed.\p"
	.string "That’s why she hasn't got a\n"
	.string "boyfriend, innit.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, yeah?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to scrap?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Still stuck in the sea with my\n"
	.string "little brother!\p"
	.string "Oh, hi. Let's battle so I can take\n"
	.string "my mind off things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It’s your fault we lost again!\p"
	.string "Training session starts now!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a proper boyfriend, we’d smoke\n"
	.string "anyone with elite combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You planning to battle us?\n"
	.string "Need two POKéMON for that.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I’m gonna catch heck.\n"
	.string "I’m going 100% all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "Big sis is gonna roast me again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is terrifying\n"
	.string "when she’s angry.\p"
	.string "She’s gonna make me grind the squad\n"
	.string "until my fingers fall off…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: You want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There’s no other word for it.\n"
	.string "This is pathetic, fam!$"

Route124_Text_DeclanDefeat:
	.string "I’m feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I should try chat to the lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I’m not gonna lose to some\n"
	.string "random surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I’ve just got sweat in my eyes!\n"
	.string "I am definitely not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find bare pretty colored\n"
	.string "shards around these parts.$"

Route125_Text_NolenIntro:
	.string "I heard you approaching, so I hung\n"
	.string "about waiting for you!$"

Route125_Text_NolenDefeat:
	.string "I surrender!$"

Route125_Text_NolenPostBattle:
	.string "Sound travels faster in water than\n"
	.string "it does through air, trust.$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check the levels on my POKéMON!$"

Route125_Text_StanDefeat:
	.string "I flopped…$"

Route125_Text_StanPostBattle:
	.string "I was blown away by HORSEA’s charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I’m tired of swimming.\n"
	.string "You up for a scrap with me?$"

Route125_Text_TanyaDefeat:
	.string "You’re way too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Which way to MOSSDEEP CITY, fam?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "WATER-type squad I’ve raised?$"

Route125_Text_SharonDefeat:
	.string "Lost it… My head’s gone.$"

Route125_Text_SharonPostBattle:
	.string "Your power… You’re the real deal.\n"
	.string "I’m actually amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I’m a buff, tough SAILOR!\n"
	.string "I’ve braved the world’s seas, fam!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "I couldn’t get the W!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "Btw, it’s about six hours from high\n"
	.string "tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your NAV,\n"
	.string "and I’ll tell you some good tech.$"

Route125_Text_ErnestRematchIntro:
	.string "It’s high time I get my payback!\n"
	.string "Come on, it’s on sight!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn’t win!\n"
	.string "I flat out couldn’t win, man!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can’t get to\n"
	.string "depending on the rise of the tide.\p"
	.string "It’s six hours between high and low.\n"
	.string "Don’t forget the timing!$"

Route125_Text_KimIntro:
	.string "KIM: Some funny old man lives in the\n"
	.string "SHOAL CAVE. A little bird told me.\l"
	.string "Are you heading there, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I really thought we’d win.$"

Route125_Text_KimPostBattle:
	.string "KIM: There really is a funny old man\n"
	.string "in the SHOAL CAVE, innit?\p"
	.string "Let’s go find him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "otherwise it’s just dead!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, can you tell me what we’re\n"
	.string "actually looking for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going in?\n"
	.string "We’re gonna get soaking wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never do something\n"
	.string "as unfair as a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea, you ask?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "I’ll tell you why I’m here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and tossed\n"
	.string "it out to sea.\p"
	.string "I’m certain a girl SWIMMER will\n"
	.string "find it and hit me up!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the ocean?$"

Route125_Text_AuronDefeat:
	.string "Oh, okay. You weren't throwing trash\n"
	.string "into the sea. My bad.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It vexes me that people would just\n"
	.string "pollute the sea like that!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout, fam!\n"
	.string "You’re gonna get proper fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it!\n"
	.string "You got the W!$"

Route126_Text_BarryPostBattle:
	.string "Check the daily swimming routine…\n"
	.string "Feast your eyes on this physique, man!$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY, innit.$"

Route126_Text_DeanDefeat:
	.string "I actually got smoked?$"

Route126_Text_DeanPostBattle:
	.string "I can’t find the entrance to\n"
	.string "SOOTOPOLIS. Where’s it hiding, fam?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I’m a mermaid, darling!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst like a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to\n"
	.string "disappear into a wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want to scrap with me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "I love frolicking with the squad in\n"
	.string "the sea like this! High vibes!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body, fam!\n"
	.string "I’m more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you really woke me up!\n"
	.string "I’ll grind myself and the squad harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you’re not bad at all!\n"
	.string "I’d like to see how you move later!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful frame!\n"
	.string "I’m more shapely than any SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Truly too strong!\n"
	.string "Mad levels! Mad levels!$"

Route126_Text_PabloPostRematch:
	.string "I’m gonna train even harder!\n"
	.string "You’re a great motivator, truss!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn’t even swim last year,\n"
	.string "but now I’m a decent SWIMMER.\p"
	.string "I feel like I’m capable of anything!$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, getting greedy didn’t do\n"
	.string "a thing for me, did it?$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice, you’ll get better.\n"
	.string "Simple as that, fam.\p"
	.string "You’re young—don’t be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn’t it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub! Poisoned!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It’s bitter! It’s salty!! My head!$"

Route126_Text_SiennaIntro:
	.string "I’m throwing my whole heart\n"
	.string "into this scrap!$"

Route126_Text_SiennaDefeat:
	.string "You had more heart, clearly!$"

Route126_Text_SiennaPostBattle:
	.string "I need to cool down now…\n"
	.string "I think I’ll go for a DIVE.$"

Route127_Text_CamdenIntro:
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene, fam.$"

Route127_Text_DonnyIntro:
	.string "Do you have a rival whom you just\n"
	.string "hate to take an L against?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "I hate taking the L!$"

Route127_Text_DonnyPostBattle:
	.string "If you have a rival, don't you feel\n"
	.string "like you have to keep leveling up?$"

Route127_Text_JonahIntro:
	.string "Through fishing, I have attained a\n"
	.string "state of pure zen…\p"
	.string "Allow me to demonstrate…$"

Route127_Text_JonahDefeat:
	.string "Even though I’ve lost, my heart\n"
	.string "remains calm…$"

Route127_Text_JonahPostBattle:
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don’t tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "I can’t keep up with this!$"

Route127_Text_HenryPostBattle:
	.string "It’d be a madness if I actually\n"
	.string "hooked your tough squad!$"

Route127_Text_RogerIntro:
	.string "Well, hey! This is a match between\n"
	.string "a POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:
	.string "No! My line’s all tangled!\n"
	.string "The party’s over, fam!$"

Route127_Text_RogerPostBattle:
	.string "My fishing line’s doing a dance!\n"
	.string "The tangle tango! Hahaha!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON have elite vision.\n"
	.string "They spot prey from bare heights.$"

Route127_Text_AidanDefeat:
	.string "Whew… I give up.$"

Route127_Text_AidanPostBattle:
	.string "There’re lots of diving spots in\n"
	.string "the sea around here, truss.\p"
	.string "You can spot them from the sky\n"
	.string "because they’re a darker blue.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet, fam.\n"
	.string "That’ll toughen up your soles!$"

Route127_Text_KojiDefeat:
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels legendary.\n"
	.string "But your RUNNING SHOES are cool too.$"

Route127_Text_KojiRegister:
	.string "This is what I do to people who beat me!\n"
	.string "Let’s exchange details for later.$"

Route127_Text_KojiRematchIntro:
	.string "I still run barefoot every day.\n"
	.string "My soles are tough as boots!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a bit?\n"
	.string "So I can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "We should have a slow and methodical\n"
	.string "match, darling.$"

Route127_Text_AthenaDefeat:
	.string "You didn’t give me a chance to\n"
	.string "even think of a strategy.$"

Route127_Text_AthenaPostBattle:
	.string "When I’m surrounded by the blue sea\n"
	.string "and sky, it feels like time slows down.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY is still a long\n"
	.string "way off, isn't it…$"

Route128_Text_IsaiahDefeat:
	.string "My first W seems a long way off,\n"
	.string "too…$"

Route128_Text_IsaiahPostBattle:
	.string "My whole life has been about taking\n"
	.string "the L, but I’ll never give up!$"

Route128_Text_IsaiahRegister:
	.string "I know I’m not elite yet, but I think\n"
	.string "I can win eventually.\p"
	.string "Register me in your POKéNAV, yeah?$"

Route128_Text_IsaiahRematchIntro:
	.string "I’m still feeling good. I’ll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "I’ve yet to taste that first W…$"

Route128_Text_IsaiahPostRematch:
	.string "I’ll eventually reach EVER GRANDE\n"
	.string "where I can finally win…$"

Route128_Text_KatelynIntro:
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon, fam.\p"
	.string "It’s a grueling race, no cap.$"

Route128_Text_KatelynDefeat:
	.string "A POKéMON battle is grueling, too…$"

Route128_Text_KatelynPostBattle:
	.string "I have to ride a BIKE next, but…\n"
	.string "I’m about to throw in the towel…$"

Route128_Text_KatelynRegister:
	.string "Well, I may as well make the best\n"
	.string "of this. Remix sometime?$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But the road to\n"
	.string "the CHAMPION spot is just as long\l"
	.string "and grueling, truss me.$"

Route128_Text_KatelynRematchDefeat:
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving, innit…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to\n"
	.string "the challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "We’ve been grinding so hard to mount\n"
	.string "a POKéMON LEAGUE challenge…\p"
	.string "We can’t afford to take an L now!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "After all I’ve done to get here,\n"
	.string "I won’t give up after one setback.\l"
	.string "The grind continues, truss.$"

Route128_Text_RubenIntro:
	.string "There is no stronger TRAINER than me!\n"
	.string "I’m the GOAT!$"

Route128_Text_RubenDefeat:
	.string "This can’t be real life!$"

Route128_Text_RubenPostBattle:
	.string "There probably is no stronger TRAINER\n"
	.string "than you. Fair play, fam.$"

Route128_Text_WayneIntro:
	.string "I’m tryna hit EVER GRANDE, so I\n"
	.string "caught a POKéMON with WATERFALL\l"
	.string "just to scale the cliffs.$"

Route128_Text_WayneDefeat:
	.string "I’m absolutely crestfallen!$"

Route128_Text_WaynePostBattle:
	.string "Awww, allow it!\p"
	.string "My POKéMON knows WATERFALL, but\n"
	.string "I haven't got the SOOTOPOLIS BADGE!\l"
	.string "I’m stuck, man!$"

Route128_Text_HarrisonIntro:
	.string "You’re looking awfully tough.\n"
	.string "Wonder if I can even win this?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle:
	.string "There are elite TRAINERS galore\n"
	.string "around EVER GRANDE.\p"
	.string "Starting to think I might be out\n"
	.string "of my league, honestly.$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems bare harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat:
	.string "I couldn’t even see because of\n"
	.string "the glare. Total violation.$"

Route128_Text_CarleePostBattle:
	.string "I should head back soon.\n"
	.string "I need to reapply my sunscreen before\l"
	.string "I get cooked.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon, fam.\n"
	.string "I’m bare tense and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "I flopped the win!$"

Route129_Text_ChasePostBattle:
	.string "If I’m all tensed up, I won’t be able to\n"
	.string "give it 100%, truss.$"

Route129_Text_AllisonIntro:
	.string "I’m in the middle of a triathlon,\n"
	.string "but sure, let’s have a scrap.$"

Route129_Text_AllisonDefeat:
	.string "I was certain I’d win that!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know what’s the best thing\n"
	.string "about triathlons?\p"
	.string "Testing your endurance against the\n"
	.string "elements! It’s legendary!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey!\n"
	.string "Let’s get on with it!$"

Route129_Text_ReedDefeat:
	.string "Beat? I’m finished.\n"
	.string "That’s it, done!$"

Route129_Text_ReedPostBattle:
	.string "There’s nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What’s the rush, fam?\n"
	.string "Let’s take it slow and easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle:
	.string "Don’t you hate making mistakes when\n"
	.string "you’re in a rush?\p"
	.string "That’s why I keep it low-tempo.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn’t as easy as it looks,\n"
	.string "is it?$"

Route129_Text_ClarenceDefeat:
	.string "Winning definitely isn’t easy.$"

Route129_Text_ClarencePostBattle:
	.string "You got your sights on the LEAGUE?\n"
	.string "Keep at the grind, fam!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the deep sea.\p"
	.string "Let’s scrap!$"

Route130_Text_RodneyDefeat:
	.string "This kid is moving awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who’s survived the trenches and won.\l"
	.string "It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered heart finds its peace\l"
	.string "amongst the waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast ocean,\n"
	.string "the world of POKéMON has depths\l"
	.string "beyond our understanding.$"

Route130_Text_KatiePostBattle:
	.string "All the world’s children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "The vibes are bare peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I’m a happy man, truss.$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with POKéMON.\n"
	.string "It’s not an easy swim, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are\n"
	.string "actually different gravy…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "I’m wiped out, man…\p"
	.string "Getting here was easy. It’s the leaving\n"
	.string "that’s a mission.\p"
	.string "Do I even have the energy to make\n"
	.string "the return trip? I’m finished.$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "Blue as far as these eyes can see!\l"
	.string "I’m sick and tired of the water!$"

Route131_Text_HermanDefeat:
	.string "Bleah! I’m done with it!$"

Route131_Text_HermanPostBattle:
	.string "I’m bored of the sea, but swim I must.\p"
	.string "I’m a born swimmer!\n"
	.string "That’s just my life, innit.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should scrap, you and I!$"

Route131_Text_SusieDefeat:
	.string "You’re tough in spite of the way\n"
	.string "you look! Total surprise!$"

Route131_Text_SusiePostBattle:
	.string "Did you see that guy over there whinging\n"
	.string "about being bored of the sea?\p"
	.string "That’s all cap.\n"
	.string "He’s hopelessly in love with the ocean!$"

Route131_Text_KaraIntro:
	.string "Why do men love swimsuits so much?\p"
	.string "They’re all ogling me, it’s peak!$"

Route131_Text_KaraDefeat:
	.string "I’m way out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it’s not the swimsuit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: We’ll work together as siblings\n"
	.string "to take you down!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn’t win even with\n"
	.string "the family combo…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "one with the sea and POKéMON from\l"
	.string " the second they’re born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "The battle would be dead, then.$"

Route131_Text_IanIntro:
	.string "IAN: I’m doing my best together with\n"
	.string "my big sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I did my best for my sis,\n"
	.string "but we still took the L…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "Wherever there’s salt water,\n"
	.string "that’s a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we’ll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I’ll give you some\n"
	.string "elite information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I actually lose?$"

Route131_Text_TaliaPostBattle:
	.string "There’s a weird place nearby.\n"
	.string "A massive tower stands there.\l"
	.string "Why don’t you go check it out?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch, truss.\p"
	.string "We never get vexed.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait.\n"
	.string "I’m not angry. Honestly!\p"
	.string "But boy, you’re strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I used to catch bare colds as a kid,\n"
	.string "but I became totally fit once\l"
	.string "I started swimming, truss.$"

Route132_Text_GilbertDefeat:
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS are always hiking and\n"
	.string "climbing, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "I try not to swim where the currents\n"
	.string "are moving too mad.$"

Route132_Text_DanaDefeat:
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I’ll lose my\n"
	.string "entire sense of place, fam…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you’ll never know until\n"
	.string "you test the waters!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "I never scrap when I know I’ll win.\n"
	.string "I only battle on the razor's edge!$"

Route132_Text_KiyoIntro:
	.string "I contemplate POKéMON 24/7, fam.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose.\n"
	.string "I concede the L.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "You’re a total POKéMON fanatic.\p"
	.string "You’re grinding 24 hours a day,\n"
	.string "aren't you? It shows.$"

Route132_Text_MakaylaIntro:
	.string "I’m always with my husband,\n"
	.string "but I can secure a W without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't elite enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He’s actually making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone’s been watching me intently.\n"
	.string "Was that you, fam?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That’s some serious power!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake the feeling that\n"
	.string "someone’s still watching me.\p"
	.string "I can’t even concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where has my wife gone?\n"
	.string "I’m always with her.\l"
	.string "Can I even win on my own?$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see I couldn't manage\n"
	.string "the W solo after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I’d best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It’s peak that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't moan about other\n"
	.string "people being here anymore.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must be destiny, fam.\l"
	.string "Let’s scrap!$"

Route133_Text_FranklinDefeat:
	.string "Strong!\n"
	.string "Way too strong!$"

Route133_Text_FranklinPostBattle:
	.string "It’s just my luck that an elite TRAINER\n"
	.string "like you would drift here…\l"
	.string "I’m actually cursed, truss.$"

Route133_Text_DebraIntro:
	.string "I’ve led a life of woe and misery…\n"
	.string "I’ve been cast away, and this is where\l"
	.string "I’ve drifted… It’s peak…$"

Route133_Text_DebraDefeat:
	.string "Just another L…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\n"
	.string "I don't want this anymore!$"

Route133_Text_LindaIntro:
	.string "Welcome!\n"
	.string "I’ve been expecting you, darling!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "An elite child TRAINER…\n"
	.string "That is so incredibly annoying!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise the squad like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things my way\n"
	.string "than to be a sheep like everyone else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON, no cap.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You’re stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I’d love to go back to FORTREE,\n"
	.string "but I’ve grown to like this spot, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I’ve lost count, honestly.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings, fam.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become elite like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They’ve got no direction!$"

Route133_Text_ConorDefeat:
	.string "You actually have a sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose your way as you grow older.$"

Route134_Text_JackIntro:
	.string "Even POKéMON that can swim get\n"
	.string "carried away by these currents, fam.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I think the squad actually enjoys\n"
	.string "the fast-running water around here.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC are looking for a fun\n"
	.string "match. You in, fam?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "There’s a collector who’s moving mad\n"
	.string "after the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! That's enough rest!\n"
	.string "It’s time for a scrap!$"

Route134_Text_AlexDefeat:
	.string "Tuckered out again… I’m finished.$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro:
	.string "You’re a TRAINER.\n"
	.string "No need for words. We scrap now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "I challenged you, and yet I took\n"
	.string "the L. I am deeply shamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever, truss.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede the defeat.$"

Route134_Text_AaronPostBattle:
	.string "We’re going back to METEOR FALLS\n"
	.string "for more training.\p"
	.string "You should go, too. It’ll definitely\n"
	.string "toughen up your squad!$"

Route134_Text_KelvinIntro:
	.string "O-our boat!\n"
	.string "The tide carried it away, fam!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Please, stop! Have mercy!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "I know a fainted POKéMON can still\n"
	.string "SURF, but it feels like a violation.$"

Route134_Text_MarleyIntro:
	.string "Can your squad dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such tech existed!\n"
	.string "You’ve defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for speed.\n"
	.string "I’ll just grind harder next time.$"

Route134_Text_ReynaIntro:
	.string "My squad won't be taken down\n"
	.string "that easily!$"

Route134_Text_ReynaDefeat:
	.string "You’re kidding!\n"
	.string "Explain how I even lost!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "You won, fair play!\p"
	.string "I’ll work my way back up by taking on\n"
	.string "every TRAINER I meet on sight!$"

Route134_Text_HudsonIntro:
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonDefeat:
	.string "Now, that’s actually something!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea, fam.\p"
	.string "My buddy’s a timid fellow, so I’m\n"
	.string "proper worried about him.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "The battery is dead.\p"
	.string "Steps needed to charge the\n"
	.string "hardware: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "There are no Trainers about who\n"
	.string "want the smoke…\p"
	.string "The VS Seeker was turned off.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "The other Trainers don't appear\n"
	.string "to be ready for a remix.\p"
	.string "Let's wait till later.{PAUSE_UNTIL_PRESS}$"

