Route3_Text_ColtonRematchIntro::
	.string "Yo!\n"
	.string "I remember you from VIRIDIAN FOREST!$"

Route3_Text_BenRematchIntro::
	.string "Hi! I still love shorts!\n"
	.string "They’re comfy and easy to wear, fam!\p"
	.string "You should definitely be wearing\n"
	.string "shorts too, truss!$"

Route3_Text_JaniceRematchIntro::
	.string "Excuse me!\n"
	.string "You’re still staring at me, aren't you?$"

Route3_Text_GregRematchIntro::
	.string "You’re a TRAINER, right?\n"
	.string "Let’s get into it right now!$"

Route3_Text_SallyRematchIntro::
	.string "That look you’re giving me…\n"
	.string "It’s actually bare intriguing!$"

Route3_Text_CalvinRematchIntro::
	.string "Yo! What is wrong with you?\n"
	.string "You’re still not wearing shorts!$"

Route3_Text_JamesRematchIntro::
	.string "I’ll battle you with the squad\n"
	.string "I’ve been raising since day one.$"

Route3_Text_RobinRematchIntro::
	.string "Eek!\n"
	.string "Did you just push me, fam?$"

Route4_Text_CrissyRematchIntro::
	.string "I’m still catching mushroom POKéMON\n"
	.string "on MT. MOON. The grind never stops.$"

Route6_Text_RickyRematchIntro::
	.string "Oh! You’re that nosy kid who\n"
	.string "was eavesdropping on us!$"

Route6_Text_NancyRematchIntro::
	.string "Excuse me! Didn’t I tell you this\n"
	.string "is a private conversation?\p"
	.string "You shouldn’t be listening in,\n"
	.string "you uncouth person! Total violation!$"

Route6_Text_KeigoRematchIntro::
	.string "I’m trying to find something decent\n"
	.string "that isn't a BUG POKéMON, but…$"

Route6_Text_JeffRematchIntro::
	.string "Huh?\n"
	.string "You want to go again? Say less!$"

Route6_Text_IsabelleRematchIntro::
	.string "Me?\n"
	.string "Well, okay. I’ll play along once more.$"

Route6_Text_ElijahRematchIntro::
	.string "Yo, long time no see!\n"
	.string "Have you actually gotten better?$"

Route8_Text_AidanRematchIntro::
	.string "You’re good at POKéMON, sure, but\n"
	.string "how’s your chemistry grade looking?$"

Route8_Text_StanRematchIntro::
	.string "All right!\n"
	.string "Let’s have another game!$"

Route8_Text_GlennRematchIntro::
	.string "You need strategy to win these scraps.\p"
	.string "Have you been following my advice?$"

Route8_Text_PaigeRematchIntro::
	.string "I’ve collected bare NIDORAN.\n"
	.string "I don’t want them to evolve, but…$"

Route8_Text_LeslieRematchIntro::
	.string "School is cool, but I still think\n"
	.string "POKéMON are way more fun.$"

Route8_Text_AndreaRematchIntro::
	.string "MEOWTH and PERSIAN are so cute,\n"
	.string "meow, meow, meow! High vibes!$"

Route8_Text_MeganRematchIntro::
	.string "We might look silly standing here\n"
	.string "like this, but I can still scrap.$"

Route8_Text_RichRematchIntro::
	.string "I’m a rambling, gaming dude!\n"
	.string "I’m on a mad winning streak right now!$"

Route8_Text_JuliaRematchIntro::
	.string "What’s cute, round, and fluffy?\p"
	.string "You already know the vibes, don't you?$"

Route8_Text_RicardoRematchIntro::
	.string "My bike’s still acting up, man.\n"
	.string "Proper annoying.$"

Route8_Text_JarenRematchIntro::
	.string "Okay, kid!\n"
	.string "Don't expect any mercy this time!$"

Route8_Text_EliRematchIntro::
	.string "ELI: Our twin power became even\n"
	.string "more elite!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Our twin power is powered up!$"

Route9_Text_AliciaRematchIntro::
	.string "We’re battling again?\n"
	.string "This time, you’re finished!$"

Route9_Text_ChrisRematchIntro::
	.string "I haven't forgotten you and your\n"
	.string "good-looking squad from before.$"

Route9_Text_DrewRematchIntro::
	.string "I’m taking ROCK TUNNEL to go to\n"
	.string "LAVENDER…\p"
	.string "But I keep getting stopped by\n"
	.string "everyone on the way! Mad!$"

Route9_Text_CaitlinRematchIntro::
	.string "Don’t you dare patronize me today!\n"
	.string "We’re playing for keeps!$"

Route9_Text_JeremyRematchIntro::
	.string "Bwahaha!\n"
	.string "Great! I was getting bored again!$"

Route9_Text_BriceRematchIntro::
	.string "Hahaha!\n"
	.string "Still a little toughie, I see!$"

Route9_Text_BrentRematchIntro::
	.string "I got up early every day to train\n"
	.string "my squad from cocoons, no cap!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "I’m taking the W this time!$"

Route9_Text_ConnerRematchIntro::
	.string "Go win, my super BUG POKéMON!$"

Route10_Text_MarkRematchIntro::
	.string "Wow, you’re back again?\n"
	.string "Maybe you’re a POKéMANIAC, too?\l"
	.string "Want to see my collection?$"

Route10_Text_ClarkRematchIntro::
	.string "Ha-hahah-ah-ha!\n"
	.string "I can’t stop sneezing, fam!$"

Route10_Text_HermanRematchIntro::
	.string "Hi, kid!\n"
	.string "Did I ever show you my POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "I went out to a POKéMON GYM again.\p"
	.string "…But I took an L, as usual.$"

Route10_Text_TrentRematchIntro::
	.string "Ah!\n"
	.string "This mountain air is legendary!\l"
	.string "It’s so good, I’m never leaving!$"

Route10_Text_CarolRematchIntro::
	.string "My head is starting to spin.\n"
	.string "I’ve been hiking for way too long…$"

Route11_Text_HugoRematchIntro::
	.string "Win, lose, or draw!\n"
	.string "It’s time for the remix!$"

Route11_Text_JasperRematchIntro::
	.string "Competing is the ultimate thrill.\n"
	.string "I still can’t get enough of it!$"

Route11_Text_EddieRematchIntro::
	.string "You know the vibes, right?\n"
	.string "Let’s go, but don’t try any cheats!$"

Route11_Text_BraxtonRematchIntro::
	.string "Hi, there!\p"
	.string "But watch out!\n"
	.string "I’m still laying down some cables!$"

Route11_Text_DillonRematchIntro::
	.string "I only became a TRAINER a bit ago.\n"
	.string "But I think I can secure this W.$"

Route11_Text_DirkRematchIntro::
	.string "Fwahaha!\n"
	.string "I have never taken an L!\p"
	.string "…And if I did, I’ve forgotten all\n"
	.string "about it, truss!$"

Route11_Text_DarianRematchIntro::
	.string "I have never won a battle before…\p"
	.string "Perhaps I’m destined to stay\n"
	.string "this way forever…$"

Route11_Text_YasuRematchIntro::
	.string "I’m the best in my class.\n"
	.string "I train every morning and night, fam!$"

Route11_Text_BernieRematchIntro::
	.string "Keep your eyes peeled for live wires!$"

Route11_Text_DaveRematchIntro::
	.string "I raised my squad carefully.\n"
	.string "They should be ready now.\l"
	.string "This time, they’re taking the W.$"

Route12_Text_NedRematchIntro::
	.string "Yeah!\n"
	.string "I got a bite right here!\l"
	.string "Th-this might be the big one!$"

Route12_Text_ChipRematchIntro::
	.string "You’re finally here.\n"
	.string "Fishing is a waiting game, innit.$"

Route12_Text_JustinRematchIntro::
	.string "Still haven't found a MOON STONE…\n"
	.string "Have you found one yet?$"

Route12_Text_LucaRematchIntro::
	.string "Electricity has always been my\n"
	.string "specialty, fam.\p"
	.string "I don’t know a thing about sea\n"
	.string "POKéMON, though.$"

Route12_Text_HankRematchIntro::
	.string "The FISHING FOOL vs. POKéMON KID!\n"
	.string "Round two—fight!$"

Route12_Text_ElliotRematchIntro::
	.string "I love fishing, don’t get me wrong.\n"
	.string "But I wish I had more work…\l"
	.string "…It’s hard to give up the rod!$"

Route12_Text_AndrewRematchIntro::
	.string "What’s catching, fam?\p"
	.string "You’ll never know unless you beat\n"
	.string "me!$"

Route12_Text_JesRematchIntro::
	.string "JES: I’ll win here today and\n"
	.string "then I’m proposing to my GIA.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: Hey, JES…\n"
	.string "I’ve been waiting a long time now.\p"
	.string "If we win today, I’ll marry you!$"

Route13_Text_SebastianRematchIntro::
	.string "My bird POKéMON definitely remember you!$"

Route13_Text_SusieRematchIntro::
	.string "I want to be the best TRAINER\n"
	.string "while I’m still a kid!$"

Route13_Text_ValerieRematchIntro::
	.string "Wow!\n"
	.string "You got even more elite BADGES!$"

Route13_Text_GwenRematchIntro::
	.string "My cutely raised POKéMON want to\n"
	.string "reacquaint themselves with you.$"

Route13_Text_AlmaRematchIntro::
	.string "I cleaned out my savings and\n"
	.string "bought bare CARBOS, no cap.$"

Route13_Text_PerryRematchIntro::
	.string "I’m not losing this time.\n"
	.string "The wind is blowing my way!$"

Route13_Text_LolaRematchIntro::
	.string "Oh, you’re back?\p"
	.string "Sure, I’ll play with you again,\n"
	.string "sweetie.$"

Route13_Text_SheilaRematchIntro::
	.string "Can’t you just forget that we\n"
	.string "battled before?$"

Route13_Text_JaredRematchIntro::
	.string "What’re you staring at, fam?$"

Route13_Text_RobertRematchIntro::
	.string "I always go with bird POKéMON.\n"
	.string "I’ve dedicated my life to them.$"

Route14_Text_CarterRematchIntro::
	.string "I used TMs to teach the squad\n"
	.string "some elite moves.$"

Route14_Text_MitchRematchIntro::
	.string "My bird POKéMON should be ready\n"
	.string "to scrap this time.$"

Route14_Text_BeckRematchIntro::
	.string "Are you actually using TMs?\n"
	.string "Just holding them is useless, fam.$"

Route14_Text_MarlonRematchIntro::
	.string "Have you taught your bird POKéMON\n"
	.string "how to FLY?\p"
	.string "You’ll be able to soar through the\n"
	.string "sky! Give it a try, truss.$"

Route14_Text_DonaldRematchIntro::
	.string "The legend of the winged mirages…\n"
	.string "You’ve heard the stories, right?$"

Route14_Text_BennyRematchIntro::
	.string "I’m really not feeling it, but okay.\n"
	.string "Let’s go!$"

Route14_Text_LukasRematchIntro::
	.string "Yo!\n"
	.string "I remember your face!\p"
	.string "C'mon, c'mon.\n"
	.string "Let’s go, let’s go, let’s go! Action!$"

Route14_ IsaacRematchIntro::
	.string "You’re back again, huh?\n"
	.string "Stop yapping and battle, fam.$"

Route14_Text_GeraldRematchIntro::
	.string "We’ve been riding here because of\n"
	.string "the wide-open spaces. No speed limits!$"

Route14_Text_MalikRematchIntro::
	.string "POKéMON battle, right?\n"
	.string "Say less! Rumble time!$"

Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, I hope we actually win\n"
	.string "the day. No more Ls!$"

Route14_Text_JanRematchIntro::
	.string "JAN: KIRI, here we go!\n"
	.string "Let’s secure the W for sure this time!$"

Route15_Text_KindraRematchIntro::
	.string "I’m gonna keep scrapping with the\n"
	.string "squad I got in trades. Elite potential!$"

Route15_Text_BeckyRematchIntro::
	.string "You look bare gentle, so I think I can\n"
	.string "actually beat you.\p"
	.string "I’ll give it one more go!$"

Route15_Text_EdwinRematchIntro::
	.string "When I whistle, bird POKéMON\n"
	.string "gather around like a squad.\p"
	.string "They’re amazingly cute, truss!$"

Route15_Text_ChesterRematchIntro::
	.string "Hmm? My birds are shivering!\n"
	.string "Wait, aren't you that elite TRAINER…$"

Route15_Text_GraceRematchIntro::
	.string "Oh, you’re a little cutie!\n"
	.string "Just like a darling POKéMON!\l"
	.string "I remember you now!$"

Route15_Text_OliviaRematchIntro::
	.string "I raise POKéMON for protection\n"
	.string "since I live solo.\p"
	.string "That hasn't changed. Stay safe!$"

Route15_Text_ErnestRematchIntro::
	.string "Yo, kid! C'mon!\n"
	.string "I gapped these off some loser!$"

Route15_Text_AlexRematchIntro::
	.string "Fork over all your cash when you\n"
	.string "take this L, kid!$"

Route15_Text_CeliaRematchIntro::
	.string "What’s cool and happening?\n"
	.string "Trading POKéMON, obviously.$"

Route15_Text_YazminRematchIntro::
	.string "Want to play with my squad\n"
	.string "again? High vibes only!$"

Route15_Text_MyaRematchIntro::
	.string "MYA: Hi, we keep meeting,\n"
	.string "don't we? It’s fate!\p"
	.string "Help me train my little brother\n"
	.string "again? He’s a bit of a mid.$"

Route15_Text_RonRematchIntro::
	.string "RON: My sister's gotten way more\n"
	.string "powerful. It’s scary…$"

Route16_Text_LaoRematchIntro::
	.string "What do you want, fam?$"

Route16_Text_KojiRematchIntro::
	.string "Nice BIKE!\n"
	.string "Hand it over, quick time!$"

Route16_Text_LukeRematchIntro::
	.string "Come out and play, little mouse.\n"
	.string "I’ll treat you right! Hahaha!$"

Route16_Text_HideoRematchIntro::
	.string "Yo, wait a second!\n"
	.string "Don’t call me and then run away!\l"
	.string "That’s a violation!$"

Route16_Text_CamronRematchIntro::
	.string "I’m feeling hungry and mean!\n"
	.string "I really need a punching bag, truss!$"

Route16_Text_RubenRematchIntro::
	.string "Hey, there!\n"
	.string "We’ll have ourselves a legendary time!$"

Route16_Text_JedRematchIntro::
	.string "JED: Are you here to see our\n"
	.string "love, which knows no bounds?$"

Route16_Text_LeaRematchIntro::
	.string "LEA: Sometimes, the intensity of\n"
	.string "our love actually scares me.$"

Route17_Text_RaulRematchIntro::
	.string "I told you, there’s no getting rich\n"
	.string "quick by battling kids. Absolute bait.$"

Route17_Text_IsaiahRematchIntro::
	.string "I’m mighty proud of my bod, kiddo.\n"
	.string "Check the gains! C’mon!$"

Route17_Text_VirgilRematchIntro::
	.string "You out for a stroll or what?$"

Route17_Text_BillyRematchIntro::
	.string "We’re BIKERS!\n"
	.string "We rule these roads, man!$"

Route17_Text_NikolasRematchIntro::
	.string "VOLTORB’s going to seriously\n"
	.string "electrify you today! No cap!$"

Route17_Text_ZeekRematchIntro::
	.string "I leveled up my POKéMON, but it\n"
	.string "absolutely won't evolve. Why, fam?$"

Route17_Text_JamalRematchIntro::
	.string "Gaah! I really need to exercise\n"
	.string "and seriously trim some flab! It’s peak!$"

Route17_Text_CoreyRematchIntro::
	.string "Be a rebel! Stay dangerous!$"

Route17_Text_JaxonRematchIntro::
	.string "Yep, that’s a legendary BIKE!\n"
	.string "How’s it handle? Smooth?$"

Route17_Text_WilliamRematchIntro::
	.string "Get lost, kid!\n"
	.string "I’m absolutely bushed!$"

Route18_Text_WiltonRematchIntro::
	.string "I’ve been checking every grassy\n"
	.string "patch for new POKéMON.\p"
	.string "But the RNG is not on my side…$"

Route18_Text_RamiroRematchIntro::
	.string "Koorukukukoo!\n"
	.string "Is my birdcall getting elite yet?$"

Route18_Text_JacobRematchIntro::
	.string "I warned you before, this is my\n"
	.string "turf, fam!\p"
	.string "I don't want you coming around.$"

Route19_Text_RichardRematchIntro::
	.string "I’m almost warmed up enough to go\n"
	.string "out for a swim. Proper gains!$"

Route19_Text_ReeceRematchIntro::
	.string "Wait! Slow down!\n"
	.string "You tryna have a heart attack, fam?$"

Route19_Text_MatthewRematchIntro::
	.string "I love swimming!\n"
	.string "I guess you're more the surfing type.$"

Route19_Text_DouglasRematchIntro::
	.string "What’s beyond the horizon?\n"
	.string "Have you seen the sights?$"

Route19_Text_DavidRematchIntro::
	.string "I tried diving for POKéMON again,\n"
	.string "but it was a flop like before. Peak.$"

Route19_Text_TonyRematchIntro::
	.string "I look at the sea to forget all\n"
	.string "the bad things that happened.\p"
	.string "…Like taking that L from you!$"

Route19_Text_AnyaRematchIntro::
	.string "You always get to ride your\n"
	.string "POKéMON…\p"
	.string "It looks bare relaxing.\n"
	.string "Can I have it if I win? No cap?$"

Route19_Text_AliceRematchIntro::
	.string "Swimming’s legendary!\n"
	.string "Sunburns? Not so much!$"

Route19_Text_AxleRematchIntro::
	.string "These waters are treacherous!\n"
	.string "You shouldn't have come back, fam!$"

Route19_Text_ConnieRematchIntro::
	.string "I swam here with my friends…\n"
	.string "I’m finished…\l"
	.string "Must we really battle again? Long day.$"

Route19_Text_LiaRematchIntro::
	.string "LIA: You know my brother just\n"
	.string "became a TRAINER, right?\p"
	.string "I want to help him level up, so I\n"
	.string "need your help again, truss.$"

Route19_Text_LucRematchIntro::
	.string "LUC: My big sis taught me all\n"
	.string "about POKéMON.\p"
	.string "I wonder if I’m actually better?$"

Route20_Text_BarryRematchIntro::
	.string "The water is shallow here.\n"
	.string "Bare people swimming today.$"

Route20_Text_ShirleyRematchIntro::
	.string "Are you jealous that I’m\n"
	.string "vacationing on SEAFOAM? High life!$"

Route20_Text_TiffanyRematchIntro::
	.string "I love floating with the fishes\n"
	.string "here among the waves. Chill vibes.$"

Route20_Text_IreneRematchIntro::
	.string "Were you on vacation, too? Or just\n"
	.string "grinding?$"

Route20_Text_DeanRematchIntro::
	.string "Check out my physique!\p"
	.string "It’s even more buff than ever\n"
	.string "before! Mad gains!$"

Route20_Text_DarrinRematchIntro::
	.string "Why are you riding a POKéMON?\n"
	.string "Haven’t you learned to swim yet, fam?$"

Route20_Text_RogerRematchIntro::
	.string "I rode my bird POKéMON here.\n"
	.string "Air travel is the way.$"

Route20_Text_NoraRematchIntro::
	.string "My boyfriend gave me big pearls.\n"
	.string "And they’ve actually grown bigger!$"

Route20_Text_MissyRematchIntro::
	.string "I swam here from CINNABAR ISLAND.\n"
	.string "It wasn’t easy, I told you!$"

Route20_Text_MelissaRematchIntro::
	.string "CINNABAR, in the west, has a LAB\n"
	.string "for POKéMON.\p"
	.string "My daddy works there. He’s elite.$"

Route21_North_Text_RonaldRematchIntro::
	.string "You want to know if the fish are\n"
	.string "biting? Or you want the smoke?$"

Route21_North_Text_WadeRematchIntro::
	.string "I got a big haul again!\n"
	.string "Wanna go for it once more? Say less!$"

Route21_North_Text_SpencerRematchIntro::
	.string "The sea cleanses my body and soul!\n"
	.string "Pure zen, fam!$"

Route21_South_Text_JackRematchIntro::
	.string "I caught my squad at sea.\n"
	.string "And that’s where I train them. Deep!$"

Route21_South_Text_JeromeRematchIntro::
	.string "Right now, I’m in another triathlon\n"
	.string "meet! No rest for the wicked!$"

Route21_South_Text_RolandRematchIntro::
	.string "Ahh!\n"
	.string "Feel the sun and the wind! Pure life!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Hey, cut it out already.\n"
	.string "You always scare away the fish! Long!$"

Route21_South_Text_NolanRematchIntro::
	.string "Keep me company until I get a hit.$"

Route21_North_Text_LilRematchIntro::
	.string "LIL: Huh? A battle again?\n"
	.string "IAN, can’t you do it solo for once?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: My sis is still a slob.\n"
	.string "Help me get her into shape, truss!$"

Route25_Text_JoeyRematchIntro::
	.string "I won’t take an L while I’m here!$"

Route25_Text_DanRematchIntro::
	.string "Dad took me to a legendary party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_FlintRematchIntro::
	.string "I’m a cool guy.\n"
	.string "I’ve actually got a girlfriend!\p"
	.string "I’ll show her how elite I am for\n"
	.string "sure this time!$"

Route25_Text_KelseyRematchIntro::
	.string "Hi!\n"
	.string "My boyfriend is bare cool!\l"
	.string "My conditioning’s top-tier today!$"

Route25_Text_ChadRematchIntro::
	.string "I had this feeling…\n"
	.string "I knew I had to scrap with you again!$"

Route25_Text_HaleyRematchIntro::
	.string "My friend has many cute POKéMON.\n"
	.string "I’m bare jealous, honestly!$"

Route25_Text_FranklinRematchIntro::
	.string "I just trained up on MT. MOON,\n"
	.string "but I’ve still got gas in the tank!$"

Route25_Text_NobRematchIntro::
	.string "A POKéMANIAC lives on the cape.\n"
	.string "Have you seen his collection? It’s mad.$"

Route25_Text_WayneRematchIntro::
	.string "You’re tryna see BILL again?\n"
	.string "First, we scrap, fam!$"

Route24_Text_ShaneRematchIntro::
	.string "I saw your highlights from the grass!\n"
	.string "Let's see if you've still got it!$"

Route24_Text_EthanRematchIntro::
	.string "Okay!\n"
	.string "I’m gonna stomp you this time!$"

Route24_Text_ReliRematchIntro::
	.string "You always look bare busy…\n"
	.string "Aren’t you getting tired of the grind?$"

Route24_Text_TimmyRematchIntro::
	.string "You really must love coming back to\n"
	.string "NUGGET BRIDGE. Looking for a remix?$"

Route24_Text_AliRematchIntro::
	.string "The time we battled…\p"
	.string "Even though I was second in line,\n"
	.string "I was the most elite, wasn't I?$"

Route24_Text_CaleRematchIntro::
	.string "People call this the NUGGET\n"
	.string "BRIDGE, truss!\p"
	.string "You already cleared us, so no more\n"
	.string "Nuggets for you…\p"
	.string "…But you’re always welcome to catch\n"
	.string "another L from us!$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Lying back, rocked by the waves…\n"
	.string "I don’t even notice time slipping by…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "The weather’s gorgeous, fam!\n"
	.string "I’ll try not to spoil the vibes.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "My sunburn is actually starting to\n"
	.string "hurt now… It’s peak…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "The fire bird’s mountain casts\n"
	.string "a massive shadow, innit…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "I have a strong feeling that\n"
	.string "I’m securing the W this time!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Wait! Wait a second, fam!\n"
	.string "I’m sure I’ve hooked a monster!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "You’re gonna help me out with my\n"
	.string "training again? Absolute legend.$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "We haven't missed a single day of\n"
	.string "the grind yet! Consistency is key!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Every morning, before breakfast,\n"
	.string "I swim around this island…\l"
	.string "Three times! Mad cardio, truss!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Dress appropriately for battle!\n"
	.string "Ditch that mid outfit, I said!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "You know, everything tastes elite\n"
	.string "when you’re out in the wild.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "I ate way too much again, so will you\n"
	.string "scrap for some quick cardio?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: My big brother and I make\n"
	.string "an elite combination, truss!\p"
	.string "We won't lose this time!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: Together with KIA, we aren't\n"
	.string "afraid of anything!\p"
	.string "We’ll prove the hype this time!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Are we really doing this again?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Where have you come from, and\n"
	.string "where are you heading, traveler?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "I want to swim without my float\n"
	.string "ring soon. Time to level up.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Yay, yay!\n"
	.string "POKéMON vibes!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Oh, no—didn’t I tell you already?\n"
	.string "Please, stay away from me, fam!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: We’ve gotten way stronger!\n"
	.string "The gains are real!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MEG: You’re not beating us today!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Oh, hello!\p"
	.string "Are you raising your squad in a\n"
	.string "healthy environment? High vibes?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "With these hands, I’ll manifest\n"
	.string "my victory today.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Must I repeat myself?\n"
	.string "I’m tryna paint, fam.\l"
	.string "Please keep out of my sight!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "I haven't made any progress…\n"
	.string "I still can’t find the right angle…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Oh? You’ll give me another\n"
	.string "chance to match wits with you?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "They’re almost finished making the\n"
	.string "pool for my POKéMON.\p"
	.string "You must drop in for the housewarming.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "I’m a top-tier runner.\n"
	.string "I’ve gotten even faster, no cap!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "I say, friend!\n"
	.string "Let us enjoy this legendary time together!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "I’m the eldest of the BIRD BROTHERS.\n"
	.string "Remember the face?\p"
	.string "That’s right—I’m the one who loves\n"
	.string "birds for their beaks! Elite stuff.$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "I’m the middle kid of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I’m the one who loves the wings.\n"
	.string "Let’s scrap again!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "I’m the youngest of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I love birds for their down.\n"
	.string "I didn’t think I’d see you again!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "I’m still having no luck at all.\n"
	.string "A battle’d be a nice change of pace!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Gasp… Gasp…\p"
	.string "I swam here from SIX ISLAND’s port\n"
	.string "in one go again. Cardio king!$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "You always seem to show up while\n"
	.string "I’m in the middle of a swim.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Let’s have another\n"
	.string "2v2 marine scrap today!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: My big sister and I are way\n"
	.string "tougher than before, truss!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Huh?\p"
	.string "I envision my house, but TELEPORT\n"
	.string "always brings me here! The lag is real!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Oh, hello.\n"
	.string "A pleasant breeze is blowing again.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehehe, I’m practicing in secret\n"
	.string "again. Shadow training!$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "What, you’re sick of seeing\n"
	.string "SWIMMERS like me?\p"
	.string "Aww, don’t be hating, fam!\n"
	.string "Battle with me again.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Sigh…\n"
	.string "My boyfriend’s busy again… Peak.$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Come on, tell me—where are the\n"
	.string "mountains around here? I’m lost!$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Hello, POKéMON!\n"
	.string "It’s time to play again! Yay!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Hello, POKéMON!\n"
	.string "It’s time to battle again!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "There appear to be many secrets\n"
	.string "still unsolved in this world, truss.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Hi, didn't we meet before?\n"
	.string "What compelled you to come back here?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "It’s been said there are mysterious\n"
	.string "stones on this island.\p"
	.string "Have you discovered any gems since\n"
	.string "we last met?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "A rematch with you, way up here!\n"
	.string "The vibes are high!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "I’m pretty familiar with the land\n"
	.string "around these parts. Local expert!$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "I sensed your approach, fam.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping. Deep lore.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Kyahaha!\p"
	.string "Coming back won’t change a thing.\n"
	.string "I’ll flick you away effortlessly!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Howdy! You’re a member of my\n"
	.string "fan club, isn’t that right? No cap?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "This island is way too spread out…\n"
	.string "Patrolling the place is a drag…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "I don’t forgive people who move mad\n"
	.string "and abuse POKéMON! No way!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: I’ll team up with JON and\n"
	.string "we’ll battle together again. Synergy!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: When I’m with EVE, it feels\n"
	.string "like we could never lose. Period.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Let’s have another battle.\n"
	.string "My conditioning is top-tier!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "It doesn't matter if you have the\n"
	.string "strongest POKéMON on paper…\p"
	.string "It doesn't mean a thing if you don't\n"
	.string "have the IQ to use them properly!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "I work to protect the environment.\n"
	.string "In turn, nature protects me, truss.$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Every time we meet, you’ve got those\n"
	.string "legendary shoes on. Fresh!$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "You must have gotten tougher.\n"
	.string "Let me battle you—please! I need it!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "I was given an elite education\n"
	.string "to become this strong.\p"
	.string "I won’t take an L this time.\n"
	.string "Absolutely not!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LEX: My darling NYA, together\n"
	.string "we are securing the W for certain!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: I won’t drag down my mentor\n"
	.string "LEX! We’re gonna win!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Have you discovered anything about\n"
	.string "this stone chamber? Deep mysteries…$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "A mystic POKéMON is said to sleep\n"
	.string "inside here. High tier lore!$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "My teacher is showing me how to\n"
	.string "paint even more scenes. Elite!$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Today, on top of our lesson,\n"
	.string "we came to check the chamber again.$"

