CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "It's the POKéMON PRINTER!\p"
	.string "I can put a fresh print of your squad\n"
	.string "on the back of your TRAINER CARD.\p"
	.string "Only ¥50 to get it sorted.\n"
	.string "You want to try it?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "You’re short on cash, babes.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Pick which style you’re feeling.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Give me a big smile for the lens!\n"
	.string "Three… Two… One…\p"
	.string "Flash!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Your POKéMON print is looking leng!\n"
	.string "Check your TRAINER CARD.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Hehe…\n"
	.string "I’ve copped so many STICKERS.\l"
	.string "I wish I had a way to show them off…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Oh, elite!\n"
	.string "You’ve come to the right spot!\p"
	.string "Look, look! See? See?\n"
	.string "These are my STICKERS!\l"
	.string "Look at the collection!\p"
	.string "I bet you want some.\n"
	.string "Truss, I know you do!\p"
	.string "I’ll give you a STICKER if you can\n"
	.string "brag about something mad you've\l"
	.string "done on your journey.\p"
	.string "What’s the motive? What you got?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Give me a proper brag.\n"
	.string "I’ll give you a STICKER for it.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Oh, hi!\n"
	.string "The top boy is back.\p"
	.string "What legendary stuff are you\n"
	.string "bragging about today?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Oh, wow, you actually made it into\n"
	.string "the HALL OF FAME.\p"
	.string "That’s a serious achievement, yup!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Oh, wow, you’ve hit the\n"
	.string "HALL OF FAME bare times!\p"
	.string "That’s impressive, yup!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Whoa! You’ve made it into the\n"
	.string "HALL OF FAME that often?\l"
	.string "That’s actually mad, yup!\p"
	.string "You basically run the LEAGUE!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "No way! You’ve gone into the\n"
	.string "HALL OF FAME that many times?\p"
	.string "You’re on another level, yup!\n"
	.string "I have to give you this one.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "The HALL OF FAME STICKER was\n"
	.string "slapped on the TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Bring me a better story next\n"
	.string "time, yeah?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Oh, no, I'm out.\p"
	.string "You’re basically a living legend.\n"
	.string "I’ve got no STICKERS left for you.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Oh, wow, there are POKéMON EGGS?\n"
	.string "I didn’t even know that!\p"
	.string "That’s a cool shout, yup!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowEggsLow::
	.string "You’ve hatched that many EGGS?\n"
	.string "You’re really dedicated to it!\p"
	.string "That’s impressive, yup!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Whoa! You’ve hatched a whole\n"
	.string "heap of EGGS!\p"
	.string "You’re an EGG-hatching machine!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Wh… You hatched THAT many?\p"
	.string "What is this love for EGGS about?\n"
	.string "It’s beyond incredible, yup!\p"
	.string "You’re moving too elite, I tell you.\n"
	.string "I have to give you this.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "The EGG STICKER was slapped\n"
	.string "onto the TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Bring me a better story next\n"
	.string "time, yeah?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Oh, no, I'm out.\p"
	.string "You’re basically a living legend.\n"
	.string "I’ve got no STICKERS left for you.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Oh, wow, you’ve been winning\n"
	.string "your link battles?\p"
	.string "You’re proper strong, yup!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "You’ve smoked your friends bare\n"
	.string "times in link battles, huh?\p"
	.string "You’re impressively tough, yup!\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Whoa! You’ve beaten your friends\n"
	.string "a scary amount of times.\p"
	.string "You sure you still have friends?\n"
	.string "Take one of these.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Wh… Mad! Just mad!\n"
	.string "You’ve won more than I can count!\p"
	.string "It’s actually scary thinking\n"
	.string "about how much you carry.\p"
	.string "You’re the stuff of nightmares!\n"
	.string "I have to give you this.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "The VICTORY STICKER was slapped\n"
	.string "onto the TRAINER CARD.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Bring me a better story next\n"
	.string "time, yeah?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Oh, no, I'm out.\p"
	.string "You’re practically a living legend.\n"
	.string "I’ve got no STICKERS left to give.$"

