CeladonCity_DepartmentStore_3F_Frlg_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_CounterTutor::
	goto EventScript_CounterTutor
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV1::
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV2::
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV3::
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV4::
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_Poster::
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
	.string "Listen, every mon you bag comes\n"
	.string "with an ID and the OT, yeah?\p"
	.string "OT means 'Original Trainer'—the\n"
	.string "boss who first caught it in the ends.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
	.string "Safe! My boy is swapping his\n"
	.string "KANGASKHAN for my HAUNTER.\l"
	.string "Swap shop's looking peak today!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
	.string "Allow it, HAUNTER!\p"
	.string "I’m gassed for HAUNTER, I’ve got\n"
	.string "bare of them in my boxes.\p"
	.string "Wait... what?\p"
	.string "My HAUNTER just leveled up into\n"
	.string "a whole different mon mid-trade!\l"
	.string "That’s actually mental!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
	.string "You can check if a mon is from your\n"
	.string "circle or a random by the ID numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
	.string "It’s a vintage console. Proper\n"
	.string "old school bits.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
	.string "One of them long RPGs.\n"
	.string "Man’s got no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
	.string "A football game!\n"
	.string "The old man would love that.$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
	.string "A puzzle game.\n"
	.string "Looks bare addictive, still.$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
	.string "A fighting game!\n"
	.string "Looks like a proper scrap!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
	.string "3F: THE PLUG FOR GAMES$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
	.string "Red and Green version posters.\n"
	.string "Classic vibes in the building.$"

Text_CounterTeach::
	.string "Yo! I finally beat the Elite Four\n"
	.string "and finished my journey.\p"
	.string "You’re still on the grind? Let me\n"
	.string "bless you with a cold move.\p"
	.string "I’m talking about COUNTER.\p"
	.string "It’s for when a pagan hits you\n"
	.string "and you want to send that energy\l"
	.string "straight back at 'em twice as hard!$"

Text_CounterDeclined::
	.string "You’re not feeling the vibes?\n"
	.string "Holla at me if you change your mind.$"

Text_CounterWhichMon::
	.string "Which mon is gonna learn how to\n"
	.string "run a COUNTER?$"

Text_CounterTaught::
	.string "Make sure you use that COUNTER\n"
	.string "if anyone tries to move to you!$"

