AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring::
	.string "This spot is prime for a look around,\n"
	.string "no cap. It’s moving in here!\p"
	.string "I’m betting there’s some high-value\n"
	.string "loot stashed on this deck.$"

